### ISSUE TITLE
[CLI] Need a `flow-typed create`

### ISSUE THREAD

**Issue by jeffmo** [flow-typed/flow-typed#104]
The process of creating all the directories and names and such (as described in CONTRIBUTING.md) is a bit tedious.

@nmote pointed out that we could probably make this a lot easier with some kind of `flow-typed create` command that prompts the user for lib name, lib version, flow version range(s), etc and creates files with TODOs in them (or whatever).

**Comment by ryyppy** [comment]
I actually already started something for creating the structure... but now we have the windows support / WIP-namespace discussions, which will influence the design...

See #225 
See #178

**Comment by ryyppy** [comment]
Oh wow, time flies by and the windows support is now merged.

What I wondered, isn't this `create` command basically the same as the `create-stub` thing as seen in #323 ?

Or is this more for the quick and dirty hack?

**Comment by jeffmo** [comment]
Yea, now that things have evolved a bit and we have `create-stub`, maybe we just want `flow-typed contribute` which takes a libdef file/test file(s)/flow version/libversion, runs the tests, opens a PR for them, and outputs a link to the PR.

I imagine this "contribute" command being useful for both sending in new libdefs as well as sending in *updates* to existing libdefs:

For example, let's say I install some libdef and realize that one of its methods isn't quite right. I should be able to tweak the locally-installed libdef to get it right, then use `flow-typed contribute` to send my changes back up (and write some tests to cover my changes).

For the case where the command is used on an existing libdef or stub (we can detect this with the signature put at the top of all installed stubs and libdefs), we should confirm that the specified versions/library name accurately matches the ones that are actually installed for the project. Hopefully this will help keep some accuracy on versions that people are writing libdefs for.

**Comment by ryyppy** [comment]
I love this idea. So there will be a lot of interaction with the locally checked out `flow-typed` repo installed in the home dir? I am not sure how the process should look like... this would require a contributor to have a separate fork and configure it for the `flow-typed` bin, right?

* E.g. I forked `flow-typed` and put it in `~/.flow-typed/contrib`
* I type `flow-typed contribute redux-saga` (after editing some stuff)
* (syncs up ~/.flow-typed/contrib` to current master)
* (does a `checkout -b update-redux-saga`)
* (adds the changes / creates new libdefs and runs the tests for redux-saga)
* (pushes the PR to the fork repo as `origin/update-redux-saga`)
* (? sends a PR to the official flow-typed repository ? - not sure how to do this)

Or am I completely mistaken?

For the signature verification part: This should actually be part of the `install` command...? I mean, whenever I use `contribute`, the file will definitely be different to the official version?

**Comment by Brianzchen** [comment]
Recently created the `create-def` command that does the tedious work of creating the files structure for a new def given a name and lib version. If there needs to be more enhancements let me know
