### ISSUE TITLE
A lot of functions don`t use $ReadOnlyArray type in the Lodash type definitions

### ISSUE THREAD

**Issue by mtnt** [flow-typed/flow-typed#1099]
A `$ReadOnlyArray` type is a subtype of `Array`. Many declarations, where incoming array will not be modified, has just an `Array` as type. It should be `$ReadOnlyArray` for consistent use.

**Comment by GAntoine** [comment]
Would you be up to open a PR that fixes this?

**Comment by Schedulaar** [comment]
Also a lot of functions should use `$ReadOnly<{ [id: any]: T }>` instead of just `{ [id: any]: T }` as input parameter. For example `omitBy` should have the type
```js
    omitBy<A, T: $ReadOnly<{ [id: any]: A }>>(
      predicate: OPredicate<A>
    ): (object: T) => Object;
    omitBy<A, T: $ReadOnly<{ [id: any]: A }>>(predicate: OPredicate<A>, object: T): Object;
```
instead of
```js
    omitBy<A, T: { [id: any]: A }>(
      predicate: OPredicate<A>
    ): (object: T) => Object;
    omitBy<A, T: { [id: any]: A }>(predicate: OPredicate<A>, object: T): Object;
```
