### ISSUE TITLE
Flow Typed Browser

### ISSUE THREAD

**Issue by lematt1991** [flow-typed/flow-typed#1122]
I've thrown together a really simple app for browsing flow-typed source code.  It uses the Github API, so it will always have the most up-to-date versions of all packages.  I frequently find myself wanting to look through the source code of the type declarations for different packages contained in this repository, but find Github's browser a bit clunky.  

I was wondering if there is any interest in incorporating this into this repo.  It currently lives [here](https://github.com/ml9951/flow-typed-browser) (live version [here](https://ml9951.github.io/flow-typed-browser/)), but could easily get thrown into a `gh-pages` branch in the `flow-typed` repository.

![](https://github.com/ml9951/flow-typed-browser/raw/master/images/demo.gif)

**Comment by GAntoine** [comment]
Damn, that's sleek!

Funny enough, I wrote something similar a few months a go (without the in-app code viewer, which is super neat), at the [request](https://github.com/flowtype/flow-typed/issues/848) of a couple users: http://flowtyped.gantoine.com/

It's more of a search tool then a code viewer, but does give you install commands on-the-fly. How would you feel about merging our tools? They seem to share a lot of similarities in build. Combined, you'd have a pretty slick online interface for viewing code and searching the repo.

@jeffmo Thoughts on this?

**Comment by ml9951** [comment]
@GAntoine, that looks great.  I would certainly be interested in merging these two projects.  I'll defer to one of the flowtype members as to whether it should be housed under this organization or elsewhere.

**Comment by marudor** [comment]
I'm all for hosting it "officially"
CC @calebmer

**Comment by Brianzchen** [comment]
Actually what was built here has been completely incorporated into github, on the main repo page you can just press `T` and you can search files quite effectively. Going to close, but if there's additional value we can gain from a custom website please raise.
