### ISSUE TITLE
Prettier toolchain causing unexpected errors

### ISSUE THREAD

**Issue by vicapow** [flow-typed/flow-typed#1187]
https://github.com/flowtype/flow-typed/pull/1143 is causing a lot of headache when working with definitions. Everything seems to work fine after committing. Then, under the scenes, the files are rewritten in ways that cause errors. Specifically troublesome for tests that have `// $ExpectError` on lines that then get word wrapped.

**Comment by johnhaley81** [comment]
Prettier should probably be added to the linter and then for people with linters installed in their editor/IDE files can be fixed as you save and not after the fact when you're trying to commit. For people without integration they can see that prettier is failing the linter when they make their commit and then it's move obvious what's breaking and not the fact that prettier just changed your files and for some reason your tests are now failing when they weren't before you were about to make a commit. This makes prettier a better DX IMO.

**Comment by johnhaley81** [comment]
Ah, I see that it is run through `eslint` in the `cli` package but done via `lint-staged' section in the `definitions` package.

**Comment by jedwards1211** [comment]
According to `eslint-plugin-prettier` docs:

> This plugin works best if you disable all other ESLint rules relating to code formatting, and only enable rules that detect patterns in the AST. (If another active ESLint rule disagrees with prettier about how code should be formatted, it will be impossible to avoid lint errors.) You can use eslint-config-prettier to disable all formatting-related ESLint rules.

> If your desired formatting does not match the prettier output, you should use a different tool such as prettier-eslint instead.

Part of the problem is that you're not using `eslint-config-prettier`.

**Comment by jedwards1211** [comment]
To make matters worse, the prettier config inlined in `.eslintrc` an `.prettierrc` differ in `bracketSpacing` and `trailingComma` settings.
