### ISSUE TITLE
redux-form

### ISSUE THREAD

**Issue by kristian-puccio** [flow-typed/flow-typed#121]
The FormConfig type doesn't allow settings to be passed from props.

I do this all the time say if the list of fields is dynamic I'll have a container that is connected to redux which creates the array of fields and passes it to the redux-form wrapped component.

See http://redux-form.com/5.2.4/#/api/reduxForm?_k=do3dix

**Comment by ryyppy** [comment]
Hey!
Hey, for me it sounds like your wrapper component / container passing down the `fields` is too loosely typed... how would the props definition of that container look like?

**Comment by kristian-puccio** [comment]
I'll set you up a sample project when I get a chance.

Cheers

**Comment by kristian-puccio** [comment]
Here is an example

https://github.com/kristian-puccio/form-flow

```
index.js:28
 28: reduxForm({})(FormPage);
     ^^^^^^^^^^^^^ function call
 63:   declare function reduxForm(config: FormConfig, mapStateToProps?: Function, mapDispatchToProps?: Function, mergeProps?: any, options?: Object): (component: React.Component) => React.Component;
                                          ^^^^^^^^^^ Library type error:. See lib: flow-typed/redux-form.js:63
 63:   declare function reduxForm(config: FormConfig, mapStateToProps?: Function, mapDispatchToProps?: Function, mergeProps?: any, options?: Object): (component: React.Component) => React.Component;
                                          ^^^^^^^^^^ property `form`. Property not found in. See lib: flow-typed/redux-form.js:63
 28: reduxForm({})(FormPage);
               ^^ object literal
```

**Comment by kristian-puccio** [comment]
ugg just a sec!

**Comment by ryyppy** [comment]
Cool! Thanks for the sample and sorry for the late reply... 
I will check that out as soon as I have some time :-)

**Comment by kristian-puccio** [comment]
I've started using redux-form v6 and here is my flow config for it: https://gist.github.com/kristian-puccio/65d32833306ba8b697b1b3db041aeb44

I'll make a pull request and add tests when I'm not quite so under the pump.

**Comment by jeffmo** [comment]
Nice! Please do send the pull request when you get a chance :)

Going to mark this issue as a libdef request for now until we get the libdef updated (so that others can find it if they hit the same issue)

**Comment by kristian-puccio** [comment]
Looks like there is a lot of work going on for a typescript def at the
moment.

I'll look at adding the missing bits from that

**Comment by aaronjensen** [comment]
Here's an updated def which includes a props safe `Field` component: https://gist.github.com/aaronjensen/54643af48aedb2f7eba424d9434ca99f

**Comment by stunaz** [comment]
@aaronjensen could you please provide it a pr for v6 version?

**Comment by aaronjensen** [comment]
@stunaz it's not complete and I don't have the time to complete it just yet. I'll open a pr when I get a chance.

**Comment by jacobk** [comment]
@aaronjensen great job with the initial libdef, just a question. How do you declare props on components passed to the `component` prop of fields?

**Comment by aaronjensen** [comment]
@jacobk thanks! I'm not sure what you mean, I don't do anything special, I just declare the props normally.

**Comment by aaronjensen** [comment]
Actually, maybe you mean this:

```js
import type { FieldInputProps } from 'redux-form'

export type Props = {
  filter?: InputFilter,
  disabled?: boolean,
  id: string,
  label?: string,
  placeholder?: ?string,
  tag?: string,
  type?: InputType,
  onFieldBlur?: (e: Event) => void,
  onKeyDown?: (e: KeyboardEvent) => void,
} & FieldInputProps
```

**Comment by jacobk** [comment]
@aaronjensen Thanks, that's exactly what I mean. I was confusing myself trying to use `FieldProps<P>` which became pretty weird ;)

**Comment by patricktoy** [comment]
I'm hoping someone here can help me with understanding how to properly type this. This is just a dumbed down example, in an effort to properly type a wrapped component when passed to the Field HoC.

```
// @flow

import React from 'react';
import { Field } from 'redux-form';
import type { FieldInputProps } from 'redux-form';

type TestComponentProps = {
    someValue: string
} & FieldInputProps;

const TestComponent = ({ input: { onChange, value }, meta: { error }, someValue }: TestComponentProps): React.Element<*> => (
    <div>{someValue}</div>
);

type FieldWrapperProps = {
    name: string
};

const FieldWrapper = ({ name, ...props }: FieldWrapperProps): React.Element<*> => (    
    <Field name={name} component={TestComponent} {...props} />
);
```

I receive the following error:
```
56:     <Field name={name} component={TestComponent} {...props} />
                                       ^^^^^^^^^^^^^ arrow function. This type is incompatible with
 44:     component: ClassComponent<void, P, void> | FunctionComponent<P> | string
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: type application of polymorphic type: type `ClassComponent` | type application of polymorphic type: type `FunctionComponent` | string.
```

This is only a problem when intersecting `FieldInputProps` and `TestComponentProps` - for example, this works without error:

```
const TestComponent = ({ input: { onChange, value }, meta: { error } }: FieldInputProps): React.Element<*> => (
    <div></div>
);

type FieldWrapperProps = {
    name: string
};

const FieldWrapper = ({ name, ...props }: FieldWrapperProps): React.Element<*> => (    
    <Field name={name} component={TestComponent} {...props} />
);
```
