### ISSUE TITLE
WithTheme doesn't work styled-components

### ISSUE THREAD

**Issue by klaasn** [flow-typed/flow-typed#1216]
This test case for a stateful react component

class NeedsThemeStateFullReactClass extends React.Component<{ foo: string, theme: Theme }, { open: boolean } > {
  render() { return <div />; }
}

const NeedsStateFullClass: React.Component<{ foo: string }, { open: boolean }> = withTheme(NeedsThemeStateFullReactClass);

Gives the following error:
ERROR: styled-components_v2.x.x/flow_v0.53.x-
 * styled-components_v2.x.x/flow_v0.53.x- (flow-v0.53.1): Unexpected Flow errors(2):
   Error: 1-test_styled-components_v2.x.x.js:207
   207: const NeedsStateFullClass: React.Component<{ foo: string }, { open: boolean }> = withTheme(NeedsThemeStateFullReactClass);
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: type application of polymorphic type: class type: $npm$styledComponents$ReactComponent. This type is incompatible with
   207: const NeedsStateFullClass: React.Component<{ foo: string }, { open: boolean }> = withTheme(NeedsThemeStateFullReactClass);
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React$Component

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
