### ISSUE TITLE
if I uninstall npm package and run flow-typed update, the definitions are not removed

### ISSUE THREAD

**Issue by capaj** [flow-typed/flow-typed#1230]
I would expect the definitions to be removed when the package.json no longer contains the dependency.

**Comment by GAntoine** [comment]
As nice as that would be, how do we deal with libdefs which were modified by the user?

**Comment by TravisHoover** [comment]
When I need to do this, I just remove the flow-typed directory and run `flow-typed install`. It will only put back currently installed packages.

**Comment by AndrewSouthpaw** [comment]
Agreed with @TravisHoover. It's like deleting a line from `package.json` directly -- you're not going to see it removed from `node_modules`, you have to run `npm uninstall` or `yarn remove`.

If there were a post-uninstall hook that we can connect to with yarn or npm (don't know if that exists), and you wanted to set the system up for removing the appropriate libdefs from `/flow-typed` when those happen, that would be a reasonable approach.
