### ISSUE TITLE
styled-components - props requirements is lost

### ISSUE THREAD

**Issue by jonasi** [flow-typed/flow-typed#1288]
Prop validation is not preserved when using styled-components 2 with flow 0.53+.

The test below illustrates:

```js
class CompWithProps extends React.Component<{ foo: string }> {
    render() { return <div />; }
}

const StyledCompWithProps = styled(CompWithProps)``;

// $ExpectError
<CompWithProps />; // missing foo
<CompWithProps foo="hey" />;

// $ExpectError
<StyledCompWithProps />; // missing foo, SHOULD FAIL - but does not
<StyledCompWithProps foo="hey" />;
```

**Comment by kalley** [comment]
I have a branch where I've been working on this, but need to update tests across the board. If you're interested in testing it out in the meantime, I have a gist (you can just replace the one in flow-typed or put it wherever you have any local libdefs): https://gist.github.com/kalley/22859a23a70e5800d47e3cdd43ad4fbc

**Comment by aaronjensen** [comment]
@kalley I've been starting down the path of typing glamorous and I'm stuck on `defaultProps`. It looks like the existing styled-components libdef and the one you're working on have similar problems to what I'm seeing. 

It seems that assigning `defaultProps` after the declaration of something is special cased in flow so I can't seem to replicate it by doing something like:

```js
class CompWithProps extends React.Component<{ foo: string }> {
    render() { return <div />; }
}

const StyledCompWithProps = styled(CompWithProps)``;
StyledCompWithProps.defaultProps = {foo: 'hi'}
```

In my glamorous types, no matter what I do, I either get what @jonasi is reporting here--all prop validation is stripped, or I get what I get when I try pulling out your definitions from your gist--setting `defaultpProps` is ineffective.

[try in flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFAwCeYWcAJAHZgguoMA2WAEwDCJSGyxsYqFiPARxkgOrAYACwAiWAsgCuvGAAViYVAB4acOJu17Dx1AC44AbwC+AGgtwjEE07c0AHxwALyYVDAyovISMAAqjFimPibBAGQucAJauvopjlY5tvlwrjTluLxo6ABynNx8grJisdIAyo3C0Qow5pbWuXa+qJ6W+aNwANJY9KhBcFgAHjASAujYeJHNMZLJ9sHOXjzIMMC4WUV59k4DxfY0ZTTZlciUcAQ6bPjA8nArPMlAgAKAyhYLINj0ACUTiEVVQZjqXB49H4XTkPXanW2PVMbnc3gJADcIMABIFAgBuCryHhwABiEAgoT+WB4QKBAH1-IsHGwdCAAEZYKCuKFguD83i8KHUxkQAB02RsV2GLOcvIAzK5KZYaKZ5QB6QJAA)

Is there a way around this or does this actually work in your libdef and I'm just missing something?

Thanks!

**Comment by kalley** [comment]
@aaronjensen. I don’t think I’ve taken that use case into account as that was not the problem most people were having, but it’s a good one. My version takes care of the case where the compnent you’re wrapping has `defaultProps`, like:

```js
const MyComponent = ({ foo }: { foo: string }) => <div>{foo}</div>

MyComponent.defaultProps = { foo: 'bar' }

const MyStyledComponent = styled(MyComponent)
```


I would argue that if you want to define `defaultProps` on a styled component, that’s a good case for using [`.attrs`](https://www.styled-components.com/docs/basics#attaching-additional-props). I hadn’t seen anyone setting that on a styled component before.

That said, it still seems a valid use case, and something I can definitely look into attempting to fix in my version. Thanks for the heads up on that. I definitely would like to make the definition better for as many use cases as possible.

**Comment by aaronjensen** [comment]
> I would argue that if you want to define defaultProps on a styled component, that’s a good case for using .attrs. I hadn’t seen anyone setting that on a styled component before.

Right, as it stands, it's one of the [recommended approaches](https://glamorous.rocks/api#__next) in glamorous, but glamorous also has a `withProps` option that may end up being the only way to get default props working in flow. 

But yes, if you figure out an approach that works I'd appreciate hearing about it. Thanks!

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
