### ISSUE TITLE
lodash_v4.x.x type of object key in _.find

### ISSUE THREAD

**Issue by liamfd** [flow-typed/flow-typed#1330]
Hello,

Within the lodash type definiton, a few functions look like this:

```
    // ... the array version
    find<V, A, T: { [id: string]: A }>(
      object: T,
      predicate?: OPredicate<A, T>,
      fromIndex?: number
    ): V,
```

I was wondering if it would be possible to remove or loosen the restriction that the the `id`s of the `T` object be strings. Flow seems to allow any type to be used as an indexer property. While I'm not suggesting its a good idea to use things like objects as keys, I think its fairly common to have non string indexer properties of types that can be cast to strings more elegantly. For instance, I have something like this:

```javascript
type User = {id: number, name: string};
type MyMap = {[id: number]: User};
const findUser = (user_map: MyMap) => {
  return _.find(user_map, user => user.name === 'John Smith');
};
```

Which appears to work properly in lodash, but throws a type error about the indexer property not being a string:

```
  Error:
  127: export const findMyEntity = (entity_map: {[number]: MyEntity}) => {
                                                  ^^^^^^ number. This type is incompatible with
  340:     find<V, A, T: { [id: string]: A }>(
                                ^^^^^^ string. See lib: flow-typed/npm/lodash_v4.x.x.js:340
```

Is there anything in lodash or Flow that would prevent us from relaxing this restriction by using either an enum of reasonable key types (ie. `string | number`) or even something like `{ [id: *]: A }`?

I'd be happy to try my hand at a pull request, just wanted to clarify whether or not this was intended before I jumped in.

**Comment by guyfedwards** [comment]
I would also like to add the usecase of an object thats keyed by an opaque type, this results in `MyOpaque is incompatible with string in the indexer property`
