### ISSUE TITLE
styled-components: styled SVG modules fail

### ISSUE THREAD

**Issue by dfalling** [flow-typed/flow-typed#1376]
```javascript
import Logo from './logo.svg';

const StyledLogo = styled(Logo)`
  fill: #000000;
`;
```

Results in
`error| function call: Function cannot be called on any member of intersection type intersection`

logo.svg is just
```xml
<?xml version="1.0" encoding="utf-8"?>
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
...
```

I'm having trouble decyphering the libdef to figure out what needs to be changed in a PR.

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
