### ISSUE TITLE
Mongoose: gathering of fixes

### ISSUE THREAD

**Issue by Delapouite** [flow-typed/flow-typed#1445]
Hello

I'm starting this issue as a central place to collect problems with current Mongoose typedef.
During the next few days I'll try to complete this issue as much as I can. highlighting the wrong/missing parts along with relevant links and explanations.
Then I'll try to provide a PR in one go soon, but feel free to help if you want :)

- `plugin()`, `set()`, `loadClass()` are chainable, should return `this`

flow-typed: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js#L129
mongoose: https://github.com/Automattic/mongoose/blob/master/lib/schema.js#L1211-L1229

- `model()` can take only one arg to retrieve a model.

example: `var Venue = db.model('Venue');`

flow-typed: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js#L450
mongoose: https://github.com/Automattic/mongoose/blob/master/lib/connection.js#L971

- `static()` function is not recognised

example of flow output:

```
Error: server/models/inviteSchema.js:91
 91: inviteSchema.static('add', function add (mount, email, name) {
                  ^^^^^^ property `static`. Property not found in
 91: inviteSchema.static('add', function add (mount, email, name) {
     ^^^^^^^^^^^^ Mongoose$Schema
```

but the `static()` function is defined in the typedef: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/mongoose_v4.x.x/flow_v0.50.x-/mongoose_v4.x.x.js#L147-L148

is it a naming collision with the `static` keyword ?

Related work for `express.static()` function: https://github.com/flowtype/flow-typed/pull/1072/files

**Comment by Delapouite** [comment]
related mongoose issue https://github.com/flowtype/flow-typed/issues/1469

**Comment by wtfleming** [comment]
Mongoose 5 was released in January https://github.com/Automattic/mongoose/blob/master/History.md
and there are no mongoose_v5.x.x definitions yet
There haven't been that many changes, and I assume the work is mostly adapting the 4.x.x ones over, but I'm not familiar enough with flow yet to attempt to update/create the definitions, but would love to have them.

**Comment by stepankuzmin** [comment]
So need to wait untill mongoose_v5.x.x definitions is released?

**Comment by oonsamyi** [comment]
I rewrote static methods in types and it worked for me.

_Before:_
```js
  static (method: string, fn: Function): this;
  static (methods: { [method: string]: Function }): this;
```
_After:_
```js
  static: (method: string, fn: Function) => this;
  static: (methods: { [method: string]: Function }) => this;
```
