### ISSUE TITLE
Flow Types for external code (like elasticsearch), How to share them?

### ISSUE THREAD

**Issue by A-Tokyo** [flow-typed/flow-typed#1461]
I have been using [elasticsearch](https://www.elastic.co/) lately with nodeJS, and I needed to utilize flow for that. The solution I found was to simply create a file in my flow types exporting/declaring elasticsearch related flow types.

I was wondering how can I share something like that with the community? I think some people would like to use flow for external code like in my case. Any ideas? 

Should I just create an npm package with the flow types?, is there a way to maybe add it here somehow? or should we just rely on each developer to create their own flow files for external services like in this case?

An example from the file I use to declare elasticsearch flow types:

```
/** Geo bounding box */
export type esGeoBoundingBoxType =
    {|
      top_left: {
        lat: number,
        lon: number,
      },
      bottom_right: {
        lat: number,
        lon: number,
      },
    |}
  | {|
      top_right: {
        lat: number,
        lon: number,
      },
      bottom_left: {
        lat: number,
        lon: number,
      },
    |}
  | {|
      top: number,
      left: number,
      bottom: number,
      right: number,
    |};

/** Elastic search distance units. */
export type esDistanceUnitsType =
  | 'mi'
  | 'miles'
  | 'yd'
  | 'yards'
  | 'ft'
  | 'feet'
  | 'in'
  | 'inch'
  | 'km'
  | 'kilometers'
  | 'm'
  | 'meters'
  | 'cm'
  | 'centimeters'
  | 'mm'
  | 'millimeters'
  | 'NM'
  | 'nmi'
  | 'nauticalmiles';
```

**Comment by MatrixFrog** [comment]
My understanding is that you just create a pull request adding it to this repo under https://github.com/flow-typed/flow-typed/tree/master/definitions/npm (assuming that you're using the https://www.npmjs.com/package/elasticsearch package)

**Comment by A-Tokyo** [comment]
@MatrixFrog I would have done what you said if I was using the official ES node package. However I am communicating with the API directly. And even if I was using the package, there are still some defs that don't fall under the scope of the package since mostly I `type` responses ( :
