### ISSUE TITLE
Missing change information on releases

### ISSUE THREAD

**Issue by doberkofler** [flow-typed/flow-typed#1468]
Unfortunately the releases to not contain a change information nor is there a change log file that indicates what has been changes in a new release.

**Comment by GAntoine** [comment]
I totally agree, it's one of the things I'm working to have implemented, at least from the perspective of the CLI. Were you thinking of a changelog for definitions?

**Comment by doberkofler** [comment]
I think that the usual simple release information in a change log file that is also visible in the release description on github would do the job for cli.
For the definitions we would really need some more advanced mechanism as I eluded https://github.com/flowtype/flow-typed/issues/819.
