### ISSUE TITLE
feat: install module should be able to stub

### ISSUE THREAD

**Issue by AndersDJohnson** [flow-typed/flow-typed#1506]
`flow-typed install module@x.x.x` should have an optional flag to automatically stub, just like `flow-typed install` for all modules does, e.g., `flow-typed install --stub module@x.x.x`.

Or perhaps even make this the default behavior, perhaps with a way to opt-out, e.g., a flag like `--no-stub`.

**Comment by GAntoine** [comment]
We have a command for that, `flow-typed create-stub module@x.x.x`. IMO there's no reason why we should use a flag, to basically delegate to another command.
