### ISSUE TITLE
Add AbortController and AbortSignal

### ISSUE THREAD

**Issue by Haroenv** [flow-typed/flow-typed#1652]
Documentation is visible here: https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController

I'd like to add it, but not too sure in which files

**Comment by Jahans3** [comment]
Bump. Is there any update on this?

**Comment by AndrewSouthpaw** [comment]
You can add it under the `browser` folder, which is for "libraries" that aren't in NPM.

**Comment by stereobooster** [comment]
```ts
// translation of https://dom.spec.whatwg.org/#abortcontroller
declare interface AbortSignal extends EventTarget {
  +aborted: boolean;
  onabort: EventHandler;
}
declare class AbortController {
  +signal: AbortSignal;
  abort: () => void;
}
```

**Comment by Brianzchen** [comment]
Exists in flow core libs under `bom.js`
