### ISSUE TITLE
Wrong information about default exports for modules in libdefs

### ISSUE THREAD

**Issue by koluch** [flow-typed/flow-typed#1662]
[Documentation](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-commonjs-module) says following:

> Note that you can also declare other things inside the body of the declare module, and those things will be scoped to the body of the declare module, **but they will not be exported from the module**:

But this is not true for types, declared in module scope: [all the types are exported and available for the import](https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md#prefix-global-variables-that-arent-really-meant-to-be-global). I think, this should be mentioned in documentation

**Comment by Eche36** [comment]
Yes it true

**Comment by jedwards1211** [comment]
@koluch I don't think that's correct, if I understand you correctly. I just double-checked with the following non-exported type in sequelize:

```js
  declare type AssociationType = 'HasMany' | 'BelongsTo' | 'HasOne' | 'BelongsToMany'
```

I tried this:
```js
import {type AssociationType} from 'sequelize'
```

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/universal/components/ApolloForm.js:11:15

Cannot import AssociationType because there is no AssociationType export in sequelize.
```

**Comment by jedwards1211** [comment]
Also the title of this is confusing because it has nothing to do with *default* exports right?
