### ISSUE TITLE
[LIBDEF] rethinkdbdash

### ISSUE THREAD

**Issue by ctrlplusb** [flow-typed/flow-typed#167]
I have been trying to create one for my own project.

If anyone else has started one, please do let me know. :)

**Comment by JohnyDays** [comment]
I did start some work on typing it, although it's still a bit crude, it works for common usage. 🍰 
https://gist.github.com/JohnyDays/26792b298b442353da00427f21609f4c

**Comment by ctrlplusb** [comment]
Brilliant, thanks for the share!  I'll look to merge this into mine.

**Comment by alexeygolev** [comment]
@ctrlplusb I started working on rethinkdb driver (not rethinkdbdash). Don't have it publicly though. How would I share it with you?

**Comment by ctrlplusb** [comment]
@alexeygolev, brilliant thanks, every bit of reference will help.
Feel free to email me - sean [at] ctrlplusb [dot] com
Thanks!

**Comment by alexeygolev** [comment]
@ctrlplusb have you received it (really sorry to use the issue but I'm not sure if the email went through)

**Comment by ctrlplusb** [comment]
@alexeygolev I've just checked, sorry, yes I have received it.  Thanks so much dude!

I have been finishing off another project - hoping to be rid of it within the next week, thereafter will be spending a considerable amount of time on this effort.  Complete up to us co-collaborating on this.

I'll ping you via email when I am getting ready to go. 

Sorry about not picking that up sooner!

**Comment by GAntoine** [comment]
Closing as the rethinkdbdash project looks to be dead.
