### ISSUE TITLE
validate-defs complains about .DS_Store files that osx generates all the time

### ISSUE THREAD

**Issue by Gozala** [flow-typed/flow-typed#1723]
Hi I wanted to contribute some lib definitions but as I'm trying to run `flow-typed validate-defs` I run into following error:

```
definitions/npm/.DS_Store:
  • Expected only directories to be present in this directory.

prosemirror-model_v1.x.x/.DS_Store:
  • Unexpected file name. This directory can only contain test files or a libdef file named `prosemirror-model_v1.x.x.js`.

pull-stream_v3.x.x/.DS_Store:
  • Unexpected file name. This directory can only contain test files or a libdef file named `pull-stream_v3.x.x.js`.
```

It's kind of annoying because osx generates those `.DS_Store` files in every directory you navigated with finder and it's kind of silly that `flow-typed` complains about it instead of just ignoring.

**Comment by GAntoine** [comment]
Agreed, I've come across it all the time. I'll pop it on the list of things to fix. In the meantine, run `find . -name '.DS_Store' -type f -delete` from the project root.
