### ISSUE TITLE
Can't get how to use flow-typed

### ISSUE THREAD

**Issue by SilencerWeb** [flow-typed/flow-typed#1743]
Why doesn't [this example](https://github.com/SilencerWeb/flow-typed-example) work? What do I do wrong?

Icon is wrapped in `styled()` and flow doesn't throw errors for it.
Icon2 isn't wrapped in `styled()` and flow does throw errors for it.

What I did:
1. installed flow-typed globally
2. installed packages via `flow-typed install`
3. add ./flow-typed to libs in .flowconfig

Example setup steps:
1. `git clone https://github.com/SilencerWeb/flow-typed-example.git`
2. `cd flow-typed-example`
3. `yarn install` (or `npm install`)
4. `yarn flow`

**Comment by GAntoine** [comment]
If it's an issue with using built-in definitions, provided by flow-core, you might have better luck asking for help on the official flow repo. My knowledge only extends as far as the cli and some third-party libdefs.

**Comment by SilencerWeb** [comment]
So, everything with setting up flow-typed is fine, right?

**Comment by GAntoine** [comment]
From the looks of it, should be. You've got the same setup I do on another project. Try using one of the library definitions found here, and see if errors appear when you make a mistake.
