### ISSUE TITLE
Add an "incomplete" libdef namespace for stale, unfinished libdef PRs

### ISSUE THREAD

**Issue by jeffmo** [flow-typed/flow-typed#178]
As @mirek pointed out over in #42, it's inevitable that we'll have some PRs submitted with an incomplete libdef (such that it doesn't fit the acceptance guidelines -- i.e. tests/too many `any`s/incorrect interfaces/etc) that the author doesn't have time to finish.

In these cases, its probably better to just merge these into a namespace that's excluded from the normal `npm` namespace so that someone might come along later and pick up where they've been left off (rather than starting from scratch).

Initially we can do this manually, but eventually we should build a bot to help manage this kind of SLA as well as doing the work of tweaking the PR and committing it properly.

**Comment by ryyppy** [comment]
How about a `$wip` namespace and `definitions/wip` directory, whereby user can define the `--wip` flag for the install command?

**Comment by ryyppy** [comment]
Okay I just realized you have been discussing this in a PR,... but not sure what the outcome is now?

**Comment by jeffmo** [comment]
Yea, `$wip` namespace would be a fine name too.

I created this issue just to track the idea independent of the Pull Request. I haven't started working on it or anything yet.

**Comment by mirek** [comment]
To avoid limbo (for both - wip namespace and libdefs like lodash) do you think it's reasonable to:

1. just create `./definitions/wip/...` directory with structure equivalent to `./definitions/npm/...` and
2. tell people to throw libdefs that need more attention there.

There's no really a need to add any support for now in the cli (really - there's no reason in the first step).

After this decision we'll flush couple of PRs that are hanging for months (lodash etc). This will move things a lot already.

Then as a second step we can add the `--wip` flag which just merges listing from that directory as if definitions were in npm, that should do the trick.

**Comment by ryyppy** [comment]
Hmmm... we will at least need the `--wip` flag for the `install` command.. otherwise it's unnecessarily complicated to look up the queried libdef...

After a second thought, I think a `$wip` could also make things more complicated (so `$npm` would just be fine)... 
I am in for your proposal to just start migrating longer pending PRs to the `definitions/wip` directory and merge them... maybe things would get along faster then?

**Comment by Brianzchen** [comment]
I think #4051 supersedes what this issue set out to accomplish

**Comment by GAntoine** [comment]
Agreed, we can close this.
