### ISSUE TITLE
Library definitions as ES or CommonJS?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flow-typed/flow-typed#1847]
When building a new library definition, should it be written in ES or CommonJS? They're [mutually exclusive](https://flow.org/en/docs/libdefs/creation/).

I see a mixture generally happening (even the actual library can mix), I'm not entirely clear that it matters, and I'd favor ES if that makes sense... thoughts?

**Comment by sibelius** [comment]
ES

**Comment by GAntoine** [comment]
Seconded for ES, since ES6 `import` and `export` are the actual standards. Though I won't twist anyone's arms for using `module.exports`!

**Comment by Brianzchen** [comment]
Depends how they're used. In a frontend context most people would just use import/export but when coding in node and without other parsers except for `babel/preset-flow` the standard would be `require/module.exports`.

What happens is that if everything is written with `declare export default` then when I require a var eg `const views = require('koa-views')` I can't use it as `views()` and flow tells me I should do `views.default()` which now flow thinks is all good but it would probably not work when you run it. 

So I don't think we need a rule/standard, you just create a module in the way that best suits the library, the author generally would have an expectation of the only way it can be used anyways.
