### ISSUE TITLE
Multiple test files

### ISSUE THREAD

**Issue by alexeygolev** [flow-typed/flow-typed#186]
As some libdefs are quite big (e.g. ramda) it would be very nice to be able to break tests into separate smaller files. As we already have a folder structure I wonder if we could add an optional `tests` folder to keep everything clean. Then the `test_...` file could just import all the tests

**Comment by marudor** [comment]
Already possible. See the Jasmine definitions.
https://github.com/flowtype/flow-typed/tree/master/definitions/npm/jasmine_v2.4.x

**Comment by alexeygolev** [comment]
@marudor thanks, it might become quite messy though... do we want to think about a cleaner solution?

**Comment by thejameskyle** [comment]
This seems like a clean enough solution

**Comment by jeffmo** [comment]
Having many test files next to each other doesn't bother me much, but I'm sympathetic to the messiness concern.

I'd be open to something like having the test runner also look for a `test/` directory (in the same places it looks for `test_*` files) and run those tests as if they were just `test_*` files.

I'll leave it to someone who feels strongly about this to write the PR :)

**Comment by GAntoine** [comment]
Closing as this is already possible, if a little messy.
