### ISSUE TITLE
lodash dissoc type

### ISSUE THREAD

**Issue by sam-rad** [flow-typed/flow-typed#1862]
I couldn't find `libdef` for lodash on their repo so apologies in advance if this is irrelevant here. I think the return type of `_.dissoc` should be an `object` rather than `boolean`.

See [lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js][1]

`dissoc` is an [alias][2] for `unset` but it doesn't mutate the object and rather it returns a new one. 

```js
// I think this is wrong
dissoc(path: Array<string> | string): (object: Object) => boolean;

// This might be more accurate
dissoc(path: Array<string> | string): (object: Object) => Object;
```

[1]: https://github.com/flowtype/flow-typed/blob/0289401daee889dfee9232c21512462b689f7395/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js#L2984

[2]: https://github.com/lodash/lodash/wiki/FP-Guide#aliases

**Comment by Mr-Wallet** [comment]
Don't forget `dissocPath`, which is another alias.

Basically when FP definitions were added, the fact that this one returns a different type than vanilla lodash was overlooked.
