### ISSUE TITLE
Ramda `pipe` function shows error when given more than 1 argument

### ISSUE THREAD

**Issue by functionalStoic** [flow-typed/flow-typed#1899]
@LoganBarnett @AndrewSouthpaw 

Today, I created a function with `pipe` and received an error due to passing more than 1 argument. 

The Ramda docs say 

> The leftmost function may have any arity

Even the example in the docs uses `Math.pow` which takes 2 arguments.

```
var f = R.pipe(Math.pow, R.negate, R.inc);

f(3, 4); // -(3^4) + 1
```

However, As far as I can tell the type definition for Pipe uses `UnaryFn` to annotate the arguments to `pipe`. 

Snippet from the type definition:

```
declare type Pipe = (<A, B, C, D, E, F, G>(
    ab: UnaryFn<A, B>,
    bc: UnaryFn<B, C>,
    cd: UnaryFn<C, D>,
    de: UnaryFn<D, E>,
    ef: UnaryFn<E, F>,
    fg: UnaryFn<F, G>,
    ...rest: Array<void>
  ) => UnaryFn<A, G>) &
    (<A, B, C, D, E, F>(
      ab: UnaryFn<A, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      de: UnaryFn<D, E>,
      ef: UnaryFn<E, F>,
      ...rest: Array<void>
    ) => UnaryFn<A, F>) &
    (<A, B, C, D, E>(
      ab: UnaryFn<A, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      de: UnaryFn<D, E>,
      ...rest: Array<void>
    ) => UnaryFn<A, E>) &
    (<A, B, C, D>(
      ab: UnaryFn<A, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      ...rest: Array<void>
    ) => UnaryFn<A, D>) &
    (<A, B, C>(
      ab: UnaryFn<A, B>,
      bc: UnaryFn<B, C>,
      ...rest: Array<void>
    ) => UnaryFn<A, C>) &
    (<A, B>(ab: UnaryFn<A, B>, ...rest: Array<void>) => UnaryFn<A, B>);
```

It appears that the first argument should be a function that can accept any arity. I'm not quite sure which predefined type that is but with some confirmation I can make a PR if necessary.

Thanks!

**Comment by AndrewSouthpaw** [comment]
That does seem to be an issue, and looking at the libdef I don't think we have an `NNaryFn`. I also think it might be hard to do, but you're welcome to give it a shot.

**Comment by functionalStoic** [comment]
@AndrewSouthpaw Well I may be completely out of my league in regards to Flow with this but let me know what you think about this.

Based on the Typescript-Ramda type def for `pipe` located [here](https://github.com/tycho01/typescript-ramda/blob/dacb14793a4d5249091fea27146cc13d2315362f/ramda.d.ts#L1545) it appears to have acceptance of binary function as the first parameter.

So I made changes to my local def along with working through and seeing errors while I made changes the Flow.org REPL? and it passes with no errors. I also no longer receive a flow error in the code that prompted me to look into this. 

[Link to Flow REPL](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQVQHa2QMSwB4BBAGngCUA+eAXngAooAueYgSjpooG4AoUJFgIU6eACEAljhj4iZCeWp1GTVgoBGrcZ1rdOAMj7wTqlm100GWiZcrt+A8NDhI0CAAqSx9BiQAM5MQAjOTi5ADC5AAi5ACi5HjkAOJUDMamUDZSMnIBQaESVKQZJhpgrNi4BITh8BHFpfBgwJW5NVHw0Y2m8KBt1USx8HE9piAAZgOyNQnweGMmEwDm03lJ8KklvQB0e3AAzojqMDBQyIQAbgD2ksBUGXY5g-lshamGTU1+xIFvYZEYvFEmkmiYstppC9fgUwotTOU1jU6g1tr1mq14FUZkROt00b1+lj2kN4vCTJMkUQ5gsCaY9jtDsc2Kdzldbvcmk8oTjXiEQZ9et8+YUUUCRqD0fAIRIeXkYf8inSyhViS8UeSMVTCHjNUTsXlhqNlfAGUyTmcLjc7g9etySSKyYLTMKFfzFPUYpL0TLnry3aLNYi1byNSaWtrdSazSAjha2dbOXauLKHQGvc6TK6-u6Nekpb65TV00qwfBgwbkZFNTG4yzLeybVyU375TnCg1M-Bs7CikxskX5O24eRa8ziKyrRyqPbocOig4gA)

Thoughts?
```
declare type UnaryFn<A, R> = (a: A) => R;
declare type BinaryFn<A, B, R> = ((a: A, b: B) => R) &
    ((a: A) => (b: B) => R);

declare type Pipe = (<A0, A1, B, C, D, E, F, G>(
    ab: BinaryFn<A0, A1, B>,
    bc: UnaryFn<B, C>,
    cd: UnaryFn<C, D>,
    de: UnaryFn<D, E>,
    ef: UnaryFn<E, F>,
    fg: UnaryFn<F, G>,
    ...rest: Array<void>
  ) => BinaryFn<A0, A1, G>) &
    
    (<A0, A1, B, C, D, E, F>(
      ab: BinaryFn<A0, A1, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      de: UnaryFn<D, E>,
      ef: UnaryFn<E, F>,
      ...rest: Array<void>
    ) => BinaryFn<A0, A1, F>) &
    
    (<A0, A1, B, C, D, E>(
      ab: BinaryFn<A0, A1, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      de: UnaryFn<D, E>,
      ...rest: Array<void>
    ) => BinaryFn<A0, A1, E>) &
    
    (<A0, A1, B, C, D>(
      ab: BinaryFn<A0, A1, B>,
      bc: UnaryFn<B, C>,
      cd: UnaryFn<C, D>,
      ...rest: Array<void>
    ) => BinaryFn<A0, A1, D>) &
    
    (<A0, A1, B, C>(
      ab: BinaryFn<A0, A1, B>,
      bc: UnaryFn<B, C>,
      ...rest: Array<void>
    ) => BinaryFn<A0, A1, C>) &
    
    (<A0, A1, B>(ab: BinaryFn<A0, A1, B>, ...rest: Array<void>) => BinaryFn<A0, A1, B>);
```

**Comment by LoganBarnett** [comment]
I wonder if we can use `$Compose` or `$ComposeReverse` here. This is the closest thing I could find for [documentation](https://github.com/facebook/flow/commit/ab9bf44c725efd2ed6d7e1e957c5566b6eb6f688) in a short period of time. I thought there was a blog post or something about it, but my google fu has proven weak here.

**Comment by AndrewSouthpaw** [comment]
Using that REPL link, I'm getting errors. Repro'ed [here](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQVQHa2QMSwB4BBAGngCUA+eAXngAooAueYgSjpooG4AoUJFgIU6eACEAljhj4iZCeWp1GTVgoBGrcZ1rdOAMj7wTqlm100GWiZcrt+A8NDhI0CAAqSx9BiQAM5MQAjOTi5ADC5AAi5ACi5HjkAOJUDMamUDZSMnIBQaESVKQZJhpgrNi4BITh8BHFpfBgwJW5NVHw0Y2m8KBt1USx8HE9piAAZgOyNQnweGMmEwDm03lJ8KklvQB0e3AAzojqMDBQyIQAbgD2ksBUGXY5g-lshamGTU1+xIFvYZEYvFEmkmiYstppC9fgUwotTOU1jU6g1tr1mq14FUZkROt00b1+lj2kN4vCTJMkUQ5gsCaY9jtDsc2Kdzldbvcmk8oTjXiEQZ9et8+YUUUCRqD0fAIRIeXkYf8inSyhViS8UeSMVTCHjNUTsXlhqNlfAGUyTmcLjc7g9etySSKyYLTMKFfzFPUYpL0TLnry3aLNYi1byNSaWtrdSazSAjha2dbOXauLKHQGvc6TK6-u6Nekpb65TV00qwfBgwbkZFNTG4yzLeybVyU375TnCg1M-Bs7CikxskX5O24eRa8ziKyrRyqPbocOig4vmBrlgjtLgMAVExyBo7FB4ABqctOISuS6weCobwgVhedBfAD0D-gAHdrjAANYHPhX9BMDfsAwwTsI+z7ANcsbwFg1yIK+74fgA-D+17-sAgGFAATOwQA), thoughts?

**Comment by retyui** [comment]
@AndrewSouthpaw
You can close this issue
Fixed in: https://github.com/flow-typed/flow-typed/pull/2958

**Comment by AndrewSouthpaw** [comment]
Looks right, thanks. @functionalStoic feel free to weigh in if you believe it is not addressed.
