### ISSUE TITLE
Possible to require package author review for libdef updates?

### ISSUE THREAD

**Issue by Ashoat** [flow-typed/flow-typed#1915]
In `react-navigation` we have a CI that tests our libdef against an example project. We ask that users submit their libdef changes first to our repo, so we can make sure they don't break our example project. We then send PRs to `flow-typed` once the changes have been committed to our repo.

This adds a layer of testing beyond the tests in this repo and helps protect against breaking libdef changes.

However, individual package users have been sending PRs on our libdef in this repo, causing the libdef versions to get out-of-sync. Is it possible to restrict `flow-typed` PRs for a specific package to package authors, or alternately to require their reviews for any PRs on their packages?

**Comment by AndrewSouthpaw** [comment]
@GAntoine 

Not that I know of. Best bet (as I mentioned in [another comment](https://github.com/flowtype/flow-typed/commit/6475dcc6d17d87bf2bebb027320cdc404dfb39d3#commitcomment-27938516)) would be to make a `CONTRIBUTING.md` file in the appropriate folder, and mention any people that should review the PR.

That doesn't ensure they will actually request those reviewers, but in this case if other assignees were explicitly called out I'd wait for their signoff, and we could probably set that as a standard within the repo.

That's my $0.02.

**Comment by AndrewSouthpaw** [comment]
Also, I'm wondering about keeping two separate libdefs, that seems unnecessary. If your library is already typed, can clients not just use that libdef, much like how react or react-forms work?

**Comment by GAntoine** [comment]
Ideally we'd have the idea of "Definition Owners", people who's get a stronger say over the contents of a definitions (be it the library's owner or an active contributor), and a bot to ping/request reviews and approval from one of those users. A `CONTRIBUTING` file could be used to update the maintain that list.

It's too easy right now for someone to make a change, and for me to come along, look at it and say "yeah that probably makes sense" and merge it in. 😅

**Comment by Ashoat** [comment]
I looked into whether GitHub has a feature to subscribe to any PRs on a folder, but it doesn't appear to exist. It would of course be possible for somebody to implement this as a third-party service.

There is a [feature](https://help.github.com/articles/about-codeowners/) on GitHub where if you specify a `CODEOWNERS` file in the repo root you can automatically add reviewers, but unfortunately it requires any such reviewer to have write permission on the repo.

> Also, I'm wondering about keeping two separate libdefs, that seems unnecessary. If your library is already typed, can clients not just use that libdef, much like how react or react-forms work?

The main reason we switched away from hosting types in-package was that we want to support multiple versions of React Native at the same time. This is possible to achieve with `flow-typed` since each `react-native` version is paired with a `flow-bin` version, and `flow-typed` allows you to set distinct libdefs depending on `flow-bin` version.

**Comment by Brianzchen** [comment]
We should look into a gitbot eventually that looks so files changes and tags appropriately though I don't have experience in that realm. @GAntoine we could leverage the package.json from a flow version for this situation

**Comment by Brianzchen** [comment]
This is almost a reality stay tuned! Just waiting on some webhook setups but here's the test PR to showcase

https://github.com/flow-typed/flow-typed/pull/4388#issuecomment-1275273086

**Comment by Brianzchen** [comment]
https://github.com/flow-typed/flow-typed/blob/main/CONTRIBUTING.md#owning-definitions
Implemented, works for any branch target as long as the `CODEOWNERS` sits in `main` branch
