### ISSUE TITLE
lodash.difference should accept any number of arguments

### ISSUE THREAD

**Issue by capaj** [flow-typed/flow-typed#1968]
now it is showing this error:
```
Cannot call `_.difference` because no more than 2 arguments are expected by function type [1]. (References: [1])
```

when I call `_.difference()` with more than two arguments

**Comment by Brianzchen** [comment]
Should be fixed now and is tested [here](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.155.x-/test_lodash-v4.x.x.js#L139)
