### ISSUE TITLE
Include stubs for package directories that contain an `index` file

### ISSUE THREAD

**Issue by mhelvens** [flow-typed/flow-typed#1994]
We use an internal library package that has paths like `/dir1/dir2/index.js`, and then import them like `import stuff from '@some/package/dir1/dir2'`. flow-typed helpfully creates stubs of all _files_ inside the package, but forgets to make stubs for those directories, resulting in "Required module not found" errors.

**Comment by SillyFreak** [comment]
seems to have been fixed with #3426. Close?
