### ISSUE TITLE
`yarn global add flow-typed` does not work

### ISSUE THREAD

**Issue by bifunctor** [flow-typed/flow-typed#1996]
Hi all   
Install flow-typed with the statement `yarn global add flow-typed` it won't work.
But with `npm i -g flow-typed` it works.  
Thanks

**Comment by GAntoine** [comment]
Could you paste the output logs when running the command? I tried it locally and it installed just fine.

**Comment by thymikee** [comment]
Cannot repro (tried on Node 8.9 and 9.6)

**Comment by sibelius** [comment]
I think this happens when u first install using npm and then try yarn

**Comment by pascalduez** [comment]
Cannot repo

```
node -v v11.9.0
npm -v 6.7.0
yarn -v 1.13.0
````

Closing for now, yell at us if the issue still exist, with precise data about versions, logs etc.

**Comment by radinreth** [comment]
you may need to `export PATH="$PATH:$(yarn global bin)"` to `~/bash_profile`
then
`source ~/.bash_profile`

https://stackoverflow.com/questions/40317578/yarn-global-command-not-working
