### ISSUE TITLE
[chrome] Adding chrome API

### ISSUE THREAD

**Issue by karelbilek** [flow-typed/flow-typed#201]
Hello,

I would like to add "chrome API" - that is, all the various functions that are available for chrome packaged apps/extensions. Stuff from here - https://developer.chrome.com/extensions/api_index

I don't know if it's better to add that here somewhere (where? it's not a npm package), or to "main" flow into the built-in definitions.

I have a definition file with stuff that I am using here

https://github.com/trezor/trezor-chrome-extension/blob/master/flowtype_definitions/chrome.js

it doesn't cover full API by _far_, but it's something I want to share anyway

**Comment by runn1ng** [comment]
....on the other hand, node definitions are already in flow/lib even when node is not part of "core" javascript, so it's probably better to put it there. Not sure (that's why I am asking :))

**Comment by SyncroIT** [comment]
If I have some time this evening I will integrate it and PR.  
You want to integrate a FlowType for the Chrome API, right?

**Comment by runn1ng** [comment]
yep. I now made a PR here

https://github.com/facebook/flow/pull/2094

**Comment by SyncroIT** [comment]
Mmm okay!
Do you wanna that I made a PR here or you're already doing it?

**Comment by runn1ng** [comment]
You can do it, I am not sure where to put it here

**Comment by sammkj** [comment]
Is there any progress on this? I'm currently working on a chrome extension and have written some of the API definitions. I would like contribute to this.

**Comment by runn1ng** [comment]
I have no idea. If you want to, you can use my definitions.

**Comment by sammkj** [comment]
Ok, it looks like your definitions contain mostly for Chrome apps. One question though, how should I write tests for this?

**Comment by runn1ng** [comment]
yep, I needed that for Chrome apps. It seems like Chrome will cancel chrome apps sooner than this will be merged anywhere :)

**Comment by ssorallen** [comment]
I've been using [flow-interfaces-chrome](https://github.com/Shraymonks/flow-interfaces-chrome/) for this use case, and the installation is done by adding a line to `[libs]` in .flowconfig. Until there's a longer term solution for non-NPM libraries, this approach seems reasonable.

**Comment by runn1ng** [comment]
I wrote what I needed for my app, not more. Again feel free to use it in
your projects; but I won't be updating it now (especially when Google wants
to kill chrome apps :( )
