### ISSUE TITLE
Can't import module types in Flow library definitions

### ISSUE THREAD

**Issue by migueloller** [flow-typed/flow-typed#2023]
Does Flow support type imports inside libdefs?

Since Apollo's graphql-tools doesn't provide flow types I'm providing my own.

```js
// flow-typed/graphql-tools.js

/* @flow */

import type { GraphQLSchema } from 'graphql'

declare module 'graphql-tools' {
  declare export var makeExecutableSchema: ({|
    typeDefs: string,
    resolvers: { [typeName: string]: { [fieldName: string]: () => mixed } },
  |}) => GraphQLSchema
}

```

Given that `graphql` is a peer dependency of `graphql-tools` I'm importing `GraphQLSchema` from `graphql`.

The issue is that when calling `makeExecutableSchema` the return type is always `any`.

```js
/* @flow */

// `typeof makeExecutableSchema` is `({|resolvers: {[typeName: string]: {[fieldName: string]: () => mixed}}, typeDefs: string|}) => GraphQLSchema`
import { makeExecutableSchema } from 'graphql-tools'

// `typeof schema` is `any`
const schema = makeExecutableSchema({ typeDefs, resolvers })
```

If instead of `GraphQLSchema` I use a builtin type, like `number`, there's no issue.

Is it not possible to import types from other modules when declaring a libdef?

**Comment by sibelius** [comment]
I think u can import types inside declare module

**Comment by saadq** [comment]
Unfortunately, it isn't currently possible (more disccusion on this in #1857). It only works if you use `import type` or `import typeof` inside the `declare module`, but you can only import types that are already builtin to Flow, you won't be able to import stuff from other libdefs.

**Comment by sibelius** [comment]
@calebmer is this right? is there any plans to support this?

**Comment by migueloller** [comment]
@sibelius, it results in an error as Flow doesn't recognize with a `Cannot resolve module graphql.`.

@saadq, that's sad to hear. I guess I'll have to explicitly do:

```js
const schema: GraphQLSchema = makeExecutableSchema({ typeDefs, resolvers })
```

**Comment by migueloller** [comment]
Here's my compromise for now:

```js
/* @flow */

declare module 'graphql-tools' {
  // $FlowFixMe: Flow currently doesn't support type dependencies between libraries. See https://github.com/flowtype/flow-typed/issues/1857.
  import type { GraphQLSchema } from 'graphql'

  declare export var makeExecutableSchema: ({|
    typeDefs: string,
    resolvers: { [typeName: string]: { [fieldName: string]: () => mixed } },
  |}) => GraphQLSchema
}
```

```js
/* @flow */

import { makeExecutableSchema } from 'graphql-tools'
import type { GraphQLSchema } from 'graphql'

const schema: GraphQLSchema = makeExecutableSchema({ typeDefs, resolvers })
```

`makeExecutableSchema` still returns `any` but it's refined by `GraphQLSchema` from `graphql`.

**Comment by saadq** [comment]
So just to clarify – Flow itself does support importing types from different libraries, but `flow-typed` doesn't currently have support for doing it.

**Comment by migueloller** [comment]
@saadq, I don't think Flow allows it. Let me try moving the file to a `libdefs` folder and adding that to the `.flowconfig`.

**Comment by migueloller** [comment]
@saadq, it does seem to be an issue with all Flow library definitions.

**Comment by saadq** [comment]
@migueloller It should work outside of `flow-typed`. Here's an example:

![screen shot 2018-04-02 at 3 06 08 pm](https://user-images.githubusercontent.com/5678694/38211114-701bb832-3687-11e8-96c9-42e072a47ae7.png)

As you can see, I only have the `Koa` libdef installed from `flow-typed`. I declared my own `koa-router` module which imports the `Middleware` type from `koa`, and the type is recognized.

**Comment by migueloller** [comment]
@saadq, keep in mind that there's no libdef for `graphql`. The Flow typed ship with the package itself.

**Comment by saadq** [comment]
> keep in mind that there's no libdef for graphql. The Flow types ship with the package itself.

I hadn't tried it with modules that have the types packaged in, but I think you're right that it wont work in this case :/

> The example you just gave also works inside flow-typed only because you have the koa_v2.x.x.js typedef.

The example I have above wouldn't actually work in `flow-typed`, it would complain that it can't find the `koa` module. It does work outside of it though.

**Comment by migueloller** [comment]
> The example I have above wouldn't actually work in flow-typed, it would complain that it can't find the koa module. It does work outside of it though.

Interesting, it did work for me. Is there any reason why Flow would treat the `flow-typed` folder differently? I thought that it simply included `flow-typed` in `[libs]` by default. Didn't think there was special behavior for it.

**Comment by saadq** [comment]
Sorry I think we're talking about two different things – when I say it wouldn't work in `flow-typed`, I meant that you wouldn't be able to submit a libdef to the `flow-typed` definitions repo that tried to import types from dependencies. Something like this:

```
declare module 'koa-router' {
  import type { Middleware } from 'koa';

  declare export var middleware: Middleware;
}
```

wouldn't be able to be submitted to this repo because dependencies aren't handled correctly right now. 

I think you were just talking about using the `flow-typed` folder locally in which case your assessment on it is correct.

**Comment by migueloller** [comment]
@saadq, ah yes, that is correct!

Question. If the library is a peer dependency, shouldn't `flow-typed` not care that it's being imported? What is the reason that `flow-typed` doesn't support that at the moment?

**Comment by Brianzchen** [comment]
This is now possible with PR's targeting `main` branch. v4 CLI coming soon but test framework setup and ready to go https://github.com/flow-typed/flow-typed/blob/main/CONTRIBUTING.md#importing-types-from-other-libdefs
