### ISSUE TITLE
Styled-components default export is unknown type

### ISSUE THREAD

**Issue by zalishchuk** [flow-typed/flow-typed#2144]
Why default export of the `styled-components` package is unknown. 

Example code:
```jsx
// @flow

import * as React from 'react';
import styled from 'styled-components';

const A = styled.a`
  color: red;
`;

const B: React.ComponentType<{ children: React.Node }> = ({ children }) => (
  <a>{children}</a>
);

const C = styled(B)`
  color: blue;
`;
```

`styled` is typed as `unknown`, maybe this is because of weird `$call` property in `module.exports`. This refers to https://github.com/facebook/flow/issues/2966.

https://github.com/flowtype/flow-typed/blob/master/definitions/npm/styled-components_v3.x.x/flow_v0.57.x-/styled-components_v3.x.x.js#L347

**Comment by AndrewSouthpaw** [comment]
Feel free to look at previous contributors to this libdef and cc them here. :)

**Comment by zalishchuk** [comment]
Any updates on that? @breadadams @dashed

**Comment by breadadams** [comment]
Hi @zalishchuk, sorry, I'm a _recent_ contributor and am not too up to date with what's going on in this situation.

However I've spotted what you mention too (I think), in all projects where we use `flow` & `styled-components` we get _"uncovered code"_ highlights for the styled-component's template literal contents. So _something's_ not right with the type defs, but I'm probably not the adequate candidate to fix it 😅 

Also, I noticed in your example the contents of `B` should be `<A>…</A>` (you've got lowercase `<a>`'s).

**Comment by dashed** [comment]
@zalishchuk seems there an update to the definitions recently: https://github.com/flowtype/flow-typed/pull/2190 

can you verify?

**Comment by zalishchuk** [comment]
@dashed just checked latest `styled-components` libdefs and still there is weird `$call` property in `export default`, which is not working for me. 

![image](https://user-images.githubusercontent.com/2690794/40548741-3fcc854a-603e-11e8-9b15-486862175de6.png)

`styled-components` default export is still `(unknown)` type.

**Comment by dashed** [comment]
@zalishchuk Is this a type error from running `flow` on your project? Or is this coming from your editor?

**Comment by zalishchuk** [comment]
@dashed It's not a type error, it's a coverage warning. My editor is using flow to get file flow coverage.

```sh
flow coverage src/index.js
Covered: 85.71% (12 of 14 expressions)

flow type-at-pos src/index.js 4 10
(unknown)
/Users/zalishchuk/Desktop/projects/styled-components/src/index.js:4:8,4:13
```
```js
import styled from 'styled-components';
/* ------^ 4 10 position */
```

**Comment by shrynx** [comment]
@zalishchuk can you check and report the version of both flow and styled-components.
Also maybe try killing flow (`killall flow`), just to remove flow cache.

**Comment by zalishchuk** [comment]
@shrynx tried to `killall flow`, restarting flow server, nothing changed.

```json
{
  "flow-bin": "^0.73.0",
  "styled-components": "^3.3.0"
}
```

**Comment by shrynx** [comment]
@zalishchuk 
Sorry for all the trouble.
So i have targeted the bug, for but not sure why is it being caused. I need a little time to get through it , although i do have a hot fix.
Meanwhile if you really need the hot fix. i'll add a gist that you can copy paste in your local.

**Comment by Gpx** [comment]
I think I hit the same issue when updating Flow to `0.75.0`. I now get:

```
Cannot call styled because a callable signature is missing in object type [1].

    flow-typed/npm/styled-components_v3.x.x.js
[1] 494│   declare export default {
     495│     $call: $npm$styledComponents$Call<ComponentListKeys>,
     496│     styled: $npm$styledComponents$Call<ComponentListKeys>,
     497│     css: TaggedTemplateLiteral<Array<Interpolation>>,
     498│     ...$npm$styledComponents$StyledComponentsComponentList,
     499│     ...$npm$styledComponents$StyledComponentsNativeComponentList,
     500│   }
```

@shrynx can you please share the hotfix so I can test it?

**Comment by wilomgfx** [comment]
@gpx like he said, it's really annoying. Wheres the fix?

**Comment by wilomgfx** [comment]
Switched to typescript, typescript support is much better for styled-components.

**Comment by andrewbloom37** [comment]
@shrynx Can you share the fix?

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
