### ISSUE TITLE
Flow types for takeLeading 

### ISSUE THREAD

**Issue by NotTooReact89** [flow-typed/flow-typed#2195]
Hi there,

Can you please let me know when would takeLeading from redux-saga be included in flow-typed? I am looking to use it.

**Comment by AndrewSouthpaw** [comment]
It'll likely be included when you write a PR for it. 😉

**Comment by AndrewSouthpaw** [comment]
You can fork the repo and create a PR from there.

**Comment by AndrewSouthpaw** [comment]
x

**Comment by stropho** [comment]
PR: https://github.com/flowtype/flow-typed/pull/2451
