### ISSUE TITLE
material-ui definitions are incorrect

### ISSUE THREAD

**Issue by psamim** [flow-typed/flow-typed#2240]
Hi,

Material-ui is updated to version 1.0.0 and all of [its import paths have changed](https://github.com/mui-org/material-ui/pull/11330). The [current definitions](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/%40material-ui/core_v1.x.x/flow_v0.58.x-/core_v1.x.x.js) are incorrect.

Thanks

**Comment by Brianzchen** [comment]
PR merged https://github.com/flow-typed/flow-typed/pull/2255
