### ISSUE TITLE
RXJS 6 Missing named imports to `rxjs`

### ISSUE THREAD

**Issue by behind-design** [flow-typed/flow-typed#2285]
It seems that there are some named imports that are missing from the namespace `rxjs`, mainly:

- `of`
- `from`
- `pipe`
- `empty`

And maybe some more (the creation methods), but those are the ones I caught.
The definitions for `rxjs@6` only take into account this creation methods under the following path or namespace: `rxjs/observable/{observableCreator -> of, from, ...}`

Any help would be welcome! 👍 

Thanks!

**Comment by AndrewSouthpaw** [comment]
Feel free to CC people here who have worked on that part of the repo before, they can probably provide input.

**Comment by behind-design** [comment]
@radex @GAntoine could you take a look?

**Comment by radex** [comment]
Yes, known issue :) I encourage you to contribute the missing pieces yourself. Most of what's missing in rxjs 6 typedefs is straightforward to fix/add
