### ISSUE TITLE
lodash: Incorrect type annotation for get

### ISSUE THREAD

**Issue by evankroske** [flow-typed/flow-typed#2335]
In the [libdef for lodash](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.63.x-/lodash_v4.x.x.js#L1130), get only accepts paths that are strings or arrays of strings. However, the implementation of get seems to accept anything:
- https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L4475
- https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L3048
- https://github.com/lodash/lodash/blob/4.17.10/lodash.js#L13125

**Comment by sibelius** [comment]
get is returning `any` as well

it should have the same behavior of `idx` I guess

**Comment by jedwards1211** [comment]
Ah this is fixed by #2444
Though that only adds support for numbers.  I would argue that accepting `$ReadOnlyArray<any>` in the typedefs sacrifices too much benefit of type checking -- I think it's wiser to let people manually convert to string in those cases.

**Comment by evankroske** [comment]
Thanks! The ability to use numbers addresses my use-case.
