### ISSUE TITLE
Is importing flow-type types really optional?

### ISSUE THREAD

**Issue by benknight** [flow-typed/flow-typed#2346]
I'm a bit surprised that the following code doesn't produce any errors

in src/lib/custom-types.js:

```js
type MyCustomType = {
  // ...
}
```

in .flowconfig:

```
[libs]
./src/lib/custom-types.js
```

in some-function.js:
```js
// @flow
function blah(arg: MyCustomType) {
  // ...
}
```

Should there be an error because MyCustomType wasn't imported in some-function.js?  Does using libs really make all type definitions global?  That doesn't seem right...

i.e. shouldn't I have to include this in some-function.js:

```
import type { MyCustomType } from './lib/custom-types.js';
```

**Comment by AndrewSouthpaw** [comment]
That *should* produce an error... provide a repro repo?

**Comment by Brianzchen** [comment]
This isn't really related to flow-typed at all. Also no further discussions occurred
