### ISSUE TITLE
RxJS v6 pipe with arity > 5

### ISSUE THREAD

**Issue by hally9k** [flow-typed/flow-typed#2356]
Disclaimer: I'm very new to Flow.

I to create a PR for this myself but couldn't seem to add an extra typing for `pipe` with an arity of 6.

After line 83 I added:

```
pipe<A, B, C, D, E, F>(
    op1: rxjs$OperatorFunction<T, A>,
    op2: rxjs$OperatorFunction<A, B>,
    op3: rxjs$OperatorFunction<B, C>,
    op4: rxjs$OperatorFunction<C, D>,
    op5: rxjs$OperatorFunction<D, E>,
    op6: rxjs$OperatorFunctionLast<E, F>
  ): F;
```

But this didn't seem to get picked up by the flow server at all... 🤔 

Does anyone want to help guide me to make a PR for this?

**Comment by AndrewSouthpaw** [comment]
Usually that means some earlier type definition for pipe is catching it. I'd start by looking at other `pipe` definitions above it and see if one would match.

You can also @ people who have worked on that part of the libdef (just git blame or whatever) to get their input. 😄
