### ISSUE TITLE
update flow definitions for Rxjs version 6.2.0 

### ISSUE THREAD

**Issue by sharanrprasad** [flow-typed/flow-typed#2384]
The current flow definitions are outdated and gives error If the new package syntax as mentioned in " https://rxjs-dev.firebaseapp.com/guide/v6/migration " is followed.

**Comment by radex** [comment]
@sharanrprasad I encourage you to just push a pull request with a fix and I can give it a look ;)

**Comment by sharanrprasad** [comment]
@radex 
The issue here is importing rxjs creation methods directly from rxjs module as specified in " https://rxjs-dev.firebaseapp.com/guide/v6/migration#howto-result-selector-migration " will throw a error.

This is the documentation in the website - 

<img width="890" alt="screen shot 2018-06-26 at 11 46 04 am" src="https://user-images.githubusercontent.com/35243820/41881260-ae4114bc-7936-11e8-9df5-d3836c879678.png">

The above shown code will throw a flow type error because pipe, of ,fromEvent are not defined in the rxjs flow module.

I will try to fix this and make a pull request.

**Comment by mastertinner** [comment]
I think this has been resolved in the meantime by https://github.com/flowtype/flow-typed/commit/71a8210c077c1ca00b4c5bc751c2eccb8913c7fd, no?
