### ISSUE TITLE
Flow 0.75.0 reports 'Deprecated $call syntax' error with Axios

### ISSUE THREAD

**Issue by benjreinhart** [flow-typed/flow-typed#2405]
Hey there! I'm getting the following error regarding the `$call` (lowercase c) syntax. I'm not familiar with this syntax and there's nothing in the flow docs about this. The only mention of it I could find was an old [github issue](https://github.com/facebook/flow/issues/3781#issuecomment-299068112) in the flow repo and it wasn't helpful.

This started happening when I upgraded flow from 0.74.0 to 0.75.0.

* flow: 0.75.0
* yarn: 1.7.0
* typed/npm/axios_v0.18.x.js

```
> yarn flow
yarn run v1.7.0
$ ./node_modules/.bin/flow status
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/axios_v0.18.x.js:102:5

Deprecated $call syntax. Use callable property syntax instead. (deprecated-call-syntax)

      99│   declare type AxiosPromise<T,R = T> = Promise<AxiosXHR<T,R>>;
     100│   declare class Axios {
     101│     constructor<T,R>(config?: AxiosXHRConfigBase<T,R>): void;
     102│     $call: <T,R>(
     103│       config: AxiosXHRConfig<T,R> | string,
     104│       config?: AxiosXHRConfig<T,R>
     105│     ) => AxiosPromise<T,R>;
```

**Comment by eqyiel** [comment]
@madole you can read a bit more about it here: https://github.com/facebook/flow/releases/tag/v0.75.0

AFAICT, `s/$call/[[call]]/g`, but it seems like that doesn't work.

**Comment by madole** [comment]
I did try that as well without any luck. Ended up hacking the type, not even sure it's doing the same thing now :(

**Comment by ryota-murakami** [comment]
thanks all!

i'm facing too this error and also even for packages other than axios.
so is there a way(i guess .flowconfig setting) to suppress `deprecated-call-syntax` Error?

it is useful until reflect fix to type definition file.

**Comment by dashed** [comment]
Looking at the tests: https://github.com/facebook/flow/blob/40a72f81e2f29e5a86a62738be036a852931a456/tests/call_properties/internal_slot.js

`$call: () => void` would be changed to `[[call]](): void`.

**Comment by jeremejevs** [comment]
Hmm, naive `$call` -> `[[call]]` worked fine for me, at least on Axios and Express.

**Comment by dashed** [comment]
@jeremejevs yea I kinda realized this. I had to do something weird like this to make flow happy:

```js
  declare export default {
    css: TaggedTemplateLiteral<Array<Interpolation>>,
    ...$npm$styledComponents$StyledComponentsComponentList,
    ...$npm$styledComponents$StyledComponentsNativeComponentList,
  } & {
    [[call]]: $npm$styledComponents$Call<ComponentListKeys>
  }
```

**Comment by ryota-murakami** [comment]
@dashed thank you so much for your mention!
i was not taking care about flow change log & implementation, but looks interesting.
i'm one of flow fan people, i've just motivated learn & activity about enhance for developer experience😀

**Comment by dhui** [comment]
Looks like this was fixed by https://github.com/flow-typed/flow-typed/pull/2456

**Comment by AndrewSouthpaw** [comment]
Sweet, closing.
