### ISSUE TITLE
[react-redux] connect() does not support exact types

### ISSUE THREAD

**Issue by 0x24a537r9** [flow-typed/flow-typed#2447]
Unfortunately, due to the `&`s used to combine props types in the definitions, the `react-redux` Flow module doesn't allow for [exact props types](https://flow.org/en/docs/types/objects/#toc-exact-object-types) on the wrapped component (because the intersection of different exact types yields `Empty`, since it's not possible).

For example:

```
type StoreState = {|
  b: number,
|};
type ReduxMappedProps = {|
  a: number,
|};
type Props = {|
  ...ReduxMappedProps,
  b: number,
|};

const MyComponent = (props: Props): React.Node => {
  return null;
};

const MyConnectedComponent =
  connect((storeState: StoreState): ReduxMappedProps => ({b: storeState.b}))(MyComponent);
```

This will fail with `<MyConnectedComponent a={1} />`, with Flow complaining about the props missing `b` (because it expects the `Empty` Flow internal type for the props).

Any fix probably requires identifying when the props expected by the component are exact and spreading in new ones using `...`.

**Comment by AndrewSouthpaw** [comment]
cc @villesau

**Comment by villesau** [comment]
@0x24a537r9 looks like there is an error in your example. `ReduxMappedProps` expects you to return `a` but your mapStateToProps returns `b`.

You can see here how exact props are designed to work with react-redux: https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.63.0-/test_connect.js#L136

**Comment by retyui** [comment]
@0x24a537r9
```js
// @flow
import React, {type Node} from 'react';
import { connect } from 'react-redux';

type StoreState = {|
  b: number,
|};
type ReduxMappedProps = {|
  a: number,
|};
type Props = {|
  ...ReduxMappedProps,
  b: number,
|};

const MyComponent = (props: Props): Node => {
  return null;
};

const MyConnectedComponent = connect(({b}: StoreState):ReduxMappedProps => ({a: b}))(MyComponent);

<MyConnectedComponent b={1}  />;

<MyConnectedComponent b={1} a={1} />;
```

![image](https://user-images.githubusercontent.com/4661784/48672495-b2d04880-eb47-11e8-9d67-24c1d7b0980e.png)

**Comment by fabiomcosta** [comment]
This might have been fixed on the latest version of react-redux with Flow 0.89.
@0x24a537r9 do you mind confirming if your specific issue is fixed?

**Comment by AndrewSouthpaw** [comment]
Yep, closing. Feel free to reopen if you disagree.
