### ISSUE TITLE
[BUG] Class Properties doesnt work with async functions with two generics

### ISSUE THREAD

**Issue by bradennapier** [flow-typed/flow-typed#2448]
Try Flow says it all really - not much else to add its clearly a bug.

https://flow.org/try/#0MYGwhgzhAEAqCmEAu0DeAoa0D03oHcB7AJwGsJ0BIJRFAXmgB4BBAGmgCEA+ACjAC5obaACNBHAJSDm0OlzSYs0SsXhIArsQB20MIqwBfLPuiLc0ACaFEWlETImayWbogBPLcCbDufaezFOKWgABWJCAFsASwh4Fnk5BUoVNU0dPSVoA3RsoA

**Comment by AndrewSouthpaw** [comment]
This issue belongs with the flow repo, not flow-typed. We're just in charge of library definitions.

**Comment by bradennapier** [comment]
Hmm oops don’t know how it ended up on this repo my bad

**Comment by AndrewSouthpaw** [comment]
No worries, it happens a lot. 😆
