### ISSUE TITLE
chancejs constructor defined incorrectly, named 'static'

### ISSUE THREAD

**Issue by kayneb** [flow-typed/flow-typed#2453]
In chance_v1.x.x.js, the class `Chance` has a declared function:

```
static(seed?: any): Chance;
```

Looking through the source at https://github.com/chancejs/chancejs/blob/master/chance.js I cannot see any reference to this function. This should likely be named `constructor` instead, as it is consistent with the constructor found in the above mentioned source.

**Comment by Brianzchen** [comment]
Fixed in #2454
