### ISSUE TITLE
Low hanging fruit: improve Contributing Library Definitions wiki page

### ISSUE THREAD

**Issue by callumlocke** [flow-typed/flow-typed#2471]
Whenever I come here to add a new definition for a package, I have to refamiliarise myself with where everything is, how to run the tests, etc. There's no step-by-step guide to adding a new definition. I realise there are various things that we'd like to improve about the actual dev experience (see #146 and many others), but that shouldn't stop us improving the docs today, based on how things work today.

The [Contributing Library Definitions](https://github.com/flow-typed/flow-typed/wiki/Contributing-Library-Definitions) wiki page outlines the structure and test requirements for definitions, but it's missing stuff like:

- how to run the tests locally while you're developing?
  - does it work if you use your globally installed `flow-bin` command, or should you cd into the `cli` folder and run `yarn global link` first, or should you just run `node ./cli/dist/cli.js` as the `run-def-tests.sh` script does?
  - is there a watch mode?
- how to run tests for just the definition you're adding, to save time?
- is it OK to cover only the Flow version you're using, or are you actually required to cover `flow_v0.25.x` upwards?
- how to choose a good branch name and PR name/description? (even just some links to good examples)

Maybe some of these can be answered by digging, but a prospective contributor shouldn't have to dig for this stuff. We need a step-by-step guide to adding a new definition, from forking the repo to opening a PR.

**Comment by AndrewSouthpaw** [comment]
Step in the right direction: #2503

**Comment by Brianzchen** [comment]
I'm going to close this because a lot has changed since this issue was raised. The how-to [guide](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md#creating-a-new-library-definition) should be sufficient with the simple scripts `./create_def.sh` and `./quick_run_def_tests.sh` should help someone get going quite quickly.

Can open a new issue if there is anything else missing.

**Comment by AndrewSouthpaw** [comment]
Agreed, thanks for cleaning up some old issues!
