### ISSUE TITLE
js-cookie getJSON type

### ISSUE THREAD

**Issue by jmarceli** [flow-typed/flow-typed#2478]
Why `js-cookie.getJSON` flow type is `mixed`?
With **lodash pick** I get:
```
Cannot call pick because mixed [1] is incompatible with object type [2].
```

Does **getJSON** return type shouldn't be `object` or `any`?
I'd be happy to get some opinions about that.

**Comment by AndrewSouthpaw** [comment]
You could probably add generics, rather than `mixed`, so require add a type for the output of `getJSON`.

**Comment by AndrewSouthpaw** [comment]
Nope, nevermind. I opened an issue with Flow: https://github.com/facebook/flow/issues/6597. In the meantime, pretty much your only other options is to just explicitly make those return types `any` so you can do whatever you want with it.

**Comment by AndrewSouthpaw** [comment]
Go ahead and make a PR for it; having them typed as `mixed` is probably useless and just requires all consumes to cast first to `any` so it's just a frustrating experience.

**Comment by AndrewSouthpaw** [comment]
You could also try borrowing from the `axios` libdef, that might do what you want.
