### ISSUE TITLE
flow-typed 2.5.0 fails installing / updating packages

### ISSUE THREAD

**Issue by josser** [flow-typed/flow-typed#2482]
when running flow-typed update or install it fails with error: 
here is sample output:

```
$ which flow-typed
./node_modules/.bin/flow-typed

$ flow-typed install --overwrite 
• Found 142 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
• Installing 33 libDefs...
  • react-router_v4.x.x.js
    └> ./flow-typed/npm/react-router_v4.x.x.js
react-router
... here is list of installed typings for various packages ...
• Generating stubs for untyped dependencies...
(node:94293) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[0] usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
[0]                [-o owner] file1 file2
[0]        install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
[0]                [-o owner] file1 ... fileN directory
[0]        install -d [-v] [-g group] [-m mode] [-o owner] directory ...
[0] install exited with code 64
```

**Comment by josser** [comment]
Please note, deprecation warning is actually came from webpack, because I'm using plugin which not compatible with latest webpack@4 plugin system. 

However, i'm really interesting why flow-typed need to run webpack to install typings

**Comment by GAntoine** [comment]
Which version of node are you using? I'm using `9.11.1` and `flow-typed install --overwrite` seems to be working fine. There are issues with `10+` at the moment, so I wouldn't recommend using it. Could you rerun with `--verbose` flag?

**Comment by GAntoine** [comment]
Could you try installing `flow-typed` globally and using that version?

**Comment by josser** [comment]
Installed globally and this has fixed the issue.
Looks like good workaround 👍

**Comment by josser** [comment]
Also, it looks like 2.5.1 has been fixed the issue

**Comment by GAntoine** [comment]
Glad to hear it!
