### ISSUE TITLE
Support modularized NPM packages

### ISSUE THREAD

**Issue by josemigallas** [flow-typed/flow-typed#2488]
When I require [lodash](https://www.npmjs.com/search?q=keywords:lodash-modularized) in my projects, I rarely want to use the whole library but I just install the modularized methods like `lodash.shuffle`, `lodash.clonedeep`...

However in this case flow-typed can't find definitions for those packages so either I have to:

- `npm install` the whole library so that `flow-typed` can install the definitions automagically, or
- explicitly `flow-typed install lodash@...` manually every time, which is bad

I actually wouldn't mind having the whole definition file in my project, since it's gitignored but I would like `flow-typed` to somehow recognize a modularized package is being used. This is of course not directly related to lodash but to any library that supports this modularization.

**Comment by AndrewSouthpaw** [comment]
Definitely would be a Nice To Have. Folks are welcome to take a stab at this one, though I think it'll be challenging.

Out of curiosity, what other packages do this style of modularization?

**Comment by josemigallas** [comment]
Well actually I haven't seen that anywhere else so far! Not even underscore.. If I did take a look at this, could it be a solution to "simply" add all modularized packages under definitions/? The after after all just NPM packages.

**Comment by AndrewSouthpaw** [comment]
I'm gonna go with "no" on this solution, because it would be a maintenance nightmare, unless there was supporting code to automatically copy the types into the modularized folders.

**Comment by Brianzchen** [comment]
@AndrewSouthpaw If we had dependent definitions would you be in favour of this and then we can add more definitions for the community?

```
declare module 'lodash.shuffle' {
  import typeof { shuffle } from 'lodash';

  declare module.exports: typeof shuffle;
}
```

**Comment by Brianzchen** [comment]
^ Follow example Pr above if anyone wants to add subset packages
