### ISSUE TITLE
Styled Components - How to type styled tagged literal inner props

### ISSUE THREAD

**Issue by JCMais** [flow-typed/flow-typed#2500]
I've tried
```
const MyComp: React.ComponentType<{ color: string }> = styled.div`
  color: ${props => props.c};
`;
```

But that only types the resulting component. Basically saying `MyComp` have a `color` prop, making it necessary to pass it when rendering:
<img width="636" alt="screen shot 2018-07-12 at 23 22 15" src="https://user-images.githubusercontent.com/1041647/42669195-8bd2a8a4-862a-11e8-89de-70975d305570.png">

But that is not what I want.

How to type the `props` **inside** the tagged literal?
```
${props => props.c}
```

Does not looks like the type used by `style.div` accepts any generic:
```
div:                      $npm$styledComponents$StyledComponentsComponentListValue,
```

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/styled-components_v3.x.x.js#L165

I know I can typehint the `props` inside the function, but there are no better ways?

On typescript they have this now: https://github.com/styled-components/styled-components/pull/1798

**Comment by nicholaai** [comment]
Looks like your linter is complaining because you're not passing the color prop to your component when using it. 

also you can access it by using `props.color`, which is the prop name you gave it.

**Comment by adtm** [comment]
Did someone solve it? Cause I have the same problem.

**Comment by NickProdromou** [comment]
This is also a problem I'm currently experiencing with sc

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
