### ISSUE TITLE
Installing jest type definitions make it globally available 

### ISSUE THREAD

**Issue by kasperpeulen** [flow-typed/flow-typed#251]
I don't know, but I find it odd that if I add jest definitions that they are globally available.

It is may be a bit nitpicking, but now I get expect, describe, it suggested (with auto completion) everywhere. And if I use it (out of the jest context), flow is totally happy, where this is actually a bug.

**Comment by ryyppy** [comment]
Sadly, this is something which cannot be prevented for now. Same problems occur for other tools like eslint, which have to assume some globally set entities,... do you have so many name collisions with actual code? Like, by typing a `describe`, `it`, `beforeEach` function? IMO I never had a problem with that in a very long time (since I have been using jasmine)

**Comment by kasperpeulen** [comment]
No I have had no "real" problems with it (yet). It is just that it feels wong and I want to import {describe, it, expect, beforeEach} from "jest"; in my test files instead.

**Comment by ryyppy** [comment]
From a runtime perspective, these functions will only be injected in tests, which should be isolated from the actual code... that's how `jest`, `mocha` and `jasmine` are designed. 

If you don't like this behavior, I can highly recommend other frameworks like `tape` and `ava`, which both expose their functions via module scope.

For `flow`, it doesn't really matter for following reasons:

- The only real problems with name collisions happen if you try to use multiple test frameworks with similar global function definitions (e.g. `mocha`, `jasmine` or `jest`)
- `flow` does not really interfere with your implementation code and it's very easy to cover edge cases by using `suppress comments`

Not sure where to go from here... I don't think you have to worry too much about those edge cases TBH :-)

**Comment by kasperpeulen** [comment]
> From a runtime perspective, these functions will only be injected in tests, which should be isolated from the actual code... that's how jest, mocha and jasmine are designed.
I'm used to test frameworks from other (typed) languages where I just import my test functions, just like any other function. In mocha I actually do this btw:

```
import {expect} from 'chai';
import {describe, it} from 'mocha';
import {square} from './index';

describe("square", () => {
  it("squares a number", () => {
    expect(square(3)).to.equal(9);
  });
});
```

But maybe this is my mistake, I'm just learning javascript frameworks for a couple of days.

To be honest, the reason I noted, and disliked is because I'm used to writing `exp<ENTER>` and then I normally got `export` when doing this, now this autocomplets to `expect`. Just an habit, and I can write `expo` of course, no problem.

But I was just like, what the hell, jest function should not even be available here. This is off. Everything in my ES6 code is neatly imported except jest, which want to be available everywhere, who does this Jest think he is :) 

But anyway, close this if you want, I guess there is not something that can or will be changed.

**Comment by Tallyb** [comment]
+1  as it collapses with Jasmine, used for E2E testing...

**Comment by michaelhogg** [comment]
+1 for this unfortunate issue.

As a workaround, is it possible to run two Flow servers on the same source directory, with different [configurations](https://flow.org/en/docs/config/)?

1. A Flow server for **only checking source code**, which is configured to:
    * [ignore](https://flow.org/en/docs/config/ignore/) Jest files (ie: only include normal source files)
    * not [load](https://flow.org/en/docs/config/libs/) the Jest libdef (since _"by default the `flow-typed` folder in your project root directory is included as a library directory"_, the Jest libdef would need to be placed in a different directory)
2. A Flow server for **checking source code and Jest files**, which is configured to:
    * [load](https://flow.org/en/docs/config/libs/) the Jest libdef

In this way, any usage of `describe()` `it()` etc in normal source code would be detected by the 1st server.

**Comment by Brianzchen** [comment]
The solution is to add definitions for `@jest/globals`
