### ISSUE TITLE
Axios 0.18.x "Unexpected token <" on line 102 positon 9

### ISSUE THREAD

**Issue by danielkarlsson** [flow-typed/flow-typed#2512]
When running flow axios throws error "Unexpected token <" on line 102 position 9

```
102│     [[call]]<T,R>(config: AxiosXHRConfig<T,R> | string, config?: AxiosXHRConfig<T,R>): AxiosPromise<T,R>;
```

Tried downgrading to 0.17.x with  the same result

**Comment by AndrewSouthpaw** [comment]
What version of flow are you running?

**Comment by stevenw00** [comment]
I am also facing the same issue in flow version 0.75 & 0.77.

**Comment by danielkarlsson** [comment]
After upgrading to 0.77 the error went away for me, was running 0.75 before. 

@stevenw00 Try to edit your flowconfig so that it reruns, maybe there are cache issues. Otherwise you are not happening to run it either globally or from your project with 0.75 version still or something?

**Comment by Dhuliang** [comment]
Same error at version 0.78

**Comment by brandoncc** [comment]
I have the same error at version 0.79.1

**Comment by brandoncc** [comment]
Oops, it turns out I had a global install that was being used and was an older version.
