### ISSUE TITLE
flow-typed install should ignore the comments in package.json

### ISSUE THREAD

**Issue by ssvgaddam** [flow-typed/flow-typed#2537]
**Issue:** if a package.json(as shown in below example) have comments then flow-typed install should ignore those comments.

**For example**,
**package.json:**
{
  "name": "xyz",
  "version": "0.1.0",
  ...........,
  "dependencies": {
     "//": "some comment goes here regarding the below dependency",
     "someDependency" : "0.1.0"
  }
  "scripts": {
    .......
  }
}

**Note:**
if the comments are not ignored while installing libraries then the flow-typed install fails throwing the below error:
glob error { Error: EACCES: permission denied, scandir '/lost+found'

  errno: -13,

  code: 'EACCES',

  syscall: 'scandir',

  path: '/lost+found' }

UNCAUGHT ERROR: Error: EACCES: permission denied, scandir '/lost+found'

**Comment by AndrewSouthpaw** [comment]
Wow, I didn't even know you could leave comments in `package.json`. You're welcome to introduce a fix, but I'm pretty sure it's not a strong use case for any of us maintainers to tackle it.

**Comment by rocketraman** [comment]
@AndrewSouthpaw  I encountered this problem too. Not sure why its not a strong use case for a maintainer to tackle -- this form of comments in `package.json` was stated by an npm maintainer to be reserved for comments (see https://groups.google.com/forum/#!msg/nodejs/NmL7jdeuw0M/yTqI05DRQrIJ), as well as this highly-voted stackoverflow post: https://stackoverflow.com/a/14221781/430128 [1]).

Furthermore, the failure mode here is terrible.

[1] <rant>I'm not gonna argue whether putting comments in JSON is well-advised or not -- it was probably ill-advised for npm to use JSON as its config format in the first place, so we're well past well-advised already. I think its ridiculous not being able to properly comment a build script, and having to resort to hacks like this, but that's just my opinion.</rant>
