### ISSUE TITLE
flow-typed global types : referenceerror x is not defined

### ISSUE THREAD

**Issue by ycmrun** [flow-typed/flow-typed#2540]
I have global type defined in a .js file and it resides in flow-typed folder under the root of my project. 

// @flow
declare type MCUserID = number;

declare var mcuser: MCUserID;

And [libs] section my .flowconfig looks like below.
[libs]
flow-typed

But when I try to use mcUser  in other modules in the project, I get error 
ReferenceError: mcUser is not defined

Am I missing some other configuration  ?

**Comment by AndrewSouthpaw** [comment]
Should need to add `flow-typed` to `[libs]`, it's included by default. What's your flow and flow-typed version? Can you verify you're running locally?

**Comment by ycmrun** [comment]
I'm running these locally. Here are my versions.

"flow-bin": "0.69.0",
"flow-typed": "2.4.0",

**Comment by AndrewSouthpaw** [comment]
I'm not seeing anything obvious... @villesau, @adityavohra7?

**Comment by AndrewSouthpaw** [comment]
Also, could you create a repro repo?

**Comment by adityavohra7** [comment]
@AndrewSouthpaw not sure what's happening, I tried reproducing the error.

Here's the file in `flow-typed/`:
```javascript
// @flow
declare type MCUserID = number;
declare var mcuser: MCUserID;
```
Here's a file in my project:
```javascript
// @flow
const myString: typeof mcuser = 'foobar';
```

Output from `flow status`:
```
➜  /nail/home/avohra/libraries/temp  yarn flow status
yarn run v1.3.2
warning package.json: No license field
$ /nail/home/avohra/libraries/temp/node_modules/.bin/flow status
Launching Flow server for /nail/home/avohra/libraries/temp
Spawned flow server (pid=66989)
Logs will go to /tmp/flow/zSnailzShomezSavohrazSlibrarieszStemp.log
Monitor logs will go to /tmp/flow/zSnailzShomezSavohrazSlibrarieszStemp.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ foo.js:3:33

Cannot assign 'foobar' to myString because string [1] is incompatible with number [2].

     foo.js
     1│ // @flow
     2│
 [1] 3│ const myString: typeof mcuser = 'foobar';
     4│

     flow-typed/foo.js
 [2] 4│ declare var mcuser: MCUserID;



Found 1 error
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Flow seems to be complaining as expected.

Some deets about my platform:
```
➜  /nail/home/avohra/libraries/temp  yarn flow version
yarn run v1.3.2
warning package.json: No license field
$ /nail/home/avohra/libraries/temp/node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.79.1
Done in 0.20s.
➜  /nail/home/avohra/libraries/temp  node --version
v8.9.1
```

**Comment by Brianzchen** [comment]
Unrelated to flow-typed itself. If this was a problem it was one with flow
