### ISSUE TITLE
React-redux type for connect does not allow mapDispatchToProps as function anymore

### ISSUE THREAD

**Issue by joshuajaco** [flow-typed/flow-typed#2628]
I'm getting the following flow error with the new react redux flow types, when using `connect` with a `mapDispatchToProps` function. The error does not occur when using an object instead.

```
• Either function [1] is not an object.
• Or ST [2] is not a React component.

 flow-typed/npm/react-redux_v5.x.x.js
 [2] 132│     ST: $Subtype<{[_: $Keys<Com>]: any}>

 [1]  75│ const mapDispatchToProps = (dispatch: Dispatch): DispatchProps => ({
      76│   someProp: () => dispatch(someAction()),
      77│ });
```

**Comment by villesau** [comment]
@maximeg @LoganBarnett as recent contributors, do you have thoughts on this?

**Comment by LoganBarnett** [comment]
``` javascript
ST: $Subtype<{[_: $Keys<Com>]: any}>
```

This part has been in here before my changes but we are running into issues with it being _involved_ in type coverage being lost for stateless components. I don't know what to do to fix it though. I understand it's there because it mimics the wrapped nature of the connected component (statics are still there, properties, etc).

Simply removing it makes stateless components Just Work from a type coverage and checking perspective, but it breaks existing tests. I haven't had much time to look into how to express a React type that's common between the two kinds of components but nothing has turned up so far.

**Comment by LoganBarnett** [comment]
Likely related to #2553

**Comment by amccloud** [comment]
@LoganBarnett @joshuajaco just a heads up that this appears to be the same issue https://github.com/flow-typed/flow-typed/issues/2628

**Comment by erictaylor** [comment]
@amccloud I'm having the same issue as @joshuajaco and we are using a custom `Dispatch` type.

```
type Dispatch<S = State, A = Action> = (
  action: A | ThunkAction<S, A> | PromiseAction<A>,
) => any;
```

**Comment by joshuajaco** [comment]
Yep we are also using a custom one. Pretty much the exact same erictaylor is using

**Comment by erictaylor** [comment]
@sherwinyu no I have not. I've pretty much have had to do the same thing. In some cases where we could I've modified `mapDispatchToProps` to immediately return an object, which fixes the issue, however there are lots of cases where we need the dispatch function to properly map. Would be great if someone could chime in with an appropriate fix.

**Comment by sherwinyu** [comment]
Interesting -- could you share more what you mean by "merging" it with your
custom definition?

**Comment by callmetwan** [comment]
Sorry, using ‘&’ to join them together as in

‘export dispatch = Dispatch & YourDefinition’

**Comment by callmetwan** [comment]
I think I'm wrong about this. It just moves the error from the connect statement to the consuming component. I get
>Cannot create element because: Either function [1] is not an object or `ST` [2] is not a React component.

**Comment by tobiasfriden** [comment]
Any progress or possible fix on this one? I am seeing the same one even when using object-only `mapDispatchToProps`.
