### ISSUE TITLE
What is the preferred way for a module to provide its own libdef if it's not written in Flow?

### ISSUE THREAD

**Issue by ankushg** [flow-typed/flow-typed#2664]
Hi there! I've got a project I'm working on that's **generating** JS and its own Flow libdef, but the **code itself is not written in Flow**. 

I've seen that projects that are themselves written in Flow can just include the `*.js.flow` sources, but I don't have a full set of Flow sources. I only have a libdef in the form of a bunch of `declare module` and `declare type` statements. 

Is that still something I can include in a `*.js.flow` file and have automagically picked up by Flow?

**Comment by GAntoine** [comment]
Hi! This is the project for the flow-typed library, a collection of third-party flow definitions. You might want to try asking for help on the flow project page.
