### ISSUE TITLE
Bad folder name for react-router

### ISSUE THREAD

**Issue by IanVS** [flow-typed/flow-typed#2682]
I noticed that `flow-typed install` is installing a stub instead of grabbing https://github.com/flow-typed/flow-typed/blob/9bc80757d98750d6a5419670f4401feffc9c6e4e/definitions/npm/react-router_v4.x.x/flow_v0.53.x-flow_v0.62.x/react-router_v4.x.x.js, and I think it's because the path is incorrect.

is: `flow_v0.53.x-flow_v0.62.x`
should be: `flow_v0.53.x-v0.62.x`

Is that the case?  If so, I can make a PR.

**Comment by villesau** [comment]
@IanVS please do! definitely not correct format.
