### ISSUE TITLE
Can flow-type for lodash map be more permissive? 

### ISSUE THREAD

**Issue by eaharonoff** [flow-typed/flow-typed#2701]
I have an array of objects that I want to map like so:
```
type Person = { 
name: string,
};
...
const content = [ { name: 'jim' }, { name: 'jane' } ];
const people = map(content, (person: Person): React$Element<*> => {
  return (
    <div>
       { person.name }
    </div>
});
```
The error I am receiving is `Cannot call map because Person [1] is incompatible with string [2] in the first argument.`
`     flow-typed/npm/lodash_v4.x.x.js
 [2] 634│       iteratee?: (char: string, index: number, str: string) => any`

So does this mean that I am not supposed to use an object as the iteratee's first argument as it was only intended to have a string as the first argument? Is it possible to update this flow-typed rule to allow for a object as the iteratee's first argument? I've never contributed but I'd be open to helping out on that front. Thanks in advance!

**Comment by Brianzchen** [comment]
This works after testing in 2022. Sorry it's taken so long.
