### ISSUE TITLE
[react-redux] Some type can not be imported from /react-redux_v5.x.x/flow_>=v0.68.0

### ISSUE THREAD

**Issue by mali-tian** [flow-typed/flow-typed#2710]
## Issue:

Some declared type can not be found from `react-redux` when we start to use the https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/react-redux_v5.x.x.js

here is an example, when we try 
```
import type { MapDispatchToProps } from 'react-redux';
```
then run flow checking, we will get the error:
```
Cannot import MapDispatchToProps because there is no MapDispatchToProps export in react-redux
```

unless I removed all `export` keyword from https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/react-redux_v5.x.x.js
or 
I manually change the code to export the `MapDispatchToProps` in https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.68.0-/react-redux_v5.x.x.js

## Question:

Are you going to remove some type checking in the future in `react-redux`? like `MapDispatchToProps` for example?

**Comment by AndrewSouthpaw** [comment]
Check out the test file for the `react-redux` libdef for examples of how to do type checking for Redux. Feel free to reach back out with questions.
