### ISSUE TITLE
Have `runTests` spec only run against latest flow version.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [flow-typed/flow-typed#2723]
Our CI build breaks routinely due to the `runTests` spec, which checks that unnecessary suppression comments fail correctly in flow. It breaks usually because it's running against _all_ versions of flow, not just the latest.

Let's change it to run against only the latest version, because it should still catch any unexpected change in suppression behavior for Flow and make our CI more reliable.

**Comment by villesau** [comment]
I can do the change.
