### ISSUE TITLE
connect from `react-redux` doesn't check types for `mapState` function

### ISSUE THREAD

**Issue by PinkaminaDianePie** [flow-typed/flow-typed#2734]
Connect from `react-redux` doesn't check types for `mapState` function, instead of throwing errors on incompatible types, it changes output type of `mapState` function.
```javascript
// @flow
import React from 'react';
import { connect } from 'react-redux';

type Props = {|
  +foo: string
|};

const Component = ({ foo }: Props) => (<div>{foo}</div>);

type State = {|
  +foo: number;
|}

const mapState = ({ foo }: State) => ({ foo });

export default connect(mapState)(Component);
```
Here I return `number` in `foo` from mapState, but my component expects `string`. It should throw an error, but instead flow change return type of `mapState` function to `{ foo: string | number}`. So flow doesn't show me any errors in this code, but it obviously incorrect.

Screenshot with result:
![redux_flow_issue](https://user-images.githubusercontent.com/1625500/45597465-241b4000-b9cd-11e8-959b-9a0f47eafc7c.png)

flow-bin: 0.81.0

// flow-typed signature: 502cfd4f5e95c6308f747cdf16dc93ce
// flow-typed version: 1751d5bf0a/react-redux_v5.x.x/flow_>=v0.68.0

**Comment by AndrewSouthpaw** [comment]
I think the issue is that you aren't using the component yet. Once you do something like `<Component />` it'll throw the error you seek. LMK if that's not the case.
