### ISSUE TITLE
react-select for flow 0.53+

### ISSUE THREAD

**Issue by IanVS** [flow-typed/flow-typed#2782]
It seems like react-select was [limited](https://github.com/flow-typed/flow-typed/commit/19506e57e6a19b813ec13cbab4244b3ab7f938cb) to flow 0.52, and now that I've upgraded to 0.53 I've lost all my flow typing for react-select.  What would it take to get a definition set available for newer versions of flow?  Thanks!

**Comment by AndrewSouthpaw** [comment]
You're welcome to copy the libdef and create a new version, and see how the tests work out.
