### ISSUE TITLE
Question: Are type definitions for decorators (TC39 stage 2) worth submitting?

### ISSUE THREAD

**Issue by craigfowler** [flow-typed/flow-typed#2816]
I've thrown together [some types for describing] the [TC39 proposal for class & member decorators] - currently at stage 2.  Strictly-speaking this isn't a libdef that flow-typed would carry in the usual sense. 
 Assuming it gets to stage 4 someday decorators would then become a first-class part of the JavaScript language, presumably handled by flow itself.  Are these of any use to flow-typed in the interim though?  I can contribute them if they're desired but I won't take offence if they're not.

[some types for describing]: https://github.com/csf-dev/proposal-decorators-types
[TC39 proposal for class & member decorators]: https://github.com/tc39/proposal-decorators/

Of course, as with flow itself, the types I wrote can't do anything to account for the type implications of decorators (eg: a decorator could feasibly change the return type of a class function which it decorates).  They are really just there as a convenience so that appropriate things appear in your IDE's autocomplete/intellisense/whatever.

Is it worth me formalising them into a format for submission to flow-typed or would I be wasting my time?  Thanks.

**Comment by Brianzchen** [comment]
Thanks for recommending this and apologies for the late reply. But for now I would say no, `flow-typed` isn't made to support built-in definitions or features as when you use a decorator you wouldn't be importing anything so there wouldn't be any modules to `declare {`. the flow repo itself would be the better place for this.
