### ISSUE TITLE
question: express_v4.16.x types

### ISSUE THREAD

**Issue by ericcheunghk01** [flow-typed/flow-typed#2818]
```
  declare export type RouterOptions = express$RouterOptions;
  declare export type CookieOptions = express$CookieOptions;
  declare export type Middleware = express$Middleware;
  declare export type NextFunction = express$NextFunction;
  declare export type RequestParams = express$RequestParams;
  declare export type $Response = express$Response;
  declare export type $Request = express$Request;
  declare export type $Application = express$Application;
```
Hi everyone,
I am new to use `flow-typed`. I would like to ask why `$Response`, `$Request` and `$Application` will with the `$` and others without `$`, any reason behind?

**Comment by LoganBarnett** [comment]
@ericcheunghk01 older versions of Flow had trouble with scoping in definitions. Types were effectively globally scoped in a libdef. It used to be recommended that we use a `$` delimited definition. That explains the `express$Foo` types.

Also I think the core library had Flow-authored types not managed by `flow-typed` were always global (and may still be to this day). So `Request` and `Response` you get from the `net` module would be shadowed here in your example, so they were given the `$` prefix to get around this.

Mostly what you're seeing is legacy and nobody has gotten around to updating it, but `$Request` and `$Response` may still be necessary.
