### ISSUE TITLE
[Ecosystem] Vendoring in libraries?

### ISSUE THREAD

**Issue by ryyppy** [flow-typed/flow-typed#286]
I realized that more and more libdefs are about to be shipped with the related npm package... which is awesome, but.... isn't this going to be a huge problem with breaking flow versions? 

Flow-Typed at least has a formal way of handling flow dependencies!

There needs to be a definitive recommendation how to handle libdefs for library authors... IMO it makes more sense to have a readme template instructing the users how to get libdefs for the target library and keep the libdefs in one place...

Talking especially about these PRs in [redux](https://github.com/reactjs/redux/pull/1887) and [avajs](https://github.com/avajs/ava/pull/1007)

Other libraries I could think of are react-native, draftjs, immutablejs ,...

@gabelevi @jeffmo @thejameskyle

**Comment by thejameskyle** [comment]
@gabelevi @jeffmo and I met a few weeks back to discuss the different workflows we wanted to recommend.

For libraries there are two scenarios: Ones written in Flow and ones that are not written in Flow.

For ones written in Flow the recommendation in our document is to ship them as `.js.flow` files. For ones that are not, the recommendation is to contribute back to flow-typed.

I'm still not a fan of this, I want it to be that flow-typed is always the source of truth and we should build tools around that. I think that makes for a better ecosystem.

**Comment by montogeek** [comment]
What about something similar as https://github.com/typings/typings but for Flow?

**Comment by jrnail23** [comment]
@thejameskyle: for a lib written in flow that also uses flow-typed libs, how should we deal with those flow-typed defs?  Do you also ship the flow-typed defs as `.js.flow` files?

And when using my lib in a project, will that lib's flow-typed defs conflict with any that my project may already be using? (i.e., let's say both the lib and my project use bluebird's flow-typed defs)

**Comment by Brianzchen** [comment]
After 5 years this issue seems solved.
- typed libs ship with `.js.flow`
- untyped are added to flow-typed
- for libs written in flow that use flow-typed it's been solved recently by #4143
