### ISSUE TITLE
flow-typed is thoroughly unreliable

### ISSUE THREAD

**Issue by kaiyoma** [flow-typed/flow-typed#2871]
OS: Windows 10
Node: 8.11.4
flow-typed: 2.4.0

I've been running flow-typed a bunch today and have been seeing lots of unreliable results. Runs of the tool vary wildly in their success/failure results and I often see spurious errors that I don't see with any other tool. For instance, one run today resulted in a "bad file descriptor" error - something I never see - then a subsequent run worked fine.

Here's another scenario I ran today:

1. `flow-typed install`
2. `git add .`
3. `git commit`
4. `flow-typed install`

At this point, I fully expected there to be no changes, but instead the entire contents of the lodash libdef were deleted (the file itself was not deleted). When I reset my workspace and ran all the commands again, everything worked as expected (there were no changes after step 4 above).

**Comment by villesau** [comment]
@kaiyoma are the repro steps reliable? Does it happen every time when going trough the steps?

**Comment by kaiyoma** [comment]
No, they aren't reliable, which is the whole point of this issue. 😄 

Issues don't happen every time and different issues pop up. They all seem to be filesystem-related though.

**Comment by kaiyoma** [comment]
That's the working theory here too. My coworker runs this tool periodically on his Mac and hasn't seen these problems. I don't see any of these issues with all the other web development tools I use (git, npm, yarn, mocha, jest, eslint, lesshint, flow, etc). Are you guys using a different/specialized library or API for interacting with the filesystem?

**Comment by villesau** [comment]
Here is the lib having all the file utilities: https://github.com/flow-typed/flow-typed/blob/master/cli/src/lib/fileUtils.js
So `fs-extra`, `fs` and `mkdirp` seems to be in use. Flow-typed also uses git under the hoods by executing the commands, see https://github.com/flow-typed/flow-typed/blob/master/cli/src/lib/git.js . Not sure if that could affect?

**Comment by Brianzchen** [comment]
This happens to me and my team and we are on macos. This issue is fairly old but I believe with some recent performance improvements released in v3.6.0 should have fixed what was overloaded behaviour.

Related issue #4138 references the same problem just with a different library. Will close to consolidate future conversation.
