### ISSUE TITLE
Using Default Props for Functional Components collides with eslint rule default-props-match-prop-types

### ISSUE THREAD

**Issue by schumannd** [flow-typed/flow-typed#2874]
My example code which is very close to [this example code](https://flow.org/en/docs/react/components/#toc-using-default-props-for-functional-components) triggers [this eslint error](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/default-props-match-prop-types.md).

```
// @flow
import React from 'react';
import { View } from 'react-native';

type GraphLegendType = {
  onPress: Function,
};

const GraphLegend = ({ onPress }: GraphLegendType) => <View>{onPress()}</View>;

GraphLegend.defaultProps = {
  onPress: () => {},
};

export default GraphLegend;
```

I don't know why this happens, or whether flow or eslint is at fault here.

**Comment by Brianzchen** [comment]
There is some long winded conversation about `defaultProps` and how it should be handled on the eslint repo something close to [this](https://github.com/yannickcr/eslint-plugin-react/issues/2396) but this isn't an issue related to flow nor flow-typed tbh.

I guess if it's related to best practices of using flow I would recommend to not use `defaultProps` anymore in general, after adopting flow my team opted to just use standard default values in the function arg with no troubles, maybe something you can consider also.

```
// @flow
import React from 'react';
import { View } from 'react-native';

type GraphLegendType = {
  onPress?: () => void,
};

const GraphLegend = ({ onPress = () => {} }: GraphLegendType) => <View>{onPress()}</View>;

export default GraphLegend;
```
