### ISSUE TITLE
Flow v.0.84.0 explicit inexact objects

### ISSUE THREAD

**Issue by jbrown215** [flow-typed/flow-typed#2876]
We will be releasing flow 0.84.0 this week, which includes the `...` syntax for inexact objects (for more info, see the [blog post](https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf)).  AFAIK, flow-typed doesn't require [babel support](https://github.com/babel/babel/pull/8884) to land before we can start upgrading the syntax here. I'm aiming to have the `flow-upgrade` command ready end of week to help you guys move through this as quickly as possible.

I'm opening this issue as a request for help, as I am not able to see this through myself. I imagine a script can be written with the following logic:
```
for each flow-typed library definition:
  copy the folder to one for flow v0.84.0
  run `flow-upgrade` in that new folder
```

**Comment by jbrown215** [comment]
`flow-upgrade` is blocked on the new flow parser being deployed, which should happen today or tomorrow. As soon as that happens, I'll make sure everything is ok with flow-upgrade and release.

I've noticed a few bugs in the tools `flow-upgrade` relies on, so I'm fixing those as I find them. A notable such example is that `recast` doesn't traverse opaque types.

The good news is that this change is not breaking-- we are still parsing anything with just curly braces `{}` as inexact objects, so you have at the very least 2 weeks from when the new version of flow is released to make sure this gets done.

**Comment by villesau** [comment]
Ok, that's good to know! 2 weeks should be enough for us to migrate the libdefs to new format. Eaxct by default change is great BTW! :)

**Comment by jbrown215** [comment]
Thanks for the help here! it would be useless if it broke all of the types our community has made until now

**Comment by villesau** [comment]
@jbrown215 Turns out latest release is not stable in Travis: https://github.com/flow-typed/flow-typed/issues/2916

We might need to disable checks for 0.84.0, which means that we can't migrate libdefs to 0.84 either: We can't test them.

**Comment by jbrown215** [comment]
No worries. A lot of things have to go right on our side before we're ready to parse objects as exact by default. You'll likely have a few releases to get this done. As soon as the change lands in master I'll update you here if this issue is still open.

**Comment by villesau** [comment]
Ok, good! And thanks for keeping us updated! We started to skip 0.84.0 to get tests succeed again. Looks like it worked.

**Comment by villesau** [comment]
An idea that came to my mind is that it could make sense to turn all the libdefs to be exact by default regardless how they are now defined. I'm pretty sure that in most cases it would be more accurate and inexact definition is just laziness or ignorance.

The issue might be that some libdefs might not have all the props defined which will cause errors.

**Comment by Brianzchen** [comment]
Closed by https://github.com/flow-typed/flow-typed/pull/3467
