### ISSUE TITLE
Flow-typed ramda errors, even if not uses id code

### ISSUE THREAD

**Issue by edgar0011** [flow-typed/flow-typed#2883]
ramda as devDependency, not used in code, flow just keeps stmbling upon flow-typed ramda package it self

`Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1489:48
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1486|   declare var mergeDeepRight: (<A, B>(a: A, b: B) => B & A) &
     1487|     (<A, B>(a: A) => (b: B) => B & A);
     1488|
     1489|   declare type MergeWith = (<A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1490|     fn: (a: T, b: T) => T,
     1491|     a: A,
     1492|     b: B
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1489:71
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1486|   declare var mergeDeepRight: (<A, B>(a: A, b: B) => B & A) &
     1487|     (<A, B>(a: A) => (b: B) => B & A);
     1488|
     1489|   declare type MergeWith = (<A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1490|     fn: (a: T, b: T) => T,
     1491|     a: A,
     1492|     b: B
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1507:23
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1504|
     1505|   declare type MergeWithKey = (<
     1506|     S: string,
     1507|     A: { [k: string]: T },
     1508|     B: { [k: string]: T },
     1509|     T
     1510|   >(
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1508:23
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1505|   declare type MergeWithKey = (<
     1506|     S: string,
     1507|     A: { [k: string]: T },
     1508|     B: { [k: string]: T },
     1509|     T
     1510|   >(
     1511|     fn: (s: S, a: T, b: T) => T,
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1515:36
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1512|     a: A,
     1513|     b: B
     1514|   ) => A & B) &
     1515|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1516|       fn: (s: S, a: T, b: T) => T,
     1517|     ) => (a: A, b: B) => A & B) &
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1515:59
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1512|     a: A,
     1513|     b: B
     1514|   ) => A & B) &
     1515|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1516|       fn: (s: S, a: T, b: T) => T,
     1517|     ) => (a: A, b: B) => A & B) &
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1518:36
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1515|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1516|       fn: (s: S, a: T, b: T) => T,
     1517|     ) => (a: A, b: B) => A & B) &
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1519|       fn: (s: S, a: T, b: T) => T,
     1520|     ) => (a: A) => (b: B) => A & B) &
     1521|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1518:59
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1515|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1516|       fn: (s: S, a: T, b: T) => T,
     1517|     ) => (a: A, b: B) => A & B) &
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1519|       fn: (s: S, a: T, b: T) => T,
     1520|     ) => (a: A) => (b: B) => A & B) &
     1521|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1521:36
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1519|       fn: (s: S, a: T, b: T) => T,
     1520|     ) => (a: A) => (b: B) => A & B) &
     1521|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1522|       fn: (s: S, a: T, b: T) => T,
     1523|       a: A,
     1524|     ) => (b: B) => A & B);
Error --------------------------------------------------------------------------- flow-typed/npm/ramda_v0.x.x.js:1521:59
Cannot use function type as a type because function type is a value. To get the type of a value use typeof.
     1518|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1519|       fn: (s: S, a: T, b: T) => T,
     1520|     ) => (a: A) => (b: B) => A & B) &
     1521|     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1522|       fn: (s: S, a: T, b: T) => T,
     1523|       a: A,
     1524|     ) => (b: B) => A & B);
`

**Comment by retyui** [comment]
@edgar0011 Can you tell what version flow did you use?

**Comment by edgar0011** [comment]
flow
  "version"       : "0.2.3"

"flow-bin",
  "version": "0.84.0",

flow typed "version": "2.5.1"

**Comment by AndrewSouthpaw** [comment]
It would be handy to get a repro repo...

**Comment by amirbr** [comment]
I update flow-typed Ramda by this command `flow-typed update ramda` and all the errors have been resolved.
I hope it will help.
