### ISSUE TITLE
Momentjs  >2.14.0 construct support `{}` and `[]`

### ISSUE THREAD

**Issue by gusdecool** [flow-typed/flow-typed#2903]
Momentjs starting from [v2.14.0](https://momentjs.com/docs/#/parsing/now/) support construct using empty object and empty array.
Looks like flow typed haven't updated to support this type. https://github.com/flow-typed/flow-typed/blob/77d9eda30fb387061a41ac90bd967f24f47cd6fd/definitions/npm/moment_v2.x.x/flow_v0.25.x-/moment_v2.x.x.js#L123-L131

We will need to update the allowed parameters to also support these types.

**Comment by villesau** [comment]
@gusdecool would you be willing to submit a pull request? here are instructions about contributing the libdefs: https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md

**Comment by gusdecool** [comment]
Sure, i will find time to make the Pull Request 🙂

**Comment by gusdecool** [comment]
Pull request added 🙏
