### ISSUE TITLE
[jsonwebtoken] Token header/payload can contain any JSON serializable property

### ISSUE THREAD

**Issue by samueljseay** [flow-typed/flow-typed#2919]
As far as I can interpret the jwt spec, I believe that both the Token type [declared here](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/jsonwebtoken_v8.3.x/flow_v0.56.x-/jsonwebtoken_v8.3.x.js#L100) and the Payload type [declared here](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/jsonwebtoken_v8.3.x/flow_v0.56.x-/jsonwebtoken_v8.3.x.js#L90) should be able to contain any JSON serializable property.

In one example, an AWS Cognito JWT header contains a `kid` field which causes flow to break for me in this instance.

https://jwt.io/introduction says "The header **typically** consists of two parts: the type of the token, which is JWT, and the hashing algorithm being used, such as HMAC SHA256 or RSA." But there is no statement that it must.

As for the payload it can also contain custom claims which could also be virtually anything.

I would be happy to make a PR to fix this if I could get some guidance on what would be the preferable way to represent JSON serializable properties in flow-typed.

**Comment by retyui** [comment]
First, you need to write tests to describe the behavior, then update the types to fix the errors.

[How to write tests correctly](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md#writing-tests)

```js
// the problem
var j = require('jsonwebtoken');

j.decode(j.sign('123','retyui'), {complete: true});
/*
{ header: { alg: 'HS256' },
  payload: '123',
  signature: 'XqiFdqm1349iHSx9nuVSwUgPLgn1Xinr3bmewprjew4' }
*/
```

**Comment by AndrewSouthpaw** [comment]
I think you're looking for the indexer property, which is described under Object type in the flow docs, that might point you in the right direction.

**Comment by samueljseay** [comment]
Closing because I no longer use flow and so will be unlikely to submit a PR
