### ISSUE TITLE
Stub data does not work if stub file was defined at `flow-typed/` folder

### ISSUE THREAD

**Issue by artyomtrityak** [flow-typed/flow-typed#2943]
Stub data does not work if stub file was defined at `flow-typed/` folder.
If i pull `svg-stub.js` file to any other folder it works.

.flowconfig
```
[options]
module.file_ext=.js
module.file_ext=.svg
module.name_mapper='.*\.svg$' -> '<PROJECT_ROOT>/flow-typed/svg-stub.js'
```

`svg-stub.js` content

```
/* @flow */
declare export default {[key: string]: string};
```

**Comment by AndrewSouthpaw** [comment]
I'd probably raise this in the actual Flow repo, as this is probably not an issue related to us. Closing for now, @GAntoine or @villesau et al is welcome to overrule or offer other input
