### ISSUE TITLE
[redux-saga 1.x.x]: Test file name collision on Windows systems

### ISSUE THREAD

**Issue by Mitjan11** [flow-typed/flow-typed#2950]
The windows file system is case insensitive and the flow-typed redux-saga v1.x.x (#2768) test files have a collision in file naming because of this:

`test_redux-saga_1.x.x_CANCEL.js`
`test_redux-saga_1.x.x_cancel.js`

Because of this the repository on disk is instantiated with "file changes" because one file overrides the other. As a result of this, flow typed is unable to rebase the repository because of pending file changes. (when trying to update the cache)

```
ERROR: Unable to rebase the local cache repo. Error rebasing the `master` branch of the following repo:
C:\Users\user\.flow-typed\repo

undefined

NOTE: Unable to rebase local cache! If you don't currently have internet connectivity, no worries -- we'll update the local cache the next time you do.
```

Attempting a manual rebase results in the following message:
```
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```

As a result of this you are stuck with the same libdefs until you manually remove the repository from disk and install from scratch.

**Comment by ivan-ha** [comment]
Have similar issue on mac too, `test_redux-saga_1.x.x_CANCEL.js` is edited automatically after a git clone

**Comment by villesau** [comment]
@retyui could you fix this? :)

**Comment by ericpyle** [comment]
In case others need more explicit directions, the tip for fixing this was given at the end of the problem description
> As a result of this you are stuck with the same libdefs until you manually remove the repository from disk and install from scratch.

So at the DOS cmd.exe prompt:
```
> rmdir /s /q %USERPROFILE%\.flow-typed\repo
> git clone git://github.com/flowtype/flow-typed.git %USERPROFILE%\.flow-typed\repo
```
