### ISSUE TITLE
Flow 0.85 issues with Axios libdef

### ISSUE THREAD

**Issue by kevliu** [flow-typed/flow-typed#2955]
With Flow 0.85, I'm getting issues of the sort:

Missing type annotation for R. R is a type parameter declared in function type [1] and was implicitly instantiated at call of method get [2].

 [1] 106│     get<T: any, R: any>(url: string, config?: AxiosXHRConfigBase<T,R>): AxiosPromise<T,R>;

**Comment by AndrewSouthpaw** [comment]
A *lot* of libdefs are broken by Flow 0.85. I recommend sticking with 0.84 and try updating libdefs when you have time.
