### ISSUE TITLE
Split Ramda into < 0.26.0 and 0.26.0

### ISSUE THREAD

**Issue by LoganBarnett** [flow-typed/flow-typed#2979]
You can see a list of upgrade guides [here](https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22) which outline functions that get added, removed, and deprecated (which are usually removed on the very next release). The [0.26.0 upgrade guide](https://github.com/ramda/ramda/issues/2702) removes `memoize`, and deprecates 6 more functions. If you look at prior upgrade guides you can find functions that our libdef still has which have also been removed.

We also have about 7 versions of the libdef we're maintaining. Speaking for myself, I'm finding this cumbersome to both review and maintain (although by no means deal breaking). Splitting a version up would put us at 14 versions of the libdef to maintain, and quickly becomes unsustainable as future versions roll in - albeit Ramda seems to release about once or twice a year.

I propose that we consider everything we have today to be < 0.25.0 with the caveat that it could use some further refinement to work out what's actually still in there as of 0.25.0 and before. We'll also make a version for 0.26.0 that works against the latest version of Flow only. When 0.27.0 rolls out we can do the same thing with that since we know there are backwards breaking changes with it, and treat subsequent versions the same way.

If the community needs more fidelity than that, we address it on demand and perhaps wrangle in some people to champion that cause or at least assist with maintenance.

I might take on the initial work for splitting the versions apart, but I wanted to get feedback on it first. Thoughts?

**Comment by AndrewSouthpaw** [comment]
I think it's reasonable to split out the ramda versions, considering each minor version introduces breaking changes.

I'm not terribly worried about maintainability any more than any other library; people contribute to the libdefs they care about. It may be natural that 0.25 continues to be actively developed, or it switches over to 0.26... but this is the problem that any libdef faces.

**Comment by retyui** [comment]
Assuming that for new and active projects they use the latest versions of both `ramda` and `flow-bin`.
It would be a good idea to do the separation and get rid of the remote methods. 
And update the tests of course)

**Comment by AdamWills** [comment]
Came across this thread the other day while working on a project. Is this something I can help out with?

When running the ramda tests, I discovered that there were some failing tests. I [made a PR to fix them](https://github.com/flow-typed/flow-typed/pull/3021) - figured that would be a good start.

**Comment by LoganBarnett** [comment]
@AdamWills that's a great place to start!

All of us are kind of doing this in our vast quantities of spare time. Anyone who wants to do a pull request here is welcome. Basically we need the versions split so there's a "current" (which I recommend isn't auto-followed - it would just be a def that works for 0.26.0). The version only needs to be supported for the current version of Flow. 

The specifics for this are covered [Creating a new library definition](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md#creating-a-new-library-definition) of the contributing guide, even though this is an existing libdef. Of note is the naming conventions for the files and directories in order to make them respect the version ranges we desire.

Anybody could pick it up really. It sounds like anyone who might be highly concerned with this change has spoken up and there's no opposition to doing the split. So from there it's just nuances that will be worked out in the PR.

**Comment by AdamWills** [comment]
I have a PR ready that includes a number of Ramda updates (but not all of them - I ran out of steam over the holidays). 

I'm waiting for https://github.com/flow-typed/flow-typed/pull/3021 to get merged as the new PR is based on that one.

**Comment by AdamWills** [comment]
Here's some progress on this: https://github.com/flow-typed/flow-typed/pull/3048

**Comment by AdamWills** [comment]
0.26.x has now been created and merged. There's a couple of missing definitions that I never got to, though.

**Comment by LoganBarnett** [comment]
Closing since this is addressed now. Apologies for the delay.
