### ISSUE TITLE
Typing Seems Wrong in ReactRouterDOM

### ISSUE THREAD

**Issue by gustebeast** [flow-typed/flow-typed#3007]
https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-router-dom_v4.x.x/flow_v0.63.x-/react-router-dom_v4.x.x.js

On line 70 the block method takes a callback and returns void. This doesn't match up with the functionality though:
https://github.com/ReactTraining/history#blocking-transitions

I believe the type should be
```javascript
  block(
    message: (location: Location, action: HistoryAction) => ?string | string,
  ): () => void,
```

**Comment by EvHaus** [comment]
I've created a PR to fix this: https://github.com/flow-typed/flow-typed/pull/3280
