### ISSUE TITLE
[express_v4.16.x] Deprecated utility. Using `$Subtype` types is not recommended

### ISSUE THREAD

**Issue by doberkofler** [flow-typed/flow-typed#3008]
When using flow 0.89 with the `deprecated-utility` lint rule enabled (related to #2991) the following warnings are shown:
```
Warning ---------------------------------------------------------------------- interfaces.flow/express_v4.16.x.js:123:12

Deprecated utility. Using `$Subtype` types is not recommended! (`deprecated-utility`)

   123|       req: $Subtype<express$Request>,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^


Warning ---------------------------------------------------------------------- interfaces.flow/express_v4.16.x.js:129:12

Deprecated utility. Using `$Subtype` types is not recommended! (`deprecated-utility`)

   129|       req: $Subtype<express$Request>,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^


Warning ---------------------------------------------------------------------- interfaces.flow/express_v4.16.x.js:192:12

Deprecated utility. Using `$Subtype` types is not recommended! (`deprecated-utility`)

   192|       req: $Subtype<express$Request>,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by daviduzumeri** [comment]
So now that Flow 0.98 is producing errors for `deprecated-utility` errors, is there any plan on how to deal with this? Adding properties to the request object is a fairly common practice, so simply reverting it to allowing `express$Request` on its own would probably break a huge majority of applications using this type definition. Should we just give up on flow-typing Express?

**Comment by doberkofler** [comment]
@daviduzumeri Sorry I cannot help on this as I have transitioned to TypeScript

**Comment by pbondoer** [comment]
Same happening with `express-v4.x.x`

**Comment by borlaym** [comment]
So now it is an error by default. Anyone have an idea how to handle it?

**Comment by emmenko** [comment]
I turned off the deprecated utility lint rule

```
[lints]
deprecated-utility=off
```

Someone would need to update the express types I guess, then we can turn the rule back on.

**Comment by daviduzumeri** [comment]
The question is _how_ to update the express type, as simply making it `$Request` would probably break a very high number of users of this type definition. (Personally, I'm taking this as the over-the-ledge kick to get everyone onboard with moving to TypeScript, which seems to be run by people who are actually interested in maintaining a type definition community).

**Comment by AndrewSouthpaw** [comment]
I tried to take a little stab at it, having little familiarity with `express` these days... Generally `$Shape` can serve as a standin replacement for `$Subtype`. I'm noticing [here](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/express_v4.16.x/flow_v0.93.x-/test_overrideUseMethodClassExtension.js#L6-L8) though that it looks like it should be `$Supertype` if we're passing in a custom request that has additional properties.

Unless I'm misunderstanding that?

**Comment by pbondoer** [comment]
I tried removing `$Subtype` altogether and the tests are still passing with no errors, so I'm not sure if they are of any use. Then again, I'm not using `express` so I wouldn't know if it's the appropriate "fix".

Happy to put out a PR otherwise!

**Comment by AndrewSouthpaw** [comment]
I'd say go ahead and create a PR. As long as the extant tests are passing, let's move forward. If it breaks other stuff, we can either fix it at that point or roll back this change.
