### ISSUE TITLE
[@material-ui] Type definitions for material-ui v3 are not yet available

### ISSUE THREAD

**Issue by doberkofler** [flow-typed/flow-typed#3010]
material-ui is currently on version 3 (and will soon make version 4 available) but we still only have type definitions for version 1

**Comment by locomotif** [comment]
What is the best way to know which lib someone maybe contributing to?  I wouldn't want to do double the work if someone is already working on a v3?

**Comment by pascalduez** [comment]
@locomotif No real solution, except searching for issues/PRs beforehand. 
This issue act as a request, open for anyone to tackle it.   
You can assign yourself here, also opening WIP PRs is a common pattern.

**Comment by oliviertassinari** [comment]
We are working on releasing v4. Maintaining the TypeScript definitions up to date and improving them is a significant effort. I would  expect the same time involvement required for Flow.

**Comment by oliviertassinari** [comment]
We are working on releasing v4. Maintaining the TypeScript definitions up to date and improving them is a significant effort. I would  expect the same time involvement required for Flow.

**Comment by pascalduez** [comment]
@oliviertassinari Just to clear a doubt, material-ui is not going to ship/maintain flow definitions, right?

**Comment by oliviertassinari** [comment]
@pascalduez No, unless we have people asking for it. It's not the case yet. I'm also keeping track of the trend: https://www.rank2traffic.com/flow.org.

**Comment by pascalduez** [comment]
>  I'm also keeping track of the trend

It's working so well now that people don't even need to go check the docs, here's the explanation. :sweat_smile: :clown_face:

**Comment by oliviertassinari** [comment]
@pascalduez It's probably true for React vs Vue, I'm not sure :).

**Comment by pascalduez** [comment]
Just stumbled on: https://github.com/wcandillon/material-ui-flow
