### ISSUE TITLE
Ignore possible undefined / null values if default parameter value is given.

### ISSUE THREAD

**Issue by schumannd** [flow-typed/flow-typed#3016]
Here is a minimal version describing the problem:

https://flow.org/try/#0PTAEAEDMBsHsHcBQyDGsB2BnALqAhpgCagC8oAFAB4BcoARrLNAKZ7qmjYBOArswJSkAfKADeXZth5d2lAL6oMOfEQBMHcgE9aAfgZNW6QSRHjJ09gUJb+coA

or directly here:
```
const func1 = (x: boolean = true) => {return x}

const func2 = (y: ?boolean) => {return func1(y)}

```

one solution removing the error would be:

```
const func1 = (x: boolean = true) => {return x}

const func2 = (y: boolean = true) => {return func1(y)}

```
But if I have many more functions like `func1`, I don't want to have the default value from func1 copy pasted to all of them.

Another solution would be:

```
const func1 = (x: ?boolean = true) => {return x}

const func2 = (y: ?boolean) => {return func1(y)}

```

It removes the error, and works correctly but is misleading. `func1` should not be allowed to have `undefined` as a value for parameter `x`, as the default value makes sure `x` is always defined as a boolean.

**Comment by Brianzchen** [comment]
This is a flow problem not flow-typed. Try raising this in the flow repo https://github.com/facebook/flow
