### ISSUE TITLE
Redux actions param type doesn't accept objects

### ISSUE THREAD

**Issue by JDWong-wag** [flow-typed/flow-typed#3071]
regarding https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js

Pinging @villesau , @bdelaforest 

I'm having difficulty using the redux-actions type definitions when attempting to provide it an explicit object as payload creator params.  Am I using the library incorrectly or is this a bug?

```
  declare function createAction<T, P>(
    type: T,
    $?: empty // hack to force Flow to not use this signature when more than one argument is given
  ): {(payload: P, ...rest: any[]): { type: T, payload: P, error?: boolean }, +toString: () => T};

  declare function createAction<T, A, P>(
    type: T,
    payloadCreator: (...rest: A) => Promise<P> | P,
    $?: empty
  ): {(...rest: A): { type: T, payload: P, error?: boolean }, +toString: () => T};

// works, as it should
createAction<string, string, { a: string }>(
  'ACTION_TYPE',
  inputString => ({ a: inputString })
)

// this should work, but doesn't
type Params = {
  x: number,
  y: number,
};
const payloadCreator = (p: Params) => ({
  a: p.x,
  b: p.y,
});
createAction<string, Params, $Call<typeof payloadCreator, Params>>(
  'ACTION_TYPE2',
  payloadCreator,
);

/*
Error:
payloadCreator,
      ^ Cannot call `createAction` because function [1] is incompatible with empty [2].
References:
23: const payloadCreator = (p: Params) => ({                           ^ [1]
3:     $?: empty // hack to force Flow to not use this signature when more than one argument is given
           ^ [2]
*/
```

flow demo: https://flow.org/try/#0ATAmFMGMBsEMCdzAGYFcB2kAuBLA9usJIrFuAILb7oA8AKgDTAAKAfABQBQIIWAngAdwALmCNuPACQB+UeAC2A-sAD0K4AAtYkANbAseFHniQkAMWh4A7vsPo8WYKgDOSLBpzPgznAHN0pKiIwFYa4ITyxm5ahARICL6o8uGOnsC+OABu4RIAlKIA3uwCsHyWsKCizEwAdHWIzliisOh8ANoAuvnABfqCImJMJWV4FVVM4PDwxrLAAEZ4eNDgLcAAvkwA1AYAyljwOOi+ouy5wAC8rGJrANycEhAwCEhomLgERCRklO+0jMDkJhsLg8PpCUTiUHDcqgADCX2MJzqNQaTQBZ0uLGm8k84BobGAAB8WAwJCAZHJFPw8oV2MjUaJyN1evxwYNgNDRpUScBJtN4LMFksVoQNsBtng9gcjicMVc6Ld7moQsYdM4mLAvDhHM4NHhUNBQJxiCtvlQCDRGtLfEwrYcbT1gLBRHajusOBIAOTkWF0ACSAHkAHIAfToAE1mABRT2kkCHASoLBS+0XK7sXrO4AJpMpt1rXKcQucZXuNK6-WGlXwHRMOZJsB4cDOdCerCcVlIZgIWDyLznHoSAAeonQSTmkzjwD4o-Hk84isgBEaHNKMPhpuMF2AxSqPb7cp3BQkWYENSHU7mojPfFJBbuJtIFHNtFdDu78F76uAklhsGg0A0J2eDIKuIwVBupDGEC+7OKwHogN6vqBqGEbRgATLGEichBCLwKSuQ3EAA

**Comment by retyui** [comment]
I think you should reread documentation about [`$Call`](https://flow.org/en/docs/types/utilities/#toc-call)

since what I saw in your try example is not a valid use

**Comment by retyui** [comment]
Here a valid example [flow.js try...](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxAEFNdUAeAFQBp5SGAFAPgAoAoeeDATwAOIAFzx63eAKh8IOKMADCRDDhij2AOi1wAzhlGkAlPAC8reMxg4Atlh0gqbeAB8LdCQBIA-KJDWB-JyGogDeEpraIHoGwfAhvIIiYgxSMnLAoswMIDBWMD7wAEY4OBAgUPgAvu48ANQqAMoYMFioAObqxmbJnJUA3JyDAPRDvAAWdvA6YzjIEMDwAO6qANYMhcgY8MA4UagA5Bic-EIWsFDWOqZxEgAeoqjI1oU5NfB8D08vMO79EjwAwFA4EgwGcMB4PSSaSyeRKcoqGDXdgCTLnS5dczsMI8KCiAQaW5vQr4jR8X6GAYQ1BQqAUPDw4iqACM10ICLI9OoAH0GLz4NyOBJ9qQFDQAJIAeQActyaABNZgAUQATPs3qlYYplKoggNwZCtnTsHhrsbKIzEczsfB7vBmQwPvAVfBKpTBuxzXgNJr0ho8fBHs8cu7PVyfTC-STA18Q-qRvAQLchJgQAscnlRLwoltJhU+JwwybUBG0vJ-aI9C12u6gA)

**Comment by retyui** [comment]
I think it can be closed
