### ISSUE TITLE
[react-redux] flow-typed install wont install the correct version of libdef?

### ISSUE THREAD

**Issue by jp887** [flow-typed/flow-typed#3082]
Apologies if this is just my lack of understanding and the behaviour I'm seeing is intended. But I don't seem to be able to install the new libdefs that supports flow 0.85+ with react-redux connect implemented in PR [ #3012](https://github.com/flow-typed/flow-typed/pull/3012) 

I'm using flow-bin 0.89
react-redux 5.1.1

When I run flow-typed install I'm expecting the installed libdef to be the one [here](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.89.x-/react-redux_v5.x.x.js) i.e. for flow 0.89+

What I'm actually getting is the one that looks like [this](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.68.0-v0.84.x/react-redux_v5.x.x.js) i.e. for the flow version range 0.68-0.84

Am I doing something wrong or should flow-typed be installing the newer libdef but isn't for some reason?

**Comment by AndrewTHuang** [comment]
I experienced the same thing. Targeting the specific version using something like `flow-typed install react-redux@5.0.0` installed the expected libdef.

I also assumed that `flow-typed install` would install the latest libdefs for your dependencies. Is that not the case?

**Comment by AndrewSouthpaw** [comment]
Closed due to inactivity.
