### ISSUE TITLE
Logo for flow-typed

### ISSUE THREAD

**Issue by villesau** [flow-typed/flow-typed#3084]
Flow-typed needs a logo. Best option would be to reuse Flows logo if we are allowed.

@jbrown215 Do you know wether we could use Flow logo here? Or can you put us in touch with someone who knows?

**Comment by jbrown215** [comment]
I'll find out for you!

**Comment by jbrown215** [comment]
The font used in the "flow" wordmark is not open, so you can't use the font.

Waiting on legal for a response on the graphical part of the logo. Will update here when they get back to me.

**Comment by villesau** [comment]
Thanks for keeping us updated!

**Comment by AndrewSouthpaw** [comment]
@jbrown215 Ping?

**Comment by jbrown215** [comment]
I'll ping legal again. Haven't gotten a response.

**Comment by jbrown215** [comment]
Looks like I was going through a deprecated communication channel :) Found the right place to ask the question!

**Comment by jbrown215** [comment]
Our logos are licensed the same way as our docs: https://github.com/facebook/flow/blob/master/website/LICENSE-DOCUMENTATION

This is the Creative Commons 4.0 Attribution International license.
Legal documents are completely opaque to me, so the best answer I can give you is "feel free to use it as long as it doesn't violate the license"

**Comment by Mouvedia** [comment]
The project should provide an official badge.
see badgen/badgen-icons#7

**Comment by villesau** [comment]
@Mouvedia why would we need a badge?
