### ISSUE TITLE
[react-loadable] Missing type annotation for TProps

### ISSUE THREAD

**Issue by Eugene-Musika** [flow-typed/flow-typed#3095]
React-loadable@5.5.0
flow-bin@0.91.0
flow-typed@2.5.1

Related to [flow-bin release 0.85.0](https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8)

![image](https://user-images.githubusercontent.com/19905407/51672090-47857580-1fd3-11e9-9bcc-57aa134763da.png)

**Comment by aurbano** [comment]
@Eugene-Musika I've found that if you pass the prop types it works:

```js
// import ...

import type { Props } from './';

export default Loadable<Props>({
  loader: () => import('./'),
  loading: PlaceholderComponent,
});
```

Where in `./index.js` you have an `export type Props = {...};`

**Comment by pascalduez** [comment]
Yes, Flow is unable to infer the component props from `import('./index')`.  
How's that file looking?  
But as @aurbano suggested the easiest solution is to explicitly pass the `TProps` generic: `Loadable<Props>`.

**Comment by Eugene-Musika** [comment]
Thanks for advices. It works now
