### ISSUE TITLE
How to publish typing with multiple files?

### ISSUE THREAD

**Issue by goodmind** [flow-typed/flow-typed#3103]
Is it possible to publish typings with multiple files?
Currently I use 

```
module.name_mapper='^browser-headers\(.*\)$' -> '<PROJECT_ROOT>/flow/browser-headers\1'
```

for custom typings

and folder looks like this

![image](https://user-images.githubusercontent.com/3275424/51869585-dba86180-2372-11e9-9313-d8b113665fae.png)

**Comment by AndrewSouthpaw** [comment]
Anything you put into the `flow-typed` folder gets magically loaded into flow, is that what you're asking about?

<img width="451" alt="transparentclassroom____projects_transparentclassroom__-_____frontend_src_modules_events_selectors_js__transparentclassroom_" src="https://user-images.githubusercontent.com/5187404/51996520-2d83e100-2472-11e9-86c8-020dfaa72885.png">
