### ISSUE TITLE
[redux-saga] `EventChannel<T>` not accepted by effects expecting `Channel<T>`

### ISSUE THREAD

**Issue by superguineapig** [flow-typed/flow-typed#3111]
### Versions
- flow@0.78.0
- redux-saga@1.0.0
- flow-typed libdef: redux-saga_v1.x.x

Hello, I recently upgraded to 1.x and am now encountering some (flow) errors with my effect channels.

Here's a faux-example setup:

```javascript
import { take } from 'redux-saga/effects';
import { eventChannel } from 'redux-saga';
import type { EventChannel } from 'redux-saga';

type SomeEvent = { ... }; 

const evtChan: EventChannel<SomeEvent> = eventChannel( ... );

function* someSaga() {
   yield take(evtChan); // <-- FLOW ERROR HERE for 'take'
}
```
where the error is:

> Cannot call `take` because property `put` is missing in `EventChannel` [1] but exists in `Channel` [2] in type argument `C`.
[1]: ...my code...
[2]: flow-typed/npm/redux-saga_v1.x.x.js:1429

Simply using `Channel<T>` in place of `EventChannel<T>` is not an option since `eventChannel` factory returns a strict `EventChannel<T>`.

Looking in the libdef, it seems that `EventChannel<T>` is not used anywhere other than its definition and in the return type for `eventChannel`.

Though I may just be using the types improperly to begin with. Anyone have thoughts or suggestions on this issue?

Thanks for reading!

**Comment by villesau** [comment]
ping @retyui as an author of saga libdefs 👆

**Comment by villesau** [comment]
Fixed, thanks for @retyui!

**Comment by superguineapig** [comment]
Thanks all! Fix works great.
