### ISSUE TITLE
[reselect] InputSelector is not an object error with Flow 0.92.1

### ISSUE THREAD

**Issue by jedwards1211** [flow-typed/flow-typed#3127]
Unfortunately in Flow 0.92.1, I get the following error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/reselect_v3.x.x.js:11:7

InputSelector [1] is not an object.

      8│     (state: TState, props: TProps, ...rest: any[]) => TResult
      9│
     10│   declare type OutputSelector<-TState, TProps, TResult> =
 [1] 11│     & InputSelector<TState, TProps, TResult>
     12│     & {
     13│       recomputations(): number,
     14│       resetRecomputations(): number,



Found 1 error
```

**Comment by Tasemu** [comment]
+1

**Comment by voronindenis** [comment]
+1

**Comment by voronindenis** [comment]
This error occurs when a createStructuredSelector is wrapped in an unnamed function. For example:
`const mapStateToProps = (state, { something }) => createStructuredSelector({
    otherSomething: createGetSomethingSelector({ something }),
})`

**Comment by Tasemu** [comment]
> This error occurs when a createStructuredSelector is wrapped in an unnamed function. For example:
> 
> ```js
> const mapStateToProps = (state, { something }) => createStructuredSelector({
>     otherSomething: createGetSomethingSelector({ something }),
> })
> ```

I'm getting this and am not using `createStructuredSelector` anywhere, nor am i using reselect...

**Comment by augusto-altman** [comment]
Hello guys,

I had the same issue and I fixed it by redefining the type `OutputSelector` in the file `flow-typed/npm/reselect_v4.x.x.js` like this:
`  
declare type OutputSelector<-TState, TProps, TResult> = {|
    (state: TState, props: TProps, ...rest: any[]): TResult,
    recomputations(): number,
    resetRecomputations(): number,
    resultFunc(...args: any[]): TResult,
  |}
`
The previous definition was using type intersections and I replaced that with Flow's [calleable objects](https://flow.org/en/docs/types/functions/#toc-callable-objects). It works and as far as I understand it achieves a more accurate typing.
![image](https://user-images.githubusercontent.com/7969511/73792915-32f4d380-480a-11ea-86d3-c1a93cc213f5.png)

**Comment by DmitryGonchar** [comment]
@augusto-altman Thanks a lot for the fix!) Do you think it should also be applied for the `reselect_v3` types?
