### ISSUE TITLE
Next libdef `http$IncomingMessage` error

### ISSUE THREAD

**Issue by amypellegrini** [flow-typed/flow-typed#3171]
I added the libdef for Next, but when I run flow I see this weird error:

    Cannot use  `http$IncomingMessage` [1]  without 0-1 type arguments.

Any ideas on why this is happening and how to fix it?

Thanks!

**Comment by pascalduez** [comment]
Hi @amypellegrini ,

this will need to be updated to `http$IncomingMessage<>`.
See facebook/flow#7215

Would you like to open a PR? 

Some related PRs:
https://github.com/flow-typed/flow-typed/pull/3166   
https://github.com/flow-typed/flow-typed/pull/3164  
https://github.com/flow-typed/flow-typed/pull/3168
