### ISSUE TITLE
Axios definitions errors after Flow v0.93.x

### ISSUE THREAD

**Issue by julianguyen** [flow-typed/flow-typed#3184]
When running flow I'm getting the following error from flow-typed:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/axios_v0.18.x.js:80:14

Cannot use http$ClientRequest [1] without 0-1 type arguments.

     flow-typed/npm/axios_v0.18.x.js
       77│     headers?: Object;
       78│     status: number;
       79│     statusText: string;
       80│     request: http$ClientRequest | XMLHttpRequest;
       81│   }
       82│   declare type $AxiosXHR<T,R = T> = AxiosXHR<T,R>;
       83│   declare type AxiosInterceptorIdent = number;

     /private/tmp/flow/flowlib_2ad8204c/node.js
 [1] 1297│ declare class http$ClientRequest<+SocketT = net$Socket> extends stream$Writable {
```

I tried placing `.*/flow-typed/.*` under the ignore section of `.flowconfig` but no luck :/

**Comment by pascalduez** [comment]
Hi @julianguyen, 

this will need to be updated to `http$ClientRequest<>`.
See facebook/flow#7215

Would you like to open a PR? 

Some related PRs:
https://github.com/flow-typed/flow-typed/pull/3172
https://github.com/flow-typed/flow-typed/pull/3166   
https://github.com/flow-typed/flow-typed/pull/3164  
https://github.com/flow-typed/flow-typed/pull/3168

**Comment by julianguyen** [comment]
Sure I can open up a PR! Thanks!
