### ISSUE TITLE
`flow-typed install` has warning about "before-after-hook"

### ISSUE THREAD

**Issue by kaiyoma** [flow-typed/flow-typed#3199]
This may have just started with version 0.94.0 of flow-bin.

```
$ flow-typed install
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
```

**Comment by nnennajohn** [comment]
Any status on this? Getting the same thing.

**Comment by mpatel3** [comment]
Facing similar issue.

**Comment by oshalygin** [comment]
Facing the same issue anyone have any insight?

**Comment by nataly-chobat** [comment]
facing the same, any luck on this?

**Comment by pascalduez** [comment]
We will look into it, please be patient, it's just a warning after all :wink:

**Comment by LeeCheneler** [comment]
I've started getting this message and now no packages will install:

```sh
flow-typed install react@16
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
• Searching for 1 libdefs...
```

Any other info I can provide?

**Comment by pascalduez** [comment]
@LeeCheneler This is not related. 
There's no `react` definitions in `flow-typed`, React is typed in Flow core.  

Granted the CLI output should be more meaningful in this case...

**Comment by yutingkuang** [comment]
same issue. did anyone solve it?

**Comment by pascalduez** [comment]
Should be fixed as of `flow-typed@3.x`.
