### ISSUE TITLE
Koa: how to extend context?

### ISSUE THREAD

**Issue by indeyets** [flow-typed/flow-typed#3212]
Koa's middlewares add new fields to context sometimes. Is there canonical way of representing this in a type-safe manner?

I can do this dynamically via refinements (checking that property is set and that it is an `instanceof` proper class), but it would be much nicer if I could specify that `app.use(someMiddleware)` changes app's context and further middlewares get this new context.

Another option would be to just declare presence of additional fields on the level of middleware, but I'm not sure if that is possible. My naive attempts at this failed with loud errors

Here's what I tried:

```
/* @flow */
import type { Context } from "koa";
import type Redis from "ioredis";


export type AppContext = {
  ...Context,
  dbs: {
    redis: Redis
  }
}
```

```
async function health(ctx: AppContext, next: () => Promise<void>) {…}

app.use(addRedis);
app.use(health);  // uses `ctx.dbs.redis` defined by `addRedis` above
```

and here are the errors:

```
Cannot call app.use with health bound to fn because:
 • property inspect is read-only in Context [1] but writable in AppContext [2] in the first argument.
 • property toJSON is read-only in Context [1] but writable in AppContext [2] in the first argument.
 • undefined [3] is incompatible with function type [4] in property accepts of the first argument.
 • undefined [3] is incompatible with function type [5] in property accepts of the first argument.
 • undefined [3] is incompatible with function type [6] in property accepts of the first argument.
 • undefined [7] is incompatible with function type [8] in property acceptsCharsets of the first argument.
 • undefined [7] is incompatible with function type [9] in property acceptsCharsets of the first argument.
 • undefined [7] is incompatible with function type [10] in property acceptsCharsets of the first argument.
 • undefined [11] is incompatible with function type [12] in property acceptsEncodings of the first argument.
 • undefined [11] is incompatible with function type [13] in property acceptsEncodings of the first argument.
 • undefined [11] is incompatible with function type [14] in property acceptsEncodings of the first argument.
… (more of these)
```

**Comment by indeyets** [comment]
@HsuTing how do you solve cases like this? (I noticed you're author of current koa type-definition)

**Comment by HsuTing** [comment]
@indeyets I just modify the `koa` type to support the new flow version. I just copy the files from the previous files. I had tried to use your example. I think we should modify type to support adding the new value in koa context. It should be used like this:
```js
app.use((ctx: Context & { radius: Redis }, next: () => Promise<void>)) => {
  ...
});
```

**Comment by indeyets** [comment]
@HsuTing that was my first thought, but now I start to wonder if Koa app should be the generic type over Context.

kinda like:

```
declare class Application <T: Context> extends events$EventEmitter {
  context: T,
  …
}
```

and then do it like:

```
declare type CustomContext = {
  ...Context,
  dbs: {
    redis: Redis,
  }
};

const app = new Koa<CustomContext>();
```

**Comment by indeyets** [comment]
I'm a bit in the dead-end myself. posted SO question https://stackoverflow.com/questions/55226620/self-referential-generic-types-in-flowtype

**Comment by indeyets** [comment]
Just for the reference: that's how definitelytyped does this. makes sense! https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L434-L439

**Comment by HsuTing** [comment]
I had tried to modify like `definitlyTyped`, but the behavior is different between `flow` and `typescript` in [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts#L500). This make flow type checking have some problem.

```js
// @flow
class Application<C> extends events$EventEmitter {
  ...
  use(fn: Middleware<C>): this; // I had tried to use this, but got some errors.
}

class Application extends events$EventEmitter {
  ...
  use<C>(fn: Middleware<C>): this; // In flow, this can not set default
}
```

**Comment by HsuTing** [comment]
I had tried my best to find the good [solution](#3220 ). If you have any idea, tell my please.
