### ISSUE TITLE
[sequelize] should use commonjs export format, not ES Module

### ISSUE THREAD

**Issue by zeorin** [flow-typed/flow-typed#3237]
Sequelize uses commonjs export format.
The libdef here uses the ES Module format.

Importing as follows:
```
const Sequelize = require('sequelize');
```
Doesn't work in Flow (though the code runs just fine), you have to import as:
```
const Sequelize = require('sequelize').default;
```
Luckily, Sequelize manually added a `default` prop to their `module.exports`, so the 2nd version works.

However, it'd be better if the types were congruent with the actual export format.

**Comment by retyui** [comment]
@zeorin 

We can't mix two syntaxes `ES`  and `commonjs` modules
Flow.js imposes [restrictions](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-commonjs-module)

> CommonJS modules have a **single value** that is exported (the `module.exports` value).

**Comment by zeorin** [comment]
I'm not suggesting that we mix the export formats. Just that we pick the one that the actual package uses, so that there isn't a mismatch, that still allows one to export everything the actual JS package exports, the same way.

Based on my reading of other libdefs, choosing to use the CommonJS export format does not preclude using `declare export type`.

Clearly, trying to use Sequelize as per their docs:
```
const Sequelize = require('sequelize');
```
and not having this work for Flow despite having the libdef installed, is not what we want.

> CommonJS modules have a single value that is exported (the module.exports value).

Sequelize _uses a CommonJS_ export, therefore it exports a single value. Surely we can do the same? I don't see a problem.

**Comment by retyui** [comment]
> Sequelize uses a CommonJS export, therefore it exports a single value. Surely we can do the same? I don't see a problem.

Now we export a lot of types:
https://github.com/flow-typed/flow-typed/blob/890709941d934f31381dd646747fd1f6d2200fa0/definitions/npm/sequelize_v4.x.x/flow_v0.42.x-/test_sequelize.js#L4-L35

With commonjs modules it is impossible to do:


![image](https://user-images.githubusercontent.com/4661784/56644661-cb0f3b00-6684-11e9-899b-68d27dcb70f4.png)

**Comment by retyui** [comment]
Fixed in: https://github.com/flow-typed/flow-typed/pull/3276

**Comment by retyui** [comment]
I was mistaken and eventually found a solution

**Comment by jedwards1211** [comment]
sorry, this was not a solution, it broke working code that imports via ES6

**Comment by jedwards1211** [comment]
I know Sequelize uses CommonJS exports.  But, it's equally possible to `import {Model} from 'sequelize'` or
```js
import Sequelize from 'sequelize'
const {Model} = Sequelize
```
Since this code works at runtime, it should not cause flow errors (regardless of the fact that sequelize exports using commonjs).  But is there any way to use CommonJS flow type defs and make these import statements work with flow?

**Comment by jedwards1211** [comment]
@zeorin I've been experimenting locally but I don't see any way to support `require('sequelize')` without breaking `import {Model} from 'sequelize'` etc.

I think Flow just doesn't have a way to properly model both CommonJS and ES6 imports working.

I think using CommonJS is the wrong tradeoff.  If the only problem on the CommonJS side is having to add `.default`, whereas the ES6 side has tons of errors like `import {Association, Model, Transaction, ValidationError} from 'sequelize'` etc all not working, to me using ES6 declarations is the better tradeoff.

**Comment by retyui** [comment]
> I think Flow just doesn't have a way to properly model both CommonJS and ES6 imports working.

you can create an example and find out flow.js has this opportunity or no

**Comment by jedwards1211** [comment]
@retyui I added an example to my comment above

**Comment by retyui** [comment]
@jedwards1211 
I'm talking about another example
https://github.com/flow-typed/flow-typed/pull/3276#issuecomment-490210256

**Comment by jedwards1211** [comment]
gotcha, I didn't see a full-blow solution in your example there either?

**Comment by jedwards1211** [comment]
@zeorin another reason I think using ES module declarations is a better tradeoff -- since a transpiler is required to strip flow type annotations (unless you put annotations in comments), most devs are probably already able to use `import` statements, and probably prefer to since they look better next to `import type` statements, and they can mix in `import Sequelize, {type FindOptions} from 'sequelize'`.
