### ISSUE TITLE
Typing global variables

### ISSUE THREAD

**Issue by miguel-guedes** [flow-typed/flow-typed#3241]
I'm attempting to add flow typing support to a node application that extends the `global` object. This application is part of a monorepo containing multiple packages, some of which also node applications that extend the `global` object, and other packages are browser applications. 

If I declare a var (via `declare var`) at the top of each module that references the `global` object, I get the desired typing support but this is far from ideal as each module would require such a declaration. 

Is there a way of declaring typing for global variables on a per-package basis using module definitions? I have had a good read of the relevant [documentation](section) but wasn't able to produce the desired effect.

Naive example: 
*pkgA/app.js*
```js
export default class App { 
  executeMethod(arg1: string, arg2: number): void {}
}
```

*pkgA/main.js*
```js
import App from './app';
global.app = new App()
```

*pkgB/worker.js*
```js
global.app.executeMethod(with, typing);
```

**Comment by AndrewSouthpaw** [comment]
My understanding is that `global` is typed as `any` so you could in theory type cast it to a `GlobalT` that is your definition and then use it in places.

**Comment by miguel-guedes** [comment]
Thanks for your comment, @AndrewSouthpaw .  I'm closing this issue as I don't actually think this is related to flow-typed and, besides, I achieved what I was after by reworking the design such that it doesn't use `global` at all. Apologies for the noise & thanks again!
