### ISSUE TITLE
[Question] does flowtype allow changing definitions repository?

### ISSUE THREAD

**Issue by tirthaguha** [flow-typed/flow-typed#3257]
I've created few ES6 based private libs, and flowtype is widely used in our ecosystem. I need the definitions of these to be fetched alongside the definitions which are there in this repo. For that I need to change the definitions repo URL. is that a possibility?

**Comment by villesau** [comment]
Do you have a private NPM repository? I'd recommend to push the definitions there and defining the folder to flow config:

```
[libs]
node_modules/@your_organization
```
