### ISSUE TITLE
Reach/Router How to type Match 

### ISSUE THREAD

**Issue by zecaptus** [flow-typed/flow-typed#3278]
The type definition is :

    declare export class Match<Params> extends React$Component<{|
      path: string,
      children: (props: {|
        match: null | ({ uri: string, path: string } & Params),
        location: typeof location,
        navigate: NavigateFn,
      |}) => React$Node,
    |}> {}

using Match like this :

    <Match path="/agents/:id">
       {({ match, navigate }) => ( [...] )
    </Match>

here `match` is consider as `null` by flow

if I try something like 

    class MatchAgent extends Match<{id: string}> {}

flow works great, but react crashes cannot call Class as function.

    const MatchAgent: Match<{id:string}> = Match;

this works with react, but not with flow :'(

Is someone know how we can type this with flowjs ?
Thank you

**Comment by retyui** [comment]
https://github.com/facebook/flow/issues/7672

**Comment by retyui** [comment]
`Match` isn't class it is a function!

How can I see in src:
https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/index.js#L466-L488

---

@zoontek when adding types made a mistake)

**Comment by retyui** [comment]
Fixed in https://github.com/flow-typed/flow-typed/pull/3281
