### ISSUE TITLE
[styled-components] : How should we type styled component with props

### ISSUE THREAD

**Issue by TomPradat** [flow-typed/flow-typed#3279]
I'm not able to find a single working example to type styled components using props inside

```js
const Div = styled.div`
    color: ${({ color }) => color};
`;
```

I always get an error saying that color is missing in object type, etc ...

Does anyone have a working example ?

Also i've noticed that the libdef in this repo for `styled-components_v4.x.x.js` is in a subdir called `flow_v0.75.x-`. I'm using flow 0.97 so maybe i have a problem with this too, but flow-typed binary installs me this libdef

**Comment by edahlseng** [comment]
@TomPradat #3228 should fix a lot of the issues you're seeing.

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
