### ISSUE TITLE
[archiver_v2.x.x] Cannot call archiver because a callable signature is missing in module archiver

### ISSUE THREAD

**Issue by richsinn** [flow-typed/flow-typed#3289]
Flow version: 0.95.1
[`archiver` version: 2.0.0](https://github.com/flow-typed/flow-typed/blame/master/definitions/npm/archiver_v2.x.x/flow_v0.54.x-/archiver_v2.x.x.js)

Error message:
```
Cannot call archiver because a callable signature is missing in module archiver [1].

 [1]   6│ const archiver = require('archiver');
           :
     316│         const zip = archiver('zip');
```

Please let me know what other info you need. FWIW, when I manually modified the flow-typed to be a ["common js" module](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-commonjs-module) (i.e. using `declare module.exports`), it seems to work:
```
  // Commenting out `declare export default` syntax and use CommonJS syntax 
  // declare type Vending = {
  //   (format: Format, options?: ArchiverOptions): Archiver,
  //   create(format: string, options?: ArchiverOptions): Archiver,
  //   registerFormat(format: string, module: Function): void
  // };
  //
  // declare export default Archive;

  // This works! 
  declare module.exports: {
    (format: Format, options?: ArchiverOptions): Archiver,
    create(format: string, options?: ArchiverOptions): Archiver,
    registerFormat(format: string, module: Function): void
  }
```

Thank you!

**Comment by pascalduez** [comment]
Hi,

yes, this would need to be converted to a `commonjs` declaration, as the module is a `commonjs` one. 

Some recent examples: #3276 #3267

**Comment by retyui** [comment]
Fixed in https://github.com/flow-typed/flow-typed/pull/3292
