### ISSUE TITLE
Ecosystem state

### ISSUE THREAD

**Issue by retyui** [flow-typed/flow-typed#3298]
Statistics test for each definition:

| Test result | 3 May 2019 (flow 0.86-0.98) | 3 August 2019 (flow 0.95-0.104) |
|---|---|---|
| N/A | 143 | 146 |
| ✔️ | 609 | 1296 |
| ❌ | 87 | [174](https://gist.github.com/retyui/be6470f69ff36a24d0023037f991f184#file-err-md) |
| All libs | 617 | 677 |

* Comparison with [DefinitelyTyped](https://gist.github.com/goodmind/40777b6c32e8cf8533edc27ed7739205)
* Definitions with [fail tests](https://gist.github.com/retyui/be6470f69ff36a24d0023037f991f184#file-err-md)
* Full report [.md](https://gist.github.com/retyui/be6470f69ff36a24d0023037f991f184#file-full-md), [.json](https://gist.github.com/retyui/be6470f69ff36a24d0023037f991f184#file-full-json)

---

How to run a specific library test:
```sh
# node cli/dist/cli.js run-tests <name>
# example:
node cli/dist/cli.js run-tests express_v4.x.x
# or with flow
node cli/dist/cli.js run-tests express_v4.x.x/flow_v0.32.x-v0.92.x
```

**Comment by AndrewSouthpaw** [comment]
Nice work. :

**Comment by retyui** [comment]
It would be great to know the number of downloads for a specific definition.

**Comment by villesau** [comment]
Wow, nice work indeed!

> It would be great to know the number of downloads for a specific definition.

That's not possible with current setup. Once when getting stuff together for moving to NPM, NPM should show stats like any other package.

**Comment by AndrewSouthpaw** [comment]
Leaving this open because I think it's useful. Unless @retyui  you have objections?

**Comment by goodmind** [comment]
Comparison with DefinitelyTyped
https://gist.github.com/goodmind/40777b6c32e8cf8533edc27ed7739205

**Comment by retyui** [comment]
report was updated
