### ISSUE TITLE
Cannot install styled-components v4 libdef

### ISSUE THREAD

**Issue by melissafzhang** [flow-typed/flow-typed#3317]
I'm getting an error trying to install [styled-components@4.x.x](https://github.com/flow-typed/flow-typed/pull/2933/files) with flow v0.85. 

This is the error I'm getting when running `flow-typed install styled-components@4`
```
 Searching for 1 libdefs...
• rebasing flow-typed cache...
ERROR: Unable to rebase the local cache repo. Error rebasing the `master` branch of the following repo:
/Users/melissazhang/.flow-typed/repo

undefined

NOTE: Unable to rebase local cache! If you don't currently have internet connectivity, no worries -- we'll update the local cache the next time you do.

!! No flow@v0.85.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!

Consider using `flow-typed create-stub styled-components@4` to generate an empty libdef that you can fill in.
```

Thanks for the help!

**Comment by pascalduez** [comment]
I can't reproduce, local test with flow-bin@0.85.  
Do you still have the issue @melissafzhang ? 
If so could you provide more details like node version, flow version, flow-types version, etc.
