### ISSUE TITLE
New version needs to be published for projects on babel 7.x

### ISSUE THREAD

**Issue by matthargett** [flow-typed/flow-typed#3323]
Right now, we have to point our package.json at the git repo in order for flow-typed to work with our React Native project we recently upgraded to babel 7. 

Since this causes issues with npm caching and other things, it would be swell if a new version could be published to npm.

Thanks for all your excellent work on this project!

**Comment by retyui** [comment]
We upgraded out react-native project to babel 7  without problems

**Comment by pascalduez** [comment]
Hi @matthargett,

we would need a bit more details and materials to be able to understand your issue, it's really vague.

I don't get what Babel has to do with `flow-typed`, those are pretty distinct tools with not interaction or interdependence so far. Furthermore you usually install the `flow-typed` CLI globally.

**Comment by villesau** [comment]
New version will be released tonight :)

**Comment by GAntoine** [comment]
New version has been release. @matthargett If it does not fix your issue, please open a new Issue with more details.

**Comment by matthargett** [comment]
Thanks!!
