### ISSUE TITLE
Unable to install redux_v4 libdef

### ISSUE THREAD

**Issue by tamias** [flow-typed/flow-typed#3329]
I'm trying to install the libdef for redux v4, but it's not found:

```
$ flow-typed install redux@4.0.1
• Searching for 1 libdefs...
• rebasing flow-typed cache...
!! No flow@v0.84.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!
```

...even though the libdef exists in this repo:

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux_v4.x.x/flow_v0.55.x-0.88.x/redux_v4.x.x.js

**Comment by pascalduez** [comment]
@tamias Should be fixed now. `flow-typed install redux@4`
