### ISSUE TITLE
flow-typed@2.5.1 install --overwrite unknow argument

### ISSUE THREAD

**Issue by BeAce** [flow-typed/flow-typed#3340]
![image](https://user-images.githubusercontent.com/13284978/58090173-3521ee00-7bf9-11e9-8b3b-0860aa67c836.png)

but the wiki

![image](https://user-images.githubusercontent.com/13284978/58090272-70242180-7bf9-11e9-8e66-afdda0df6977.png)

**Comment by vladzhigulsky** [comment]
Facing the same issue. The overwrite options seem to disappear after upgrading to 2.5.2

**Comment by vladzhigulsky** [comment]
I managed to get it working by using `flow-typed update` instead of `flow-typed install -o`

Still strange that it stopped working because both commands are essentially the same.

**Comment by bradennapier** [comment]
Yeah and as an automated script `overwrite` is what we would want to have the same command regardless of updating or installing.

**Comment by villesau** [comment]
@GAntoine this has not been released
