### ISSUE TITLE
[styled-components_v4.x.x] How to type styled components with theme props

### ISSUE THREAD

**Issue by vladzhigulsky** [flow-typed/flow-typed#3352]
I'm using a ThemeProvider with styled components and then in my component I'm doing the following:

```javascript
const Header = styled.header([
  ({ theme }) => css`
    background: ${theme.colours.darkBlue};
    font-family: ${theme.fontFamily.base};
    ...
    ...
  `
]);
```

I get an error saying: 

> Cannot call `styled.header` because  function [1] is incompatible with  string [2] in array element."

I haven't been able to find a clean solution so far.
Does anyone have a working example on how to do it with theme props?

**Comment by davidcarter-me** [comment]
In a similar situation :(

**Comment by Livinstone** [comment]
+1

**Comment by tobilen** [comment]
what do you get when writing
```jsx
const Header = styled('header')`
  background: ${({ theme }) => theme.colours.darkBlue};
  font-family: ${({ theme }) => theme.fontFamily.base};
`
]);
```

**Comment by pascalduez** [comment]
Closing in hope #3228 solves the issue.
