### ISSUE TITLE
Flow-typed install crashes if you have a package installed from a git URL

### ISSUE THREAD

**Issue by noahtallen** [flow-typed/flow-typed#3363]
Here is the crash:
```
UNCAUGHT ERROR: Error: Malformed npm package name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH> but instead got mtwins
    at parsePkgNameVer (/Users/noah.allen/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:295:11)
    at _callee6$ (/Users/noah.allen/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:620:38)
    at tryCatch (/Users/noah.allen/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/noah.allen/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/noah.allen/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/noah.allen/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:56:103)
    at _next (/Users/noah.allen/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:58:194)
    at <anonymous>
```

As you can see, it got "mtwins" instead of what it was expecting. This matches a package I have linked through git: (note, I do have several more dependencies that I did not list here)
```json
  "dependencies": {
    "lottie-react-native": "^2.6.1",
    "rn-tooltip": "git+https://github.com/mtwins/rn-tooltip.git"
  },
```

This happens when running:
-  `flow-typed install lottie-react-native` (a package I recently installed).
- `flow-typed install`

To get around this, I have to:
1. `rm -rf flow-typed`
2. `flow-typed install`. This works successfully, unlike before deleting the folder

**Comment by noahtallen** [comment]
It looks like flow-typed stubs the package, so it goes to `flow-typed/npm/rn-tooltip_vx.x.x.js`, and the top of the file looks like:
```js
// flow-typed signature: 527e6946ef69cf49c131a265251961cb
// flow-typed version: <<STUB>>/rn-tooltip_vgit+https://github.com/mtwins/rn-tooltip.git/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
```

I'm guessing the `install` command is trying to parse part of that, but fails?

**Comment by bz2** [comment]
This is regression the latest minor release - can work around by pinning to the previous version:

```diff
-    "flow-typed": "^2.5.1",
+    "flow-typed": "=2.5.1",
```

**Comment by Stephen2** [comment]
Thanks for confirming @bz2

**Comment by AndrewSouthpaw** [comment]
Interesting. If someone can figure out where that regression was introduced that'd be grand. 😃

**Comment by knu** [comment]
Does this still occur?  I had the same problem and worked around by pinning the version to 2.5.1, but today I gave 2.6.0 a try and flow-typed install went fine without error.  The dependencies in my package.json haven't changed since last I saw the error, except for flow-bin ("^0.102.0" to "^0.103.0").

**Comment by pletcher** [comment]
@knu, I just ran into this issue on 2.6.0. Pinning to 2.5.1 worked for me. It looks like git-based packages are (correctly?) skipping [`npmLibDefs.parsePkgNameVer`](https://github.com/flow-typed/flow-typed/blob/f1c6fe7886dc7124eab7841408e4046e01683358/cli/src/lib/npm/npmLibDefs.js#L210) in 2.5.1, but a quick look through commits around the 2.5.2 release hasn't turned up any obvious culprits for the regression :/

**Comment by kirillDanshin** [comment]
any updates on #3537? that PR fixes this issue.

**Comment by olegatg** [comment]
Still the case with 2.6.1. But 2.5.1 works.

**Comment by kirillDanshin** [comment]
Finally should be good now :)

**Comment by pReya** [comment]
Still happens for me with 2.6.2 :(

**Comment by kirillDanshin** [comment]
Hmmm, we need to do some further investigation. For some reason, it works for me

**Comment by IanVS** [comment]
>For some reason, it works for me

Could it be that you have a flow-typed cache already?  It seems to fail for me when it's rebuilding the cache.  I'm not sure if it's because I was on an old version or because I had a cache, but everything was working fine until I switched to a new laptop.  I can go back and test with my old machine later today if that's helpful.

**Comment by jedwards1211** [comment]
Still happening for me in `flow-typed@3.1.0` when a *transitive* dependency is installed from a git URL

**Comment by jedwards1211** [comment]
Even though there are some things I don't like about DefinitelyTyped, `@types` packages aren't brittle like `flow-typed` is.

**Comment by pascalduez** [comment]
@jedwards1211 Care to open a "fresh" issue?

**Comment by jedwards1211** [comment]
Should this be reopened though?  Several other commenters are still having this issue

**Comment by jedwards1211** [comment]
@pascalduez I confirmed that I have the code in #3537, it's not fixing my issue, and I figured out exactly what's going wrong.

Like @noahtallen, I have a stub sitting in `flow-typed` with this at the top:

```js
// flow-typed version: <<STUB>>/babel-plugin-transform-import-commonjs_vhttps://github.com/jedwards1211/babel-plugin-transform-import-commonjs#patch-1-built/flow_v0.59.0
```
Here's a better stack trace than OP:
```
andy@Andys-MBP-2:clarity (observable-queries) $ flow-typed install zen-observable
Found delay listed twice in package.json!
• Searching for 1 libdefs...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: Malformed npm package name! Expected the name to be formatted as <PKGNAME>_v<MAJOR>.<MINOR>.<PATCH> but instead got jedwards1211
    at parsePkgNameVer (/Users/andy/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:179:11)
    at /Users/andy/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:383:30
    at async Promise.all (index 28)
    at async getInstalledNpmLibDefs (/Users/andy/.config/yarn/global/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:345:5)
    at async installNpmLibDefs (/Users/andy/.config/yarn/global/node_modules/flow-typed/dist/commands/install.js:297:35)
    at async Object.run (/Users/andy/.config/yarn/global/node_modules/flow-typed/dist/commands/install.js:149:27)
```

`getInstalledNpmLibDefs` does this:

```js
            const signedCodeVer = getSignedCodeVersion(fileContent);
            if (signedCodeVer === null) {
              return;
            }
            const matches = signedCodeVer.match(
              /([^\/]+)\/(@[^\/]+\/)?([^\/]+)\/([^\/]+)/,
            );
            if (matches == null) {
              return;
            }

            if (matches[1] === '<<STUB>>') {
              installedLibDefs.set(terseFilePath, {
                kind: 'Stub',
                name: matches[2],
              });
              return;
            }
```
But trying this out manually shows that `<<STUB>>` doesn't get matched:
```
> var ver = '<<STUB>>/babel-plugin-transform-import-commonjs_vhttps://github.com/jedwards1211/babel-plugin-transform-import-commonjs#patch-1-built/flow_v0.59.0'
undefined
> var matches = ver.match( /([^\/]+)\/(@[^\/]+\/)?([^\/]+)\/([^\/]+)/)
undefined
> matches
[
  'github.com/jedwards1211/babel-plugin-transform-import-commonjs#patch-1-built',
  'github.com',
  undefined,
  'jedwards1211',
  'babel-plugin-transform-import-commonjs#patch-1-built',
  index: 57,
  input: '<<STUB>>/babel-plugin-transform-import-commonjs_vhttps://github.com/jedwards1211/babel-plugin-transform-import-commonjs#patch-1-built/flow_v0.59.0',
  groups: undefined
]
```
Better to just use `signedCodeVer.startsWith('<<STUB>>')` here, and also, **we must make it tolerate/repair absolutely any bad preexisting version string.**

**Comment by Brianzchen** [comment]
1. Added to dependencies
```
"rn-tooltip": "git+https://github.com/mtwins/rn-tooltip.git"
```
2. Ran `yarn`
3. Ran `flow-typed install`
4. Observed stub installed with declare modules correctly

@jedwards1211 Am I missing something here that still need fixing or can this be closed?
