### ISSUE TITLE
Desire to contribute

### ISSUE THREAD

**Issue by dantesolis** [flow-typed/flow-typed#3366]
Hello there, lately I've been using a lot of `flow` and `flow-typed` on my projects,  I would like to contribute, but don't know how or where to start; which issues to tackle, etc.

Thanks.

**Comment by goodmind** [comment]
https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md

I think just contribute libraries that doesn't have types?

**Comment by dantesolis** [comment]
@goodmind no, I think that's pretty much it :) Thanks.

**Comment by pascalduez** [comment]
> I could create flow type definitions for 1 of those libs ?

That's a good start thanks! 
Maybe prioritise packages that "make more sense" typing, for instance `@babel/preset-flow` and  `@babel/cli` not much, while `inquirer` definitely (this one exists and needs updates). 

There are requests here tracked under the ["request" tag](https://github.com/flow-typed/flow-typed/issues?q=is%3Aissue+is%3Aopen+label%3Arequest).

Also might want to look at those missing in the top most used npm packages. 
https://www.npmjs.com/browse/depended  
https://gist.github.com/anvaka/8e8fa57c7ee1350e3491

**Comment by dantesolis** [comment]
thanks @pascalduez I'll begin with `inquirer` using the lib at the moment :)

**Comment by AndrewSouthpaw** [comment]
Calling this closed?

**Comment by Mouvedia** [comment]
check #3298

**Comment by dantesolis** [comment]
@AndrewSouthpaw  yes we could close this issue, since it was a question and I think it @pascalduez helped me out with it. @Mouvedia  Will check that PR. 

To give a heads up on my commitment. At the moment I'm in the process of organizing  meetup event **25/06** as soon as that's done I'll be tackling this issue and other Open Source contributions commitments I have. 

Thanks for the patience though.

**Comment by dantesolis** [comment]
@Mouvedia so I have started writing definitions for the `inquirer` package, however is it possible to already send a PR with what I have already to see if I'm going on the right direction, or does the lib definition needs to be fully implemented before I submit the PR. 

Thanks

**Comment by pascalduez** [comment]
@dantesolis Mark the PR as "WIP" so you can get early feedback if you wish.
