### ISSUE TITLE
Move FlowDefinitelyTyped to flow-typed organization

### ISSUE THREAD

**Issue by goodmind** [flow-typed/flow-typed#3386]
Would you accept my repository [FlowDefinitelyTyped](https://github.com/goodmind/FlowDefinitelyTyped) into flow-typed organization?

Opposed to this repository this would be repository of _horrible quality_ definitions (autogenerated with [flowgen](https://github.com/joarwilk/flowgen) from DT), that can be used as blueprints for contributing to this repository

/cc @villesau @GAntoine @AndrewSouthpaw

**Comment by villesau** [comment]
I think that's an interesting idea! Maybe we could build some tooling around it to make picking the libdef easier? Something like "We couldn't find first class libdefs for you, but looks like there is DefinitelyTyped definition. Would you want to import transformed version of it for basis of a new libdef? Yes/No"

**Comment by goodmind** [comment]
@villesau it would be perfect for create-stub

**Comment by AndrewSouthpaw** [comment]
So are you envisioning this repo as containing TS definitions that we then convert on the fly from the CLI to flow when we can't find the libdef in flow-typed?

**Comment by AndrewSouthpaw** [comment]
If so, is there a reason we wouldn't want to pull directly from the DefinitelyTyped repo?

**Comment by goodmind** [comment]
Now I don't think we need repo actually

**Comment by villesau** [comment]
Yeah on-the-fly transformation sounds a bit more lightweight. But the CLI should communicate super clearly that it's machine transformation and TS->Flow might not be accurate and manual reviewing is required.

**Comment by AndrewSouthpaw** [comment]
Cool. :) Closing this issue.
