### ISSUE TITLE
[CLI] Having a dedicated command to show up local environment information

### ISSUE THREAD

**Issue by jamesgeorge007** [flow-typed/flow-typed#3413]
## Proposed API

`flow-typed info`

Check out [envinfo](https://www.npmjs.com/package/envinfo)

**Comment by AndrewSouthpaw** [comment]
Sounds good, PR away!

**Comment by goodmind** [comment]
Why this is needed in flow-typed?

**Comment by jamesgeorge007** [comment]
@goodmind It might prove useful while submitting bug reports, where information regarding the local environment is required.

**Comment by pascalduez** [comment]
`npx envinfo` ?

Looks a bit like bloating the CLI needlessly. 

/cc @villesau @GAntoine as well.
