### ISSUE TITLE
expo-constants flow-typed does not include releaseChannel

### ISSUE THREAD

**Issue by WillzMu** [flow-typed/flow-typed#3441]
in expo-constants_v5.x.x.js, releaseChannel is not included in AppManifest.

**Comment by retyui** [comment]
@WillzMu 
I look on docs https://docs.expo.io/versions/latest/sdk/constants/
but can't find any mentions about `releaseChannel`

**Comment by retyui** [comment]
Fixed in https://github.com/flow-typed/flow-typed/pull/3449
