### ISSUE TITLE
[react-redux_v7.x.x] Flow cannot import useSelector, useDispatch

### ISSUE THREAD

**Issue by retyui** [flow-typed/flow-typed#3452]
The problem: 
```js
import {
  useDispatch, // error
  useSelector, // error
} from 'react-redux';
```

via: https://github.com/flow-typed/flow-typed/pull/3440

Is it legal to copy old libdefs without checking them with reality?

Docs: https://github.com/reduxjs/react-redux/blob/master/docs/api/hooks.md

**Comment by goodmind** [comment]
> Doesn't address some of the new hooks support, just wanted to get something out there to support the majority of use cases. Can be refined later.

**Comment by AndrewSouthpaw** [comment]
Thanks @goodmind.

Yeah I figured it was better to get something out. I don't have time to add hooks support, someone else is welcome to do so.

**Comment by ssorallen** [comment]
I added types in #3461, please take a look if any of you get a chance.
