### ISSUE TITLE
[react-navigation@3.x.x]

### ISSUE THREAD

**Issue by aamalric** [flow-typed/flow-typed#3460]
Seems like the definition of  type NavigationScreenProp for push function is no longer optionnal.
Looking at https://github.com/react-navigation/react-navigation/blob/master/typescript/react-navigation.d.ts#L743
```
    push: (
      routeName: string,
      params?: NavigationParams,
      action?: NavigationNavigateAction
    ) => boolean;
```

And flow-typed definition is https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/%40react-navigation/core_v3.x.x/flow_v0.60.x-v0.91.x/core_v3.x.x.js#L531

```
    push?: (
      routeName: string,
      params?: NavigationParams,
      action?: NavigationNavigateAction
    ) => boolean,
```

**Comment by pascalduez** [comment]
Hi @aamalric,

the definitions in `flow-typed` are "just" a copy of [the ones in `react-navigation` core](https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L638). 
So if a change is needed it would need to be applied there previously.

**Comment by aamalric** [comment]
Hi @pascalduez  Thanks for clarifications
