### ISSUE TITLE
[lodash_v4.x.x] #flow definition throws error

### ISSUE THREAD

**Issue by bdhowald** [flow-typed/flow-typed#3463]
**Do you want to request a *feature* or report a *bug*?**

I am reporting a bug that is possibly linked to a [commit merged yesterday](https://github.com/flow-typed/flow-typed/commit/f125eacb942c4cc495330643a890c97ed6cc460d#diff-a986497c6415236202a140ff65ef7c06).

It appears that [someone else may be getting the same error](https://github.com/flow-typed/flow-typed/commit/f125eacb942c4cc495330643a890c97ed6cc460d#commitcomment-34335565) with another function that received a second type definition in the same commit.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using lodash#flow in the following manner (contrived example):

`_.flow([_.add, _.add])`

throws the following error:

`Cannot call flow because array literal [1] is incompatible with function type [2] in array element.`

because it fails the following type definition added yesterday:

`flow: $ComposeReverse & ((...funcs: Array<Function>) => Function);`

in addition to the existing type definition:

`flow: $ComposeReverse & ((funcs: Array<Function>) => Function);`

**What is the expected behavior?**

That this would continue to not throw an error.

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.

```bash
  System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 740.19 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 10.14. - /usr/bin/gcc
    Git: 2.21.0 - /usr/local/bin/git
  Servers:
    Apache: 2.4.34 - /usr/sbin/apachectl
  Virtualization:
    Docker: 18.09.2 - /usr/local/bin/docker
  IDEs:
    Atom: 1.38.2
    Emacs: 22.1.1 - /usr/bin/emacs
    Nano: 2.0.6 - /usr/bin/nano
    Sublime Text: Build 3176
    Vim: 8.0 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_202 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 3.6.5 - /Users/brianhowald/.pyenv/shims/python
    Ruby: 2.6.0 - /Users/brianhowald/.rvm/rubies/ruby-2.6.0/bin/ruby
  Databases:
    PostgreSQL: 11.3 - /usr/local/bin/postgres
    SQLite: 3.24.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 75.0.3770.142
    Safari: 12.1.1
```

**Comment by pascalduez** [comment]
Also see 3473

**Comment by pascalduez** [comment]
Ping @fbontin

**Comment by JavierLaguna** [comment]
I have this issue

**Comment by pascalduez** [comment]
I reverted the commit  causing issues.
