### ISSUE TITLE
[CI] failed after merge the last PR

### ISSUE THREAD

**Issue by retyui** [flow-typed/flow-typed#3484]
When I merge the master branch with this changes:

> Explicit inexact object syntax #3467

[CI failed](https://travis-ci.org/flow-typed/flow-typed/builds/566313482?utm_source=github_status&utm_medium=notification) with next error: 

```sh
$ eslint **/**/test_* --quiet

/home/i/open-source/flow-typed/definitions/npm/rxjs_v5.0.x/test_rxjs.js
  62:56  error  Parsing error: Unexpected token

  60 | (dualNumbers.combineAll((a, b) => `${a}-${b}`): Observable<string>);
  61 | 
> 62 | const combined: Observable<{ n: number, s: string, ... }> = Observable.combineLatest(
     |                                                        ^
  63 |   numbers,
  64 |   strings,
  65 |   (n, s) => ({ n, s })

✖ 1 problem (1 error, 0 warnings)
```

**Comment by villesau** [comment]
Thanks @retyui and welcome back! :)

yeah I noticed this already when merging the PR but thought it's such large PR that this can be fixed after merging. Thanks for writing the fix!! I'll go it trough and merge it latest tomorrow: We do not merge anything today in case we need to revert the mega PR. It has so huge conflict surface that reverting would get too difficult in case of errors. Thus, I'll try to get your PR in tomorrow :)

**Comment by pascalduez** [comment]
Won't we run into the fact that ESLint currently not support the inexact object syntax? 
See https://github.com/babel/babel-eslint/issues/734

**Comment by retyui** [comment]
@pascalduez 
I updated eslint* modules to the latest version and errors(inexact object syntax) disappeared
