### ISSUE TITLE
`SyntaxError: Unexpected token` for prettier definition

### ISSUE THREAD

**Issue by NigelGreenway** [flow-typed/flow-typed#3486]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Prettier linting throws an error on recent `flow-typed update`

script command: `  "qa::lint": "eslint --ext .jsx --ext .js src tests"`

```js
SyntaxError: Unexpected token (5:55)
  3 |
  4 | declare module "prettier" {
> 5 |   declare export type AST = { [key: string]: any, ... };
    |                                                       ^
  6 |   declare export type Doc = {
  7 |     [key: string]: any,
  8 |     ...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Run above script cmd and it throws and error.

**What is the expected behavior?**
Linting passes without errors

**Local Environment Information**
https://gist.github.com/NigelGreenway/206fbe6b7c0e3b0004e6edcb9876a054

**Comment by NigelGreenway** [comment]
I've just updated `prettier` from `1.13.5` to `1.18.2` and that's fixed _that_ issue above but I'm now getting this:

```js
 1817 |     (<A, B, C>(fn1: (b: B) => C, fn2: (a: A) => B, x: A) => C);
  1818 |
> 1819 |   declare function of<T>(x: T): Array<T>;
       |                      ^
  1820 |
  1821 |   declare function once<A, B, T: (...args: Array<A>) => B>(fn: T): T;
  1822 |
```

**Comment by NigelGreenway** [comment]
Okay, it's Ramda & I've updated that and running `flow-typed update` again...

**Comment by NigelGreenway** [comment]
After updating both, I'm still getting the [second error](https://github.com/flow-typed/flow-typed/issues/3486#issuecomment-517450236) 😞

**Comment by retyui** [comment]
@NigelGreenway 

Add to you `.eslintignore`

```
flow-typed/
```

**Comment by pascalduez** [comment]
Hi @NigelGreenway,

as @retyui said, you should definitely not lint the `flow-typed` directory.
