### ISSUE TITLE
Pass flag to `flow-typed update` to ignore passed args for compat with husky/lint-staged

### ISSUE THREAD

**Issue by jasonbarry** [flow-typed/flow-typed#3490]
I want to run `flow-typed` as a pre-commit hook so that newly added dependencies fetch their type definitions and add to git automatically. 

I'm using [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) to achieve this. The problem is that lint-staged passes a list of files as args to the task specified. 

> The concept of lint-staged is to run configured linter (or other) tasks on files that are staged in git. lint-staged will always pass a list of all staged files to the task, and ignoring any files should be configured in the task itself.

Since the task here is `flow-typed update`, and the file in git's staging that matches is yarn.lock, flow-typed thinks that `yarn.lock` is the name of a dependency and tries to fetch it from npm. 

A solution could be to have a flag that would ignore any arguments passed to `flow update`, i.e. `flow update --flag dep1 dep2 dep3` would be the same as `flow update`.

Here's some of my setup: 

**package.json**
```json
"husky": {
  "hooks": {
    "pre-commit": "lint-staged",
  }
},
"lint-staged": {
  "**/*.{js,jsx}": [
    "yarn prettier",
    "git add"
  ],
  "yarn.lock": [
    "flow-typed update",
    "git add"
  ]
}
```

**terminal output**
```
yarn run v1.17.3
$ flow-typed update /path/to/app/yarn.lock
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Package not found from package.json.
Please specify version for the package in the format of `foo@1.2.3`
error Command failed with exit code 1.
husky > pre-commit hook failed (add --no-verify to bypass)
```

**Comment by mrm007** [comment]
Try this:

```
"lint-staged": {
  "yarn.lock": [
    "bash -c 'flow-typed update'",
    "git add"
  ]
}
```

See https://github.com/okonet/lint-staged/issues/174#issuecomment-461423707 for a longer explanation.

**Comment by Brianzchen** [comment]
As there's no further discussion the solution above seems good enough I'll close the issue.
