### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by Hybueno09** [flow-typed/flow-typed#3491]
**Do you want to request a *feature* or report a *bug*?**
`bug`

**What is the current behavior?**
`JavaScript heap out of memory`

**If the current behavior is a bug, please provide the steps to reproduce.**

when I run `yarn install`, it throwed error for `JavaScript heap out of memory`.After I delete about six dependencies,i runed steps followed below:

- run `yarn cache clean`

- delete folder `node_modules`

- run `yarn install` again

Everythings ok.So I think the reason maybe amount of the dependencies beyond the limit

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.
Node: 10.16.0
Yarn: 1.16.0

[my repo](https://github.com/Hybueno09/flow-typed)

**Comment by Hybueno09** [comment]
• rebasing flow-typed cache...

<--- Last few GCs --->

[19036:00000161CE0FDF70]    32842 ms: Scavenge 1360.6 (1424.5) -> 1360.1 (1425.0) MB, 4.4 / 0.0 ms  (average mu = 0.165, current mu = 0.058) allocation failure
[19036:00000161CE0FDF70]    33493 ms: Mark-sweep 1360.9 (1425.0) -> 1360.3 (1425.0) MB, 644.5 / 2.1 ms  (average mu = 0.099, current mu = 0.026) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000001051E5C5C1]
    1: StubFrame [pc: 0000001051E113E6]
Security context: 0x01d24691e6e9 <JSObject>
    2: _parseVersion(aka _parseVersion) [00000347E3A06BC9] [E:\code\ZergUI\frontend\node_modules\flow-typed\dist\lib\flowVersion.js:~45] [pc=000000105228A5E5](this=0x03aa7fe026f1 <undefined>,verStr=0x00cc5aa3ecc1 <String[16]: v0.57.3-v0.103.x>,expectPossibleRangeUpper=0x03aa7fe028c9 <true>)
    3: parseDirString(aka ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF67E3DC6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 3: 00007FF67E3B7D90 node_module_register+2032
 4: 00007FF67E6D189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF67E6D17CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF67E8B7F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF67E8AEF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF67E8AD5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF67E8B6317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF67E8B6396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF67E9E0637 v8::internal::Factory::NewFillerObject+55
12: 00007FF67EA5D826 v8::internal::operator<<+73494
13: 0000001051E5C5C1
error Command failed with exit code 134.

**Comment by lukeapage** [comment]
me too.
I guess the repo is now too big
`node --max-old-space-size=10000 /c/npmprefix/node_modules/flow-typed/dist/cli.js`
(or similiar, depending on where your npm prefix is)

**Comment by barretron** [comment]
Alternative for `cross-env` users on Node >= 8

```text
cross-env NODE_OPTIONS=--max_old_space_size=10000 flow-typed update
```

**Comment by volaix** [comment]
`NODE_OPTIONS=--max_old_space_size=10000 flow-typed update`
Worked for me

**Comment by villesau** [comment]
Needs some investigation. apparently too much stuff loaded to memory that causes crashing. Easy solution would be just to bump the memory limit.

**Comment by ognanshissi** [comment]
I used `export NODE_OPTIONS=--max-old-space-size=8192` to fix `Allocation heap out of memory` when trying to build Angular project
