### ISSUE TITLE
[@testing-library/react] Improve DX for render method

### ISSUE THREAD

**Issue by bjohn465** [flow-typed/flow-typed#3520]
**Do you want to request a *feature* or report a *bug*?**
This is probably a feature, but it could be a bug, too, since this is somewhat of a regression in the developer experience for `@testing-library/react`.

Also, the apparent root cause of this issue causes "Unused suppression comment" warnings to be emitted when the tests are run for the Flow type definitions.

**What is the current behavior?**
Unless calls to the `render` method are annotated, the render result will not be type-checked by Flow.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
// @flow
import React from 'react'
import { render } from '@testing-library/react'

const MyComponent = () => null

const result = render(<MyComponent />)

// None of the following will cause a Flow error,
// even though they should.
// In previous versions of the flow-typed definitions,
// they would error, but not anymore.
result.somethingThatDoesNotExist()
result.rerender('This shouldn’t be a string')

// If you actually want the result to be checked by Flow,
// you need to annotate the `render` call,
// which isn't obvious.
const checkedResult = render<{}>(<MyComponent />)

// Now the following will cause a Flow error
checkedResult.somethingThatDoesNotExist()
checkedResult.rerender('This shouldn’t be a string')
```

**What is the expected behavior?**
I'd expect the default (non-annotated) usage to still result in the render result being checked by Flow, as previous versions of the flow-typed definitions for this library did.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Improve the developer experience

**Local Environment Information**
This issue isn't specific to any environment settings.

**Comment by pascalduez** [comment]
Thanks for reporting,

probably my bad in #3510. 
I will try to fix asap.

**Comment by valscion** [comment]
Yeah looks like #3510 indeed caused this problem. The [CI test run] in #3510 _did not pass_ but the PR was still forcefully merged 😒. So the typings have been broken for quite some time.

I'll try to fix the `@testing-library/react` type definitions to pass the existing specs.

**Comment by valscion** [comment]
See https://github.com/flow-typed/flow-typed/pull/3704, that contains a fix. https://github.com/flow-typed/flow-typed/pull/3705 contains an effort of mine where I tried to add proper typing support for custom queries https://testing-library.com/docs/react-testing-library/api#queries but I wasn't able to come up with generics for `render()` that would not break other legit use cases.

**Comment by pascalduez** [comment]
Thanks for looking into this @valscion!

#3705 was obviously rushed, in an attempt to catch back with their TS definitions. 
I thought I would have time to go into a major refactor but still not.   
Sadly most of our definitions here have failing assertions tests due to Flow versions changes. So I didn't pay enough attention to those one I guess.
