### ISSUE TITLE
puppeteer: unable to use default export

### ISSUE THREAD

**Issue by jtbandes** [flow-typed/flow-typed#3538]
The [puppeteer type definitions](https://github.com/flow-typed/flow-typed/blob/b426b5f657cc2b688f3aced6eea25fc052f8f797/definitions/npm/puppeteer_v1.12.x/flow_v0.104.x-/puppeteer_v1.12.x.js) don't seem to allow me to use the default export:
```
import puppeteer from "puppeteer";
puppeteer.launch(...);
```
which is the recommended usage according to the Puppeteer documentation.

Instead, Flow requires
```
import { launch } from "puppeteer";
launch(...);
```
because of
https://github.com/flow-typed/flow-typed/blob/b426b5f657cc2b688f3aced6eea25fc052f8f797/definitions/npm/puppeteer_v1.12.x/flow_v0.104.x-/puppeteer_v1.12.x.js#L2670
which **doesn't actually work at runtime**, because the default export is a class instance and so `launch()` here is an **un**bound method.

I've detailed the issue here:

https://stackoverflow.com/questions/57705213/flow-type-definitions-for-puppeteer-prevent-using-default-export

Are these type defs actually working for others?

**Comment by jtbandes** [comment]
@pascalduez thanks, so does that mean you think this is a bug with the defs themselves? I'm surprised they could have been written without encountering this issue, but I'm not familiar with the testing infrastructure in this repo; are there any tests that should have automatically caught this issue? I might make a PR to fix this if you can point me at the right way to test it. :)

**Comment by pascalduez** [comment]
@jtbandes I didn't dig it for long but looks like indeed something's wrong.

For the tests, nothing fancy, just try to be exhaustive and replicate the most common usages.
Use some error assertions with `// $ExpectError`.  
Look at other definitions for inspiration.
Wrap the cases in [`describe / it` blocks](https://github.com/flow-typed/flow-typed/blob/master/CONTRIBUTING.md#writing-tests).

**Comment by Rayad2361424** [comment]
https://stackoverflow.com/questions/57705213/flow-type-definitions-for-puppeteer-prevent-using-default-export

**Comment by Rayad2361424** [comment]
https://stackoverflow.com/questions/57705213/flow-type-definitions-for-puppeteer-prevent-using-default-export

**Comment by goodmind** [comment]
@jtbandes it was just converted from TS, so probably something was lost during translation

**Comment by goodmind** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/puppeteer/index.d.ts there isn't default export either

**Comment by jtbandes** [comment]
@Rayad2361424 yes, I posted that question shortly before creating this issue :)

@goodmind yeah, it looks like TypeScript users would have a similar issue, unless TS is flexible on the use of named exports with default export–style syntax?

**Comment by avalanche1** [comment]
Yep, same issue in typescript

**Comment by Silver47Gin** [comment]
Same issue in typescript version 4.4.3.
I downgrade the typescript version to 3.8.3, it works.

**Comment by ireneelder** [comment]
I'm having the same issue with Typescript 4.4.3 - the dependabot update to this version is throwing the error 'TypeError: Cannot read property '_launcher' of undefined'. Is there a fix for this or is just ignoring the update and staying on the current version (we're on 4.3.5) the only solution?

**Comment by jtbandes** [comment]
This is the flow-typed repo, which isn't the right place to discuss TypeScript issues. You should probably file a ticket on DefinitelyTyped.

**Comment by Brianzchen** [comment]
This was already solved [here](https://github.com/flow-typed/flow-typed/pull/3595/files#diff-f965aa5ef3c915587004be7d96effc66a520b4833d6358487404cd33a99a568fR1369) in https://github.com/flow-typed/flow-typed/pull/3595
