### ISSUE TITLE
Relax 'flow-bin' dependency check

### ISSUE THREAD

**Issue by mrtnzlml** [flow-typed/flow-typed#3565]
**Do you want to request a *feature* or report a *bug*?**

I want to request a _feature_.

**What is the current behavior?**

Flow-typed currently throws this error in our setup:

```
UNCAUGHT ERROR: Error: Failed to find a flow-bin dependency in package.json.
Please install flow-bin: `npm install --save-dev flow-bin`
```

**What is the expected behavior?**

It should not throw.

**If this is a feature request, what is motivation or use case for changing the behavior?**

We have custom `flow-bin` implementation which uses some additional features on top of the regular bin. So we distribute our own package (which still depends on `flow-bin` but eventually doesn' have to). As a consequence, we do not have `flow-bin` in package.json directly but seems like `flow-typed` requires it.

It would be nice to relax this requirement and allow more advanced project setups. Somehow related (but different) issue: https://github.com/flow-typed/flow-typed/issues/1282

**Comment by julienw** [comment]
I got the same problem when I tried to configure a project with a multi-repo structure.

**Comment by Brianzchen** [comment]
But how would flow-typed know what version of lib defs to provide you? Always install latest as a fallback maybe?

**Comment by julienw** [comment]
Maybe with running `node_modules/.bin/flow --version` ? Or a form of `node_modules/.bin/flow --json` which outputs the flow version in a json format, but still checks everything.

**Comment by mrtnzlml** [comment]
This should be workaroundable via `--flowVersion` option, see https://github.com/flow-typed/flow-typed/pull/4006 for more details.
