### ISSUE TITLE
create-stub --typescript fails with 404 error

### ISSUE THREAD

**Issue by paularmstrong** [flow-typed/flow-typed#3583]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

```
$ flow-typed create-stub connect-timeout@1.9.0 --typescript
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
• Creating 1 stub...
UNCAUGHT ERROR: HTTPError: Response code 404 (Not Found)
    at stream.catch.then.data (/Users/parmstrong/workspace/web/node_modules/got/index.js:386:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```
flow-typed create-stub connect-timeout@1.9.0 --typescript
```

**What is the expected behavior?**

Successfully download, convert, and use the typescript definition for connect-timeout (NOTE: this is reproducible with any library).

Everything was working fine about 1 week ago, but has been failing with this 404 for the last few days.

**If this is a feature request, what is motivation or use case for changing the behavior?**

n/a

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 115.77 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - /opt/twitter_mde/bin/node
    Yarn: 1.15.2 - /opt/twitter_mde/bin/yarn
    npm: 6.4.1 - /opt/twitter_mde/bin/npm
    Watchman: 4.7.0 - /opt/twitter/bin/watchman
  Managers:
    Homebrew: 2.1.10 - /opt/twitter/bin/brew
    Maven: 3.3.3 - /opt/twitter/bin/mvn
    pip2: 18.0 - /opt/twitter/bin/pip2
    pip3: 18.0 - /opt/twitter/bin/pip3
    RubyGems: 2.4.8 - /opt/twitter/rvm/rubies/ruby-1.9.3-p551/bin/gem
  Utilities:
    CMake: 3.12.2 - /opt/twitter/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.4.11.830. - /opt/twitter_mde/bin/git
    Clang: 1100.0.33.8 - /usr/bin/clang
    Mercurial: 4.6.1 - /opt/twitter/bin/hg
    Subversion: 1.10.4 - /usr/bin/svn
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_111 - /usr/bin/javac
    Perl: 5.18.4 - /usr/bin/perl
    PHP: 7.1.23 - /usr/bin/php
    Python: 2.7.15 - /opt/twitter/bin/python
    Python3: 3.7.0 - /opt/twitter/bin/python3
    Ruby: 1.9.3 - /opt/twitter/rvm/rubies/ruby-1.9.3-p551/bin/ruby
```

**Comment by 102** [comment]
It looks like that this error is generated somewhere [near these lines](https://github.com/flow-typed/flow-typed/blob/8c0ba659dccfcf492fa2ea7ed739f08e3c9e8ce5/cli/src/lib/stubUtils.js#L374L375)

This is also likely not a CLI bug, but a lack of helpful error messages: 

```
npx flow-typed create-stub connect-timeout@0.0.34 --typescript
```

this produces a stub from typescript, because typings are present at `npm` and `unpkg`: https://unpkg.com/@types/connect-timeout@0.0.34/index.d.ts, but there's no such definitions for 1.9.0: https://unpkg.com/@types/connect-timeout@1.9.0/index.d.ts

**Comment by paularmstrong** [comment]
Interesting @102. I think another acceptable alternative outcome in this case would be to log a warning and create an empty stub

**Comment by pascalduez** [comment]
Should be improved/fixed as of `flow-typed@3.x`.
