### ISSUE TITLE
Machine-In-The-Middle vulnerability issue with https-proxy-agent dependency

### ISSUE THREAD

**Issue by damianpm** [flow-typed/flow-typed#3607]
**Do you want to request a *feature* or report a *bug*?**

Security issue

**If the current behavior is a bug, please provide the steps to reproduce.**

Using `"flow-typed": "^2.6.1",` Run `npm install`.

It will report: `found 1 high severity vulnerability`.

Running `npm audit` will report the affected package:

`High                   │ Machine-In-The-Middle `
`Package             │ https-proxy-agent`
`Patched in         │ >=3.0.0 `
`Dependency of │ flow-typed [dev]`
`Path                   │ flow-typed > @octokit/rest > https-proxy-agent`
`More info           │ https://npmjs.com/advisories/1184`

**What is the expected behavior?**

No vulnerabilities found

**Local Environment Information**
flow-typed: 2.6.1
Node: 12.12.0
Npm: 6.11.3

**Comment by StephenTG** [comment]
Related: https://github.com/flow-typed/flow-typed/pull/3602
