### ISSUE TITLE
No flow binaries are installed when testing locally

### ISSUE THREAD

**Issue by valscion** [flow-typed/flow-typed#3637]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

`./build_and_test_cli.sh` shows a test failure locally on a clean installation. Once tests are skipped, `./quick_run_def_tests.sh` does not download _any_ flow binaries and no tests are being run, even if I manually change some test files.

**If the current behavior is a bug, please provide the steps to reproduce.**

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh_](https://user-images.githubusercontent.com/482561/68485827-980b4e00-0248-11ea-835f-a27530fadb3b.png)

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh_](https://user-images.githubusercontent.com/482561/68485870-ac4f4b00-0248-11ea-8d5f-2edd98c6e763.png)

When I skip the `yarn test-quick` phase by modifying `cli/package.json`, I get that command to pass.

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh_](https://user-images.githubusercontent.com/482561/68485982-e28cca80-0248-11ea-97d6-f7d5ea72e439.png)

However, when I then run `./quick_run_def_tests.sh`, it doesn't download any flow binaries.

Changing a type definition causes more logging to be displayed, but still nothing is downloaded.

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh_](https://user-images.githubusercontent.com/482561/68486229-58913180-0249-11ea-95f7-1630c7493281.png)

**What is the expected behavior?**

I expect this to download all recent Flow binaries so I could work on type fixes, such as pick up #3506 from where it left off.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Local Environment Information**
If this issue is specific to the CLI, provide the results of running `npx envinfo` from the command line in a GitHub gist.

`npx envinfo` output here: https://gist.github.com/valscion/fa45a6fa1d930302787ff3c6204f3e0b

**Comment by valscion** [comment]
No dice even with reinstalling to `yarn` v1.19.1:

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh__and_yarn_self-update___Yarn](https://user-images.githubusercontent.com/482561/68486905-c12cde00-024a-11ea-874e-acfd342d8e4a.png)

![vesa_Vesas-MacBook-Pro____code_muut_flow-typed__zsh_](https://user-images.githubusercontent.com/482561/68486934-d275ea80-024a-11ea-8104-0b00c1ea6c17.png)

**Comment by pascalduez** [comment]
@valscion An important fix landed in #3638. 
Could you give it another try?

**Comment by valscion** [comment]
Cool, tests pass now and the flow binaries are now downloaded as expected! :relaxed: :tada:

So this issue is fixed. Thanks!
