### ISSUE TITLE
Function generic causes unexpected error

### ISSUE THREAD

**Issue by mcharytoniuk** [flow-typed/flow-typed#3644]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

There is an unexpected error about generics.

![equatable](https://user-images.githubusercontent.com/1286785/69001627-65192800-08e2-11ea-9f18-863238135847.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the complete example. I am using `"flow-bin": "^0.112.0"`.

```js
// file-a.js
```
```js
// @flow

import type { Equatable } from "../interfaces/Equatable";

function hasArrayEqual<T>(a: $ReadOnlyArray<Equatable<T>>, item: Equatable<T>): bool {
  for (let aItem of a) {
    if (aItem.isEqual(item)) {
      return true;
    }
  }

  return false;
}

export function isEqualArray<T>(a: $ReadOnlyArray<Equatable<T>>, b: $ReadOnlyArray<Equatable<T>>): bool {
  if (a.length !== b.length) {
    return false;
  }

  if (!a.every(aItem => hasArrayEqual<T>(b, aItem))) {
    return false;
  }

  return b.every(bItem => hasArrayEqual<T>(a, bItem));
}
```

```js
// Equatable.js
```
```js
// @flow

export interface Equatable<T> {
  isEqual(other: T): boolean;
}
```

**What is the expected behavior?**

No errors.

**Comment by pascalduez** [comment]
Hi @mcharytoniuk,

looks like you'd want to open that issue to the [Flow core repository](https://github.com/facebook/flow) instead.

**Comment by mcharytoniuk** [comment]
@pascalduez Thank you! Is there a way to move the issue or should I just copy-paste it there?

**Comment by pascalduez** [comment]
@mcharytoniuk I think we can transfer issues from repos inside a same organization, but probably not outside, worth checking though.
