### ISSUE TITLE
can we have type definitions for Yup?

### ISSUE THREAD

**Issue by shantanu10** [flow-typed/flow-typed#3684]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently, we have to write our own file say `yup.flow.js ` which contains all the library definitions 
of methods and schemas in yup. But in that case we have to maintain it as yup can update its schemas. 

**What is the expected behavior?**
It would be better if flow can provide the support for yup. So it gets updated accordingly with yup.

**Comment by shantanu10** [comment]
[https://gist.github.com/lfantone/e73634b28eae1489757f493961e12961](url)
For now the solution is to use a file like above and and give its path in the [libs] section of .flowconfig. Any better approcahes ?

**Comment by pascalduez** [comment]
Did you try looking if it's already available first?

```
➜ flow-typed search yup

Found definitions:
╔══════╤═════════════════╤══════════════════════╗
║ Name │ Package Version │ Flow Version         ║
╟──────┼─────────────────┼──────────────────────╢
║ yup  │ v0.x.x          │ >=v0.69.0 <=v0.103.x ║
╟──────┼─────────────────┼──────────────────────╢
║ yup  │ v0.x.x          │ >=v0.104.x           ║
╚══════╧═════════════════╧══════════════════════╝

```
