### ISSUE TITLE
Broken axios_v0.19.x flow type with flow_v0.80.x- , using unsuported ellipsis 

### ISSUE THREAD

**Issue by eawtf** [flow-typed/flow-typed#3689]
Recent changes **broke** Flow check in many projects using **0.80.x - 0.83.y versions:**

Changes commited to the **master**:
[https://github.com/facebook/flow/blob/master/Changelog.md#0840](url)

Changelog for **0.84 version**:
[https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/axios_v0.19.x/flow_v0.80.x-/axios_v0.19.x.js](url)

![image](https://user-images.githubusercontent.com/16733354/71714995-f4da4d80-2e20-11ea-92d0-e04b0a5b18ec.png)

![image](https://user-images.githubusercontent.com/16733354/71715053-27844600-2e21-11ea-880f-65b3a093623a.png)

**Comment by pascalduez** [comment]
We need to revert those changes from the `0.80.x` definition and introduce them from a `0.104.x-` definition.
PR welcome!

**Comment by eawtf** [comment]
@pascalduez great, got it. Will post the link with PR here.

**Comment by eawtf** [comment]
@pascalduez done:
https://github.com/flow-typed/flow-typed/pull/3691/files
