### ISSUE TITLE
Split extendedMatchers, jqueryMatches and so on from jest types

### ISSUE THREAD

**Issue by danrot** [flow-typed/flow-typed#3715]
**Do you want to request a *feature* or report a *bug*?**
Bug(?)

**What is the current behavior?**
We have received a [Pull Request](https://github.com/sulu/sulu/pull/5008) modifying the jest flow types, because we have not installed stuff like `jest-styled-components`, `jest-enzyme` and so on, but the types provided by this repository are still including APIs only available if these packages are installed.

**What is the expected behavior?**
I would expect that I don't get auto complete suggestions in my editor, if I have not installed these packages. So I would suggest that the types for `jest-enzyme`, `jest-styled-components` and so on are split into separate files. This way we could leave out the packages we have not installed, while still allowing other people to install them.

**Comment by pascalduez** [comment]
Hi,

as far as I know it's not currently possible. There's no way in Flow to extend a definition or type without overriding it.

To only list a few:
https://github.com/facebook/flow/issues/396  
https://github.com/facebook/flow/issues/5364  
https://github.com/flow-typed/flow-typed/issues/1857

**Comment by danrot** [comment]
Ok, that's too bad... Hopefully it will be possible eventually at some point.
