### ISSUE TITLE
React Apollo Hooks Problem With DataProxyReadQueryOptions

### ISSUE THREAD

**Issue by ammanvedi** [flow-typed/flow-typed#3718]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using readquery flow complains that one of the interface types is not a polymorphic type

**If the current behavior is a bug, please provide the steps to reproduce.**
1. call a mutation and attempt a readquery call in the update function
2. run flow

there is a error thrown which is complaining that `DataProxyReadQueryOptions` is not a polymorphic type, i beleive this means that it does not accpet a generic but it is being passed one

[Try Flow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgCJzHAClA9gDwE8AlCOAEwEUBXaQgeQAcxhcQBnZAbwChl-kAR1pRCALmT0ARgCsICMAG4+AgG5wowOFIA2EdgH4JcEIWX8Aviv7Xk5eTo0oEj9pwCCjXDp24AwjrAEOAAPAAqfogAFhAAylFwjBAAfNw8tlBkVCKE4QA0aMkAFLjMrBwS6Jg4BCRZNHRMLGzsIajJAJQSYcgAPsgg1D7KVjwILWDI+MgAvAMQAO7Int6+AUHgRR3p+AB0mRQNokVcQjkSXBbIFh1AA)

**What is the expected behavior?**

There shouldnt be an error here and the type that is erroring should accept the generic type that we are passing it

[Try Flow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgCJzHAClA9gDwE8AlCOAEwEUBXaQgeQAcxhcQBnAHlQD5kBvAFDIRyAI60ohAFzJ6AIwBWEBGADcw0QDc4UYHHkAbCOwD8s1BpEBfTSMHkVh3SgTP27ZAEFGuQ4dwAYUNgCHBOABVAxAALCABlGLhGCD4hO2QoMipJQkiAGjQeAApcZlYOCwxsPCJSCho6JhY2Ll4ASlkI5AAfZBBqfw1bQQRWsGR8ZABefogAd29ffyCQsLBi9sFBfAA6LIbczjgQQkKTwhL+cVzZfmtka3agA
)

**Comment by gurtaj1** [comment]
I am experiencing the same issue described here

**Comment by ammanvedi** [comment]
closing as fixed by https://github.com/flow-typed/flow-typed/pull/3719
