### ISSUE TITLE
Cannot import useDispatch because there is no useDispatch export in react-redux

### ISSUE THREAD

**Issue by nguyentoantuit** [flow-typed/flow-typed#3728]
Cannot import useDispatch because there is no useDispatch export in react-redux.

     1│ // @flow
     2│
     3│ import * as React from 'react';
     4│ import { useSelector, useDispatch } from 'react-redux';
According to #3452, above message should be resolved but I updated the newest version of flow-typed already but the error message still there. Do I miss something?

**Comment by pascalduez** [comment]
Which version of `react-redux` are you using? And more importantly which version of the libdef? 
`@gandi/ui-select` is only available as of the `7.x`.

**Comment by nguyentoantuit** [comment]
Thanks @pascalduez for your response, 
I use react-redux v 7.1.3, I didn't see libdef in our source code (just join the team). 
But I am able to resolve this issue by defining flow-typed of react-redux by myself flow-typed > npm > react-redux_vx.x.x.js
So I will close this issue.

**Comment by nguyentoantuit** [comment]
Fix this issue by run command: npm run flow-typed update react-redux
Now I know what is the libdef @pascalduez . Thanks!
