### ISSUE TITLE
Duplication of new Semver incompatible Versions

### ISSUE THREAD

**Issue by marudor** [flow-typed/flow-typed#374]
We got such a case here: https://github.com/flowtype/flow-typed/pull/373
We also have the problem if we do not have anything for the new version yet flow-typed will give nothing instead of the old one that might fit for 90% of the cases.
It would be helpful if it would fetch the old version and give a hint about it being outdated?

**Comment by jeffmo** [comment]
> It would be helpful if it would fetch the old version and give a hint about it being outdated?

The problem with fetching old/semver-incompatible versions is that this means Flow could lie about what is typesafe.

It does seem reasonable to look for a previous version that shares the same major and have the CLI tell the user that a previous/incompatible version exists as a good starting point, though.
