### ISSUE TITLE
@apollo/react-hooks possibly incorrect joint type definitions

### ISSUE THREAD

**Issue by kenns29** [flow-typed/flow-typed#3745]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Currently, in @apollo/react-hooks, the joint types are defined using the intersection type, e.g.

```
  declare export type QueryResult<TData, TVariables> = ObservableQueryFields<
    TData,
    TVariables
  > & {
    client: ApolloClient<any>,
    data: ?TData,
    error?: ApolloError,
    loading: boolean,
    networkStatus: NetworkStatus,
    called: boolean,
    ...
  };
```
However, this pattern can produce unexpected behaviors according to https://flow.org/en/docs/types/objects/#toc-exact-object-types (also refer to https://github.com/facebook/flow/issues/2626)

For example, the statement

```
const {loading, error, data} = useQuery<TData, TVariable>(...);
```

will give flow error "`data` is not found in `ObservableQueryFields`", and changing the type definition to the following will fix it.

```
  declare export type QueryResult<TData, TVariables> = {
    ...ObservableQueryFields<
      TData,
      TVariables
    >,
    client: ApolloClient<any>,
    data: ?TData,
    error?: ApolloError,
    loading: boolean,
    networkStatus: NetworkStatus,
    called: boolean,
  };
```

**Comment by kenns29** [comment]
Tagging the author @ganemone

**Comment by jedwards1211** [comment]
Actually the problem is not as described in the link because these are inexact types.  Intersecting readonly inexact types can work, but intersecting mutable inexact types just doesn't.
