### ISSUE TITLE
@testing-library/react v10: href property throws error

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#3816]
**Do you want to request a *feature* or report a *bug*?**
Bug in `@testing-library/react`

**What is the current behavior?**
Elements that are returned from `getByTestId` are always `HTMLElement` so when I try to access `element.href` it throws flow error.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
  const { getByTestId } = render(
      <Footer
        {...props}
      />,
    );

    expect(getByTestId('customer-service-link').href).toBe('tel:131 802');
```

Have tried to cast it but I'm told 
```
Cannot assign `getByTestId(...)` to `linkElement` because  `HTMLElement` [1] is incompatible with  `HTMLLinkElement`
```

```
  const { getByTestId } = render(
      <Footer
        {...props}
      />,
    );

    const linkElement: HTMLLinkElement = getByTestId('customer-service-link')

    expect(linkElement.href).toBe('tel:131 802');
```

**What is the expected behavior?**
`href` should be an optionally available property or I should be able to optionally pass the type I expect back such as `getByTestId<HTMLLinkElement>('customer-service-link')`

**Local Environment Information**
Flow v. 0.122.0, latest `@testing-library/react` v10 flow types.

**Comment by Brianzchen** [comment]
Solved this by first checking the `instanceof` the element before I access the values. But all my tests will need to assert the amount of expects prior

```
expect.assertions(1);

const { getByTestId } = render(
  <Footer
    {...props}
  />,
);

const linkElement = getByTestId('customer-service-link')

if (linkElement instanceof HTMLLinkElement) {
  expect(linkElement.href).toBe('tel:131 802');
}
```

**Comment by pascalduez** [comment]
Hi @Brianzchen,

there've been a previous attempt at this in #3404. 

I proposed to try with a default generic. 

The libdef changed a bit since, but out of the blue it could look like:
```js
declare type GetByBoundAttribute<T: HTMLElement = HTMLElement> = (
  text: TextMatch,
  options?: TextMatchOptions
) => T;
```
Want to give it a try?

**Comment by Brianzchen** [comment]
Thanks @pascalduez that's a really helpful start. But I've come across a few issues over a few test scenario's.

When I try to simply implement your change, the types declaration for functions such as `getByTestId` throws errors saying `Cannot use GetByBoundAttribute [1] without 0-1 type arguments.`

Next I try to add generics to the `GetByBoundAttribute` caller with
```
getByTestId: GetByBoundAttribute<T>,
```
This removes the flow error but now no errors are thrown at all so it becomes useless.

So because I'm not so experienced I try to use the `GetByBoundAttribute` function directly in `getByTestId` 
```
getByTestId: <T: HTMLElement = HTMLElement>(
  text: TextMatch,
  options?: TextMatchOptions
) => T,
```
This works which is awesome, but only in the circumstance when I provide arrow brackets as such,
```
const linkElement = getByTestId<>('customer-service-link') // throws error telling me it's HTMLElement which is what I want
```
```
const linkElement = getByTestId<HTMLLinkElement>('customer-service-link') // no error and is casted correctly
```

But with no arrow brackets, there's no type checking and no errors at all being thrown when there should be.
```
const linkElement = getByTestId('customer-service-link') 
```

Any idea what the fix here could be?
