### ISSUE TITLE
"No libdef file found!" when I try to run-tests

### ISSUE THREAD

**Issue by jedwards1211** [flow-typed/flow-typed#3820]
What does this mean?

**Comment by GAntoine** [comment]
What folder are you running the tests from? Could you paste the command and shell output?

**Comment by jedwards1211** [comment]
it doesn't seem to make a difference if I run from the root folder, the cli folder, or one of the def folders.

```
flow-typed $ ./quick_run_def_tests.sh 
Running changed definition tests against latest 15 flow versions in /Users/andy/flow-typed/definitions/npm...

No libdef file found!
```

**Comment by jedwards1211** [comment]
I think a mistake in a single def folder can cause this to fail for everything, looking at the following code:

![image](https://user-images.githubusercontent.com/1448194/80259840-21bea480-864c-11ea-888d-8a9ade20b78e.png)

**Comment by jedwards1211** [comment]
Okay it happens when there's an empty directory inside of definitions.  Shouldn't we just warn an skip such directories?

**Comment by GAntoine** [comment]
Possibly, unless we want our tests to fail in this case, which is possible.

**Comment by Brianzchen** [comment]
@jedwards1211 I had the same issue, it's been fixed so it gives better error messaging now
https://github.com/flow-typed/flow-typed/pull/4010/files#diff-8d79504708c458af52c78196b2e4005dd80980bf42c32eea27cfbeaf2c647e44R249

**Comment by AndrewSouthpaw** [comment]
Calling this done then, feel free to request a re-open. 😄
