### ISSUE TITLE
Flow 0.127: Unsupported option specified! (suppress_comment)

### ISSUE THREAD

**Issue by Ashoat** [flow-typed/flow-typed#3856]
Seeing this error whenever I call `run-tests`

> .flowconfig:6 Unsupported option specified! (suppress_comment)

I think it's coming from [this line](https://github.com/flow-typed/flow-typed/blob/master/cli/src/commands/runTests.js#L302). It's happening because suppression config changed in Flow 0.127.

**Comment by joeblas** [comment]
@Ashoat it probably just needs to be removed from the test: https://github.com/facebook/flow/issues/8403#issuecomment-644942810

> Remove suppress_comment from your .flowconfig.
> 
> The different error suppressors are standardized now and not configurable: https://medium.com/flow-type/making-flow-error-suppressions-more-specific-280aa4e3c95c
> 
> The standard ones are: $FlowFixMe, $FlowIgnore, $FlowIssue, $FlowExpectedError. You can use sed to search/replace $FlowSuppressError to $FlowIgnore

**Comment by pascalduez** [comment]
Should be fixed by #3855

**Comment by pascalduez** [comment]
Should be fixed as of [`v3.2.0`](https://github.com/flow-typed/flow-typed/releases/tag/v3.2.0)
