### ISSUE TITLE
New terminology to promote inclusive language

### ISSUE THREAD

**Issue by adevfromhere** [flow-typed/flow-typed#3874]
Blacklist: alternatives could be “Block List” or “Deny List”
Whitelist: alternatives could be “Allow List” or “Pass List”
Master/Slave: alternatives could be "primary/secondary", "controller/device", "requester/responder", or "main/replica"

**Comment by GAntoine** [comment]
Hi @adevfromhere! Would you be interested in opening a PR that in makes those changes? If you could point out some of the locations you've come across where we use non-inclusive language, that would also be awesome.

I've considered changing the master branch to "main", but that would require some significant changes to our install scripts and third-party tools.
