### ISSUE TITLE
Feature: Enforce Children Count on React

### ISSUE THREAD

**Issue by krishnadubagunta** [flow-typed/flow-typed#3877]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Type checking currently does not enforce a certain number of components in children.

**If this is a feature request, what is motivation or use case for changing the behavior?**
```jsx
const TabSwitcher = ({ children }) => {
  const [tab, setTab] = useState<number>(0)
  
  return (<>
     <CardTabs>
        <CardTab label='tab 1' value={0} />
        <CardTab label='tab 2' value={1} />
        <CardTab label='tab 3' value={2} />
     <CardTabs>
     {
         children[tab]
     }
  </>)
}

const App = () => {
  return (<TabSwitcher>
     <div>Tab 1</div>
     <div>Tab 2</div>
     <div>Tab 3</div>
  </TabSwitcher>)
}
```

in this sample, if we could enforce the children count to be 3 for TabSwitcher, it would be a good feature so that there would be a flow error when `<div>Tab 4</div>` is added instead of having to raise an error something like 
```javascript
  if (React.Children.count(children) !== 3) throw new Error('you dumb man!')
```

**Comment by pascalduez** [comment]
Probably wrong repo for asking general Flow questions.

Maybe something like https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMAAUWOSgF4wAb1Rgw9ABYYYAEy4A7AFxgA2oqXVuhAHQBRGDSw1thADzsNGAG7sAfABpjS2gwW1rb2Ti7uXt5gfqaBVjZ2Ds6uHj7GALqoAL7o9HDa5MQAKqQARgDKCBiEqjT4YLIAFHLKapo6YFn6EnBSAJQNnvLGXIQArvjarepa9tm5+YXiFDJgjQPSQ43GjiUVVTUqdZ4xYI4pnntgAIyOwBen5+6XZWAATHcPJkpPbi+lYAAzJ9njtgHtKtVavgTn0FgViAAxUjqBprDZbHYQg7Qk7fM4XK63e6gn7gsqQw7HVB9IA
