### ISSUE TITLE
Error using flow + express 4 + HTTPS

### ISSUE THREAD

**Issue by drumbsd** [flow-typed/flow-typed#3879]
BUG?

Taking this example code:

`// @flow
const express = require('express')
const http = require('http')
const https = require('https')
const fs = require('fs')

const app = express()

// start http server
const port = 15000;
let server = http.createServer(app).listen(port)

// start https server
let sslOptions = {
  key: fs.readFileSync('key.pem'),
  cert: fs.readFileSync('cert.pem')
}

let serverHttps = https.createServer(sslOptions, app).listen(443)`

flow gives me this error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/test.js:19:50

Cannot call https.createServer with app bound to requestListener because 
net$Socket [1] is incompatible with
tls$TLSSocket [2] in type argument SocketT [3] of the first argument. 
[incompatible-call]

    src/test.js
      16│    cert: fs.readFileSync('cert.pem')
      17│ }
      18│
      19│ let serverHttps = https.createServer(sslOptions, app).listen(443)

    /tmp/flow/flowlib_493dfe4/node.js
 [3][1] 1381│ declare class http$IncomingMessage<SocketT = net$Socket> 
 extends stream$Readable {
        :
[2] 1562│   declare class IncomingMessage extends    http$IncomingMessage<tls$TLSSocket> {}    
```

**Comment by AndrewSouthpaw** [comment]
I'm not very familiar with how node/express works... it seems like it's an issue because you're passing `app` to both the `http` and `https` versions of the `createServer` method, which expect different types.

It might be possible to make the types more permissive, assuming this pattern is valid?

**Comment by drumbsd** [comment]
> It might be possible to make the types more permissive, assuming this pattern is valid?

Are you asking this to me?

**Comment by AndrewSouthpaw** [comment]
I think it's a general question to you or anyone else more familiar with Node/Express than me. 😄 

If it can be confirmed that it's a valid usage, and someone wants to adjust the libdefs, I fully support it.
