### ISSUE TITLE
Update all tests with suppression codes

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#3919]
Can we use the internal flow too to update all suppression codes in one go so that there's less friction with new flow changes?

```
sainati Today at 10:38 AM
yes
you can use the tool script that comes with the repo
so ./tool add-comments <SUPPRESSION TEXT> will add suppression comments with the correct codes and that comment
and ./tool remove-comments will remove unused suppressions
this is what we do to upgrade our codebases internally
```

**Comment by pascalduez** [comment]
Cool!

This is exactly what I wanted to ask them :) 

I hope we will be able to make it work, flow-typed tests are not a standard codebase, so dunno how the tool/flow will be able to make sense of them.

**Comment by Brianzchen** [comment]
I've run a test on this, you basically need to have both the `flow` and `flow-typed` repo's cloned. Then you'll need to install `flow-bin` in the definitions folder (which can be removed later prior to merging) and have flow on the same version.

Then in the flow repo, run, `./tool add-comments ../flow-typed/definitions` where I encountered a few issues,
- Because the imports are a bit random, it threw lots of module not found errors
- Currently flow can't handle adding suppression codes to existing comments, but the flow team will see if that ability can be open sourced

**Comment by jedwards1211** [comment]
I'm trying to write test cases and when I add suppression codes it just warns about unused suppression, is it just be flow being buggy as usual?

**Comment by jedwards1211** [comment]
Even though the Flow docs explicitly state that you can suppress multiple error codes like this:

```js
  // $FlowFixMe[incompatible-call]
  // $FlowFixMe[prop-missing]
```
I get an unused suppression warning on the first comment.
Getting really tired of dealing with bugs like this.

**Comment by jedwards1211** [comment]
Oh, I guess some of those buggy warnings were happening in 0.125-0.126 and then fixed in later versions

**Comment by pascalduez** [comment]
> Oh, I guess some of those buggy warnings were happening in 0.125-0.126 and then fixed in later versions

Yes, I experienced the same thing. Ended up scoping some libdef to 0.127.x-

**Comment by Brianzchen** [comment]
Closing, don't think there's a clear way to automate this
