### ISSUE TITLE
Support prerelease identifiers in libdef versions

### ISSUE THREAD

**Issue by jeffmo** [flow-typed/flow-typed#392]
Semver allows you have to things like `v2.3.x-beta.11`, but we currently don't support libdefs for this kind of "prerelease" version. Without such support, we can't version or find libdefs for beta versions of npm packages.

**Comment by nmote** [comment]
Just got bitten #362. The only reason I noticed it was that I ended up with a bunch of unused suppression comments.

**Comment by Brianzchen** [comment]
The CLI has been enhanced to support pulling definitions like this. eg: if `v2.3.0-beta-1` has dropped you can add definitions for `v2.3.x` and flow-typed will correctly install, as new betas or stable versions are released you can update the definition to suit.
