### ISSUE TITLE
[react-redux_v7.x.x][flow-bin v0.122.0]

### ISSUE THREAD

**Issue by carlost** [flow-typed/flow-typed#3921]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Flow reports two errors with the react-redux_v7.x.x.js flow lib def file:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/react-redux_v7.x.x.js:122:37

Inexact object type [1] is incompatible with exact MergeOPDP [2].

 [2]  87│   declare type MergeOPDP<OP, DP> = {| ...$Exact<OP>, ...DP |};
        :
     119│     mapDispatchToProps: DP,
     120│     mergeProps?: null | void,
     121│     options?: ?Options<S, OP, {||}, MergeOPDP<OP, DP>>,
 [1] 122│   ): Connector<P, OP, MergeOPDP<OP, $ObjMap<DP, Bind<D>>>>;
     123│
     124│   declare export function connect<-P, -OP, -SP, -DP, S, D>(
     125│     // If you get error here try adding return type to your mapStateToProps function


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/react-redux_v7.x.x.js:138:43

Inexact object type [1] is incompatible with exact MergeOPSPDP [2].

 [2]  88│   declare type MergeOPSPDP<OP, SP, DP> = {| ...$Exact<OP>, ...SP, ...DP |};
        :
     135│     mapDispatchToProps: DP,
     136│     mergeProps?: null | void,
     137│     options?: ?Options<S, OP, SP, MergeOPSPDP<OP, SP, DP>>,
 [1] 138│   ): Connector<P, OP, MergeOPSPDP<OP, SP, $ObjMap<DP, Bind<D>>>>;
     139│
     140│   // With `mergeProps` argument
     141│



Found 2 errors
error Command failed with exit code 2.
```

These issue go away if i add `flow-typed/npm/react-redux_v7.x.x.js` to the [declarations](https://flow.org/en/docs/config/declarations/) section of the flow config

**If the current behavior is a bug, please provide the steps to reproduce.**
[Gist of current flow config](https://gist.github.com/carlost/e5399f839261babf6251726f4528620b)

**What is the expected behavior?**
Flow thinks the react-redux lib def is just peachy and instead complains about how awful my code is.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Local Environment Information**
[gist of local env](https://gist.github.com/carlost/2bcbc4771969f28dd663c585502e8eab)

**Additional Details**
I am in the process of updating react-native from v0.61.2 to v0.63.3.  As part of that process i migrated flow-bin from v0.105.2 to v0.122.0.  My project was NOT previously using a flow-typed file for react-redux.  Flow v0.122.0 pointed that out.  After I installed the react-redux_v7.x.x.js lib def, flow-bin started complaining about the lib def itself.

I then tried installing the react-redux_v7.x.x.js lib def with the master project source that is still running flow-bin v0.105.2.  I got the same errors.  So this isn't an issue that was created by moving to flow-bin v0.122.0.

Has anyone seen anything like this?  If not, I will create a greenfield react-native project with react-redux to see if I can recreate the issue.  I am not sure if this is a **real** issue with flow and the react-redux lib def ... or just a local **me** issue.  Smart money is on it being a **me** issue.

**Comment by Brianzchen** [comment]
Are you still having an issue with this? FYI it at least has worked fine for me for the past 10 versions+

**Comment by Brianzchen** [comment]
Closing because no reply
