### ISSUE TITLE
Move to github actions from travis?

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#3949]
**What is the current behavior?**
New builds now take forever because of an apparently recent change to travis that stifles open source projects.
related: https://www.theregister.com/2020/11/02/travis_ci_pricng/

Was recommended that we should switch to github actions. Which should be reliable and has unlimited runs

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a PR in flow-typed and you'll be waiting for the build for over an hour

**What is the expected behavior?**
It should run and finish within 4 minutes

**If this is a feature request, what is motivation or use case for changing the behavior?**
Builds are slow

**Local Environment Information**
The build machine

**Comment by pascalduez** [comment]
Hey @Brianzchen,

thanks for the heads up. Why not basically. Do you have experience with Github actions and could point us to the changes it would involve?

Requires @GAntoine @AndrewSouthpaw @villesau approval.

**Comment by GAntoine** [comment]
Yeah I mean I'm all for it. @Brianzchen if you're up for making the change feel free, if not I'll have a crack at it this weekend. Same goes for anyone else who wants to try to switch it.

**Comment by Brianzchen** [comment]
Happy to have a crack at it. At first test, it looks like as a first step, someone with permission needs to go to the github actions tab and commit a dummy ci file into master using the `set up a workflow yourself`. Which will create a `.github/workflows/main.yml`
https://github.com/flow-typed/flow-typed/actions

Without this, even if I create a workflow yml file it will do nothing. 

Then I can cleanup my PR will which will auto hook up with github actions and we're good.
https://github.com/flow-typed/flow-typed/pull/3950/files

I've already created a branch for testing and you can see my results here on my fork https://github.com/Brianzchen/flow-typed/actions/runs/379716941

**Comment by GAntoine** [comment]
Nice! File has been created and workflow activated. I removed `CultureHQ/actions-yarn` since it's deprecated and covered by `actions/setup-node`.

**Comment by Brianzchen** [comment]
Perfect. I guess my PR isn't really need anymore? But I'd think next step could be removing references to travis. Thoughts?

**Comment by GAntoine** [comment]
Sorta, the PR itself can be closed, but there might be changes needed to the file itself (which can be made in a new PR). For instance, I'm getting this error in the first build:

```
console.error src/lib/git.js:45
      { stderr:
         'Author identity unknown\n\n*** Please tell me who you are.\n\nRun\n\n  git config --global user.email "you@example.com"\n  git config --global user.name "Your Name"\n\nto set your account\'s default identity.\nOmit --global to set the identity only in this repository.\n\nfatal: empty ident name (for <runner@fv-az71-140.4m3zzvtiomjupclcytd1cd5yve.bx.internal.cloudapp.net>) not allowed\n',
        stdout: '',
        exitCode: 128 }
    console.error src/commands/install.js:548
        !! Failed to install underscore at /tmp/install-cmd-test-dir-840980/flowProj/flow-typed/npm/underscore_v1.x.x.js
    console.error src/commands/install.js:549
        ERROR: Error finding latest commit hash for definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js: undefined
```

I'm not familiar with Actions, so I don't know how I'd setup a Github user. We do have a secret `GH_TOKEN` on Travis, which I can transfer here (unless it's not necessary?).

Removing references to Travis would also be a good thing to cleanup, starting with renaming `travis.sh` or removing it entirely and inlining the commands.

**Comment by Brianzchen** [comment]
@GAntoine Cleanup done here and added before install script that will fix the error you referenced.
https://github.com/flow-typed/flow-typed/pull/3951

**Comment by AndrewSouthpaw** [comment]
Thanks for this work! I didn't realize about the change with Travis and was similarly wondering why builds were taking > 1 hr to complete.
