### ISSUE TITLE
state missing in Location type of react-router

### ISSUE THREAD

**Issue by abogacki** [flow-typed/flow-typed#3972]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using `useLocation` hook, state is missing in the `Location` object.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
import React from 'react';
import { useLocation } from 'react-router';

const SomeComponent:  React$ComponentType<{}> = () => {
  const { pathname, search, state } = useLocation();
  return  </>
 }
```
Destructuring state throws `property state is missing in  Location` error:
![image](https://user-images.githubusercontent.com/32131726/101887587-61b3a700-3b9d-11eb-9b50-4bf80fa9650f.png)

**What is the expected behavior?**

State is recognized as part of `Location`.

Possible solution is to add `state` to `Location`:
```
declare module 'react-router' {
  // NOTE: many of these are re-exported by react-router-dom and
  // react-router-native, so when making changes, please be sure to update those
  // as well.
  declare export type Location = {
    pathname: string,
    search: string,
    hash: string,
    state?: any,
    ...
  };
```

**Comment by pascalduez** [comment]
Are you up to date with the libdef, cause it's was added https://github.com/flow-typed/flow-typed/pull/3772

**Comment by abogacki** [comment]
True, working just fine. Thanks.
