### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by kaushalyap** [flow-typed/flow-typed#3982]
I prefer Flow over Typescript, but lack of Flow type definitions in libraries is a problem. Is this project abandoned in favor of Typescript?

**Comment by GAntoine** [comment]
Hi @kaushalyap! Flow-typed, and the base Flow project, are still very much active. The difference in activity is largely due to Typescript's overall greater popularity to Flow. We plan to continue supporting flow-type library definition for the foreseeable future.

**Comment by kaushalyap** [comment]
Thanks good to know, but some library type definitions seems very old. ex: Material-UI

**Comment by GAntoine** [comment]
> some library type definitions seems very old

Absolutely, the most up-to-date libraries are ones used by avid/active Flow users, and the Facebook team. Material-UI is also notably difficult to type and update (search the PR history for some examples).

**Comment by Brianzchen** [comment]
You can check the commit history to clearly see there's a steady number of commits going into this project. Though as @GAntoine pointed out, if a lib def is very old it's probably a good assumption that no one in the "avid" flow community uses this dep.

For example I'm pretty sure no one that uses flow also uses koa because the lib defs were completely broken until I fixed them 😅 

Regardless if you prefer flow over TS, it's not hard to contribute and help us maintain the deps you use so that it's easier for future devs to get started with flow.

**Comment by kaushalyap** [comment]
@GAntoine @Brianzchen Cannot we do some automation using https://github.com/joarwilk/flowgen in order to generate flow types from TS type definitions?

**Comment by Brianzchen** [comment]
So if we're talking about material-ui you can but there would still be a level of user intervention required. First, given that all the files are embedded inside the actual repo they are broken up by [components](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/Alert/Alert.d.ts) whereas flow-typed has a single file per lib def but you can declare all the modules in there like this.

```
declare module 'material-ui' {}
declare module 'material-ui/Alert' {}
// etc
```

Also automating every library potentially within definitely types might be risky given we have to manually write tests. But overall I think using that flowgen tool to convert the types wouldn't be a bad idea, just needs someone to do the work and make sure they work then contribute.

But what libraries are you mainly missing? I assume you're using react and for me, all the main libraries I use on a daily basis are typed well enough and whenever I find one that isn't I'd add it. eg: I plan to add `react-swipable` soon cause a [colleague](https://github.com/roukell) recently added it to our project and it's untyped so far.

**Comment by kaushalyap** [comment]
Side question @Brianzchen What IDE, editors, plugins do you use with flow?

**Comment by Brianzchen** [comment]
> Side question @Brianzchen What IDE, editors, plugins do you use with flow?

I use vscode with [Flow Language Support](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode). That's all you'll really need. Ideally if Atom was better I would use that, but I tried that months back and the editor is slow, and the plugin doesn't work in real time. A problem with lack of dev support I guess.

**Comment by kaushalyap** [comment]
Thanks @Brianzchen 

I will close this now.

**Comment by AndrewSouthpaw** [comment]
Just wanted to say, thanks for the input and guidance @Brianzchen!
