### ISSUE TITLE
Latest version of flow-typed cli can't run "flow-typed install"

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#3988]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm currently running an older version of flow-typed and whenever I install a new dep I would run `flow-typed install` and it would update all my defs for me.

But for my colleagues who are just getting started with flow, who install the latest version of flow-typed aren't able to run this command, they can run `flow-typed install dep@version` though. Below is a screen grab of errors they get

<img width="1792" alt="Screen Shot 2021-01-09 at 1 25 24 pm" src="https://user-images.githubusercontent.com/12436524/104083929-bdee1180-5296-11eb-9fdc-ea113c70eb85.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

```
yarn global add flow-typed
# go into a project
flow-typed install
```

**What is the expected behavior?**
It should scan package.json and install new/update lib defs

**Local Environment Information**
```
System:
  OS: macOS 11.1
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 378.20 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
 Binaries:
  Node: 14.15.1 - /usr/local/bin/node
  Yarn: 1.22.10 - /usr/local/bin/yarn
  npm: 6.14.10 - /usr/local/bin/npm
 Managers:
  Homebrew: 2.7.0 - /usr/local/bin/brew
  pip3: 19.2.3 - /usr/bin/pip3
  RubyGems: 3.0.3 - /usr/bin/gem
 Utilities:
  Make: 3.81 - /usr/bin/make
  GCC: 4.2.1 - /usr/bin/gcc
  Git: 2.23.0 - /usr/local/bin/git
  Clang: 1200.0.32.28 - /usr/bin/clang
 Servers:
  Apache: 2.4.46 - /usr/sbin/apachectl
 SDKs:
  iOS SDK:
   Platforms: iOS 14.3, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
 IDEs:
  Nano: 2.0.6 - /usr/bin/nano
  VSCode: 1.52.1 - /usr/local/bin/code
  Vim: 8.2 - /usr/bin/vim
  Xcode: 12.3/12C33 - /usr/bin/xcodebuild
 Languages:
  Bash: 3.2.57 - /bin/bash
  Java: 14.0.2 - /usr/bin/javac
  Perl: 5.28.2 - /usr/bin/perl
  PHP: 7.3.24 - /usr/bin/php
  Python: 2.7.16 - /usr/bin/python
  Python3: 3.8.2 - /usr/bin/python3
  Ruby: 2.6.3 - /usr/bin/ruby
 Databases:
  MongoDB: 4.4.0 - /usr/local/bin/mongo
  SQLite: 3.32.3 - /usr/bin/sqlite3
 Browsers:
  Chrome: 87.0.4280.88
  Safari: 14.0.2
 Monorepos:
  Yarn Workspaces: 1.22.10
```

**Comment by Brianzchen** [comment]
For extra reference though when I run `flow-typed --version` I'm on `3.2.1` which is latest but I don't seem to have the same issue, any possibility there's a miss config from new installers?

**Comment by iworkinprogress** [comment]
@Brianzchen Running into this as well. You ever find a work around?

**Comment by Brianzchen** [comment]
No, I personally don't have the issue so I try to run `flow-typed install` for my team. But if you just want to install something specific you can use `flow-typed install dep@version`

Though without `flow-typed install` I can't run through all my deps and get latest lib def changes

**Comment by ticky** [comment]
I'm seeing this too, it seems to be related to having `flow-bin` in a `package.json` with a semver expression like this: `^0.100.0`. If I change that to just `0.100.0` it works fine.

It also seems to happen on 3.2.0, so isn't specifically the latest version's problem. I haven't had a chance to test more versions.

**Comment by killpapertiger** [comment]
Running into this as well
the steps listed below:

[killpapertiger]# ./node_modules/.bin/flow-typed update
• Found 37 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: Invalid npm libdef version! It appears to be a non-continugous range.
    at pkgVersionMatch (/home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:256:11)
    at /home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:281:82
    at Array.filter (<anonymous>)
    at filterLibDefs (/home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:275:15)
    at findNpmLibDef (/home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:329:27)
    at async /home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/commands/install.js:273:20
    at async Promise.all (index 35)
    at async installNpmLibDefs (/home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/commands/install.js:268:3)
    at async Object.run (/home/konglinglei/code/try/outline-scratch/node_modules/flow-typed/dist/commands/install.js:149:27)



and package.json is here




{
  "name": "line-scratch",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "clean": "rimraf build",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build:i18n": "i18next 'server/**/*.js' && mkdir -p ./build/shared/i18n && cp -R ./shared/i18n/locales ./build/shared/i18n",
    "build:server": "babel -d ./build/server ./server && babel -d ./build/shared ./shared && cp package.json ./build && ln -sf \"$(pwd)/webpack.config.dev.js\" ./build",
    "build": "yarn clean && yarn build:i18n && yarn build:server",
    "start": "node ./build/server/index.js",
    "lint": "eslint server shared",
    "flow": "flow"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "2": "^3.0.0",
    "@babel/core": "^7.12.10",
    "@babel/plugin-proposal-decorators": "^7.12.12",
    "@babel/plugin-transform-destructuring": "^7.12.1",
    "@babel/plugin-transform-regenerator": "^7.12.1",
    "@babel/preset-env": "^7.12.11",
    "@babel/preset-flow": "^7.12.1",
    "@octokit/core": "^3.2.4",
    "babel-plugin-lodash": "^3.3.4",
    "babel-plugin-styled-components": "^1.12.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "crypto": "^1.0.1",
    "date-fns": "^2.16.1",
    "debug": "^4.3.1",
    "dotenv": "^8.2.0",
    "flow-typed": "^3.2.1",
    "http-errors": "^1.8.0",
    "i18next": "^19.8.4",
    "i18next-http-backend": "^1.0.21",
    "i18next-parser": "^3.6.0",
    "jsonwebtoken": "^8.5.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-i18next": "^11.8.5",
    "semver": "^7.3.4",
    "sequelize": "^6.3.5",
    "sequelize-cli": "^6.2.0",
    "sequelize-encrypted": "^1.0.0",
    "styled-components": "^5.2.1",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.12.10",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.17.0",
    "eslint-plugin-flowtype": "^5.2.0",
    "eslint-plugin-react": "^7.22.0",
    "flow-bin": "^0.141.0",
    "rimraf": "^3.0.2"
  }
}

**Comment by lportanel** [comment]
I had the same problem on `flow-typed@3.2.1`.
After running `npm view flow-typed versions`, I tested on several versions, and it started to fail from version `3.0.0`.

My workaround, for now, is to switch to a prior version:
```
npm install -g flow-typed@2.6.2
flow-typed install
```

**Comment by joaocarmo** [comment]
Same issue here, with `flow-typed@3.2.1` and `flow-bin@0.144.0`.

@ticky's solution was the workaround for me on `package.json`:

```diff
{
    // ...
-   "flow-bin": "^0.144.0",
+   "flow-bin": "0.144.0",
    // ...
}
```

**Comment by Brianzchen** [comment]
Hi all, update that I've found the issue and created a PR. I will subsequently raise an issue with the semver project regarding patches breaking this project.

**Comment by josemigallas** [comment]
For some reason that workaround is not working for me 😩 
```
$ cat package.json | grep flow-
    "flow-bin": "0.144.0",
    "flow-typed": "3.2.1",

$ yarn flow-typed install
yarn run v1.22.5
$ /Users/jgallaso/projects/3scale/porta/node_modules/.bin/flow-typed install
• Found 101 dependencies in package.json to install libdefs for. Searching...
• rebasing flow-typed cache...
UNCAUGHT ERROR: Error: Invalid npm libdef version! It appears to be a non-continugous range.
    at pkgVersionMatch (/Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:256:11)
    at /Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:281:82
    at Array.filter (<anonymous>)
    at filterLibDefs (/Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:275:15)
    at findNpmLibDef (/Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/lib/npm/npmLibDefs.js:329:27)
    at async /Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/commands/install.js:273:20
    at async Promise.all (index 37)
    at async installNpmLibDefs (/Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/commands/install.js:268:3)
    at async Object.run (/Users/jgallaso/projects/3scale/porta/node_modules/flow-typed/dist/commands/install.js:149:27)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Could it be something else? 😟
