### ISSUE TITLE
@apollo/client types aren ot available for modern versions of flow?

### ISSUE THREAD

**Issue by danielo515** [flow-typed/flow-typed#4061]
Hello,
I took a quick look at the repo after getting this error:

```
!! No flow@v0.123.0-compatible libdefs found in flow-typed for the explicitly requested libdefs. !!
```

and I saw that the only apollo definitions available are for flow 0.104 or so. Can't I use the same definitions for my current flow version? What's the workaround?

**Comment by Brianzchen** [comment]
So it looks like there is `apollo-client` which I can't see being defined incorrectly. But you're looking for `@apollo/client` which doesn't exist, see [here](https://github.com/mrtnzlml/flow-typed/tree/master/definitions/npm/%40apollo).

I guess my recommendation is that you copy the `apollo-client_v2.x.x` to `@apollo/client_v3.x.x` for a start. I'm not sure how accurate it is these days but it's quite large so it's probably a good base to begin with. Then as you start using it you can refine the lib def and hopefully you commit it back for others 🙂

**Comment by danielo515** [comment]
You're right @Brianzchen 
I think I will copy just the TS definitions that I need (ts is maintained by the team).
I use really few functions from @apollo/client, so making a PR back to this will probably not help many.

Thanks

**Comment by jedwards1211** [comment]
I patched some of those files in my local repo, maybe eventually I can get around to making a PR 😅

**Comment by Brianzchen** [comment]
Either way if someone creates an initial PR it would take the load off someone less familiar who wants to use the definition and wants to contribute back. I don't personally use apollo so it's not something I'd do, but I'm sure it's valuable for the wider flow community.

**Comment by jedwards1211** [comment]
Actually I'm confused what the deal is here since all of the Apollo client 3 defs are `flow_v0.104.x-`, dash at the end means they should get installed for Flow 0.123.0.
In any case, I'm about to make a PR with some updates

**Comment by jedwards1211** [comment]
Oh now I know...OP is probably using Apollo client 4.
Unfortunately I can't contribute to that yet because I'm stuck on Apollo client 3, and there were some pretty big changes in v4.
