### ISSUE TITLE
[@testing-library/react] matcher return type improvement

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#4117]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Currently with react testing library, when using the various `getByTestId`, `screen.getByTestId`, `render.getByTestId`, `findAllByTestId` and etc always return as `HTMLElement`. This is not very ergonomic and I've had a problem with this for over a year shown by my attempted fix https://github.com/flow-typed/flow-typed/pull/3837.

We currently need to write code in the form of
```
const element: HTMLAnchorElement = (screen.getByTestsId('test'): any);
expect(element.href).toBe('blah');
```
Or without type casting but produces more code
```
expect.hasAssertions();
const element = screen.getByTestsId('test');
if (element instanceof HTMLAnchorElement) {
  expect(element.href).toBe('blah');
}
```
When people without flow would write it as 
```
expect(screen.getByTestsId('test').href).toBe('blah');
```

**What is the expected behavior?**
I'd like to change the defined type and related types to be like the following
```
declare type ReturnElements = HTMLElement & HTMLButtonElement & HTMLInputElement & ...;

declare type GetByBoundAttribute = (
  text: TextMatch,
  options?: TextMatchOptions
) => ReturnElements;
```
In this way, `getByTestId` is never returned as `any` but always has the advantage of easily casting into a specific HTMLElement or just using as is just like in the without flow example above

cc: @pascalduez would appreciate your feedback here!

**Comment by pascalduez** [comment]
I understand the frustration, also happens to me.  

But we already discussed it with the Flow core team if I remember correctly, and looks like there wasn't much solutions at our hands.

My personal feeling (probably biased with a lack of deep understanding of Flow internals) is you're putting too much confidence in intersections lately (no offence intended :) 

`type ReturnElements = HTMLElement & HTMLButtonElement & HTMLInputElement & ...;` would means it can return any kind of element, or more a sort of meta element with all possible attribute/methods, so we are going a bit against Flow soundness principles. 

I don't want to gives a negative feedback here, just sharing concerns.
Maybe it's fine at the end.   
Once again, if we can gather more feedback than mine, would be good ;)

**Comment by Brianzchen** [comment]
> My personal feeling (probably biased with a lack of deep understanding of Flow internals) is you're putting too much confidence in intersections lately (no offence intended :)

Haha sorry I guess my discovery and understanding of intersection has opened up a lot of doors on how to type things in a more unique way to solve my problems.

> type ReturnElements = HTMLElement & HTMLButtonElement & HTMLInputElement & ...; would means it can return any kind of element, or more a sort of meta element with all possible attribute/methods, so we are going a bit against Flow soundness principles.

I agree, this meta element goes against the grain of type safety and basically makes return of `getByTestId` somewhat untyped, but my judgement is that this is test code which doesn't need the runtime safety of logic code, if `href` for example isn't found you ideally want RTL to crash and you know the element you grabbed isn't correct but at least there is some type checking so you'll type it correctly as `href` instead of `hhef`

**Comment by AndrewSouthpaw** [comment]
... which I realize is basically what @Brianzchen said in the second paragraph. 😅  So, I agree. If there's a light-weight way to cudgel a few types together to encompass all possible return types, I call that good enough.
