### ISSUE TITLE
flow-typed ignore file

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#4127]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When I run `flow-typed install` it goes through package.json to install all deps I may use. But there some libs that I can't imagine I would ever get typed such as `eslint-x` `@babel/preset-x` `@babel/plugin-x`. As a result running the install command always updates stubs which generates more noise in my PR than is desirable.

Second problem: I sometimes run a mono repo application where a library then wouldn't have any flow files (I use them uncompiled), so when I run `flow-typed install` it would install stubs. I then have to delete it, my alternative is to create a `stub.js.flow` file in the lib so that flow-typed won't try to install stubs that override whatever types are defined in my uncompiled js code.

## Solution
I would like flow-typed to support an ignore file `.flowtypedignore` (not fussed on the name) that live in the root dir where I can specify some exact matches to library names that I don't want to have flow-typed try to install.

Future thinking we could expand this ignore file to work on particular scopes and wildcards, but the simplest use case would work well for now.

**Comment by AndrewSouthpaw** [comment]
Nice! Seems useful. I'd prefer to put it in `/flow-typed` to keep things self-contained and not pollute the root scope. I'm curious if you had specific reasons for putting it at the root?

**Comment by Brianzchen** [comment]
> Nice! Seems useful. I'd prefer to put it in `/flow-typed` to keep things self-contained and not pollute the root scope. I'm curious if you had specific reasons for putting it at the root?

Nah I actually prefer if it was `flow-typed/.ignore` I just thought people would prefer root to match stuff like `.gitignore` `.npmignore` and those kinds of standards

**Comment by pascalduez** [comment]
It might have it's use, I have to admin every time it installs me the `flow-bin` libdef I'm a bit mehish :)
But did you know of the `--skip` CLI flag? Can already do a good part of the job.

**Comment by Brianzchen** [comment]
According to the wiki, `--skip` is a boolean that disables installing stubs. That's not really what I'm looking since there are lib defs that are stubbed that I definitely want to keep around but I haven't gotten around to adding to flow-typed and I'm ok with them being any typed. I want this `.ignore` list because there are some deps that I'll never use they are only for tooling like `babel` so I just don't want those to keep making revision diffs every time me or my team runs `flow-typed install` which generated huge PR diffs
