### ISSUE TITLE
flow-typed install doesn't install deps deps

### ISSUE THREAD

**Issue by Brianzchen** [flow-typed/flow-typed#4137]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I have libraries that ship with `flow.js`, `flow-typed install` does not check those libs for their dependencies packages to add to the flow-typed/npm dir.

This is frustrating because flow will throw errors for module not found. Instead I need to check node_modules find the library and see what version of the missing libdef and then manually install each of them.

**If this is a feature request, what is motivation or use case for changing the behavior?**
When I run `flow-typed install` there is already logic to not install stubs or defs for `flow.js` dependencies, maybe we can also check out dependencies to see internally if they have `flow.js` and then install lib defs for that dependency's dependencies. 

**Example:**
I have a dependency called `a@1.2.3`, it has `flow.js` so that's great I don't need lib defs and I can get type checking out of the box. But `a@1.2.3` depends on `b@1.1.1`, this does NOT have `flow.js` files and as package `a` was being built it used `flow-typed`. When I install `a@1.2.3` and then run `flow-typed install` I should expect to see `b@1.x.x` installed into my flow-typed

**Comment by pascalduez** [comment]
> this does have flow.js files and as package a was being built it used flow-typed.

I don't get that sentence.

If both packages a and b have properly formed .flow.js files along the sources, then Flow will do it's job, no flow-typed should be involved here.

**Comment by Brianzchen** [comment]
> I don't get that sentence.

Sorry, added **NOT** keyword that was missing 😅

**Comment by Brianzchen** [comment]
https://github.com/flow-typed/flow-typed/issues/3850
Turns out I posted about the same problem a year ago
