### ISSUE TITLE
Installed libdef for Jest is sometimes empty

### ISSUE THREAD

**Issue by knutanderss** [flow-typed/flow-typed#4138]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
`flow-typed install` will sometimes install the complete libdef for Jest and other times just leave an empty libdef-file for Jest.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add `"jest": "^27.2.0"` as a dependency in package.json and execute `flow-typed install --overwrite` several times and check the content of flow-typed/npm/jest_v27.x.x.js. Sometimes it is empty and sometimes not.

**What is the expected behavior?**
The libdef for Jest should never be empty.

**Local Environment Information**
https://gist.github.com/knutanderss/7f90d32538c1e33139e1e722965e10a2

**Comment by Brianzchen** [comment]
Happens to me and my team frequently also but never found a reliable way to test to find a fix. How many times did you have to run `flow-typed install --overwrite`? I ran it a few times but couldn't reproduce

**Comment by knutanderss** [comment]
The command seems to do what it is supposed to every fourth time or so. And then I run it once more, and the libdef file has been cleared again.

I checked the output of the command with `--verbose`, they look the same both when the command works and not.

**Comment by Brianzchen** [comment]
I can observe this issue happening but it's so difficult to reproduce reliably, `--overwrite` doesn't seem to ever throw the issue again. If you or anyone else has a suggestion of reproduction that would be good. Otherwise it will be quite difficult to find a fix. I'll keep digging whenever I get a chance though

**Comment by Brianzchen** [comment]
@knutanderss happy new year! I just wanted to let you know I made a few changes to flow-typed cli with stability which has just been released, I wonder if it helped this issue. If you haven't tried would you like to give 3.6.0 a go and report back in the future if you're still intermittently experiencing this issue?

**Comment by knutanderss** [comment]
I tested it just now, and I couldn't reproduce the error with 3.6.0. Thanks!!

**Comment by Brianzchen** [comment]
🎉 that's great news! I will leave this issue open for the next month in case it does happen but I'll consider this fixed for now

**Comment by Brianzchen** [comment]
Happy Lunar New Year!
