### ISSUE TITLE
React Router hooks generic type support

### ISSUE THREAD

**Issue by bottd** [flow-typed/flow-typed#4272]
Hello, I am trying to work with the flow types for react-router v5. I am running into issues with the typings for `useParams`. I believe `useParams` needs support for generics in order to support accurate typings. Currently, the type for `useParams` is:
```js
declare export function useParams(): $PropertyType<$PropertyType<ContextRouter, 'match'>, 'params'>;
```
This results in the following return type:
```
{ [key: string]: ?string, ... },
```
This causes issues because we cannot define what the keys should be within 'params'. Due to how `useParams` is used, you can guarantee that a key will not be `null` or `undefined`. Due to these types I end up with errors because my key that is always string is seen as possibly `null` or `undefined`. 

The typings within [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts) allow for providing a type for params:
```
export function useParams<Params extends { [K in keyof Params]?: string } = {}>(): Params;
```

If it is okay to make this update I would be happy to make the PR happen.

**Comment by Brianzchen** [comment]
Hi @bottd that sounds great, I've personally used this and found it quite annoying too (I tended to just move on with my life as opposed to improving it 😅 ). But I agree params for url slugs makes sense to be populated if consumer is sure of the route passed in.

If you're happy to make the change yourself please go ahead and make the changes remembering to add some tests to verify this usage as well as if a user opts not to use generics.

Let me know if you need any help along the way 🚀

**Comment by bottd** [comment]
@Brianzchen thanks for the help! I opened a PR for this, let me know if you have any thoughts on my proposed change.
