### ISSUE TITLE
Need a notion of "ownership" for libdefs

### ISSUE THREAD

**Issue by jeffmo** [flow-typed/flow-typed#433]
Right now libdefs get skimmed for quality traits (things like over-use of `any`, etc) -- but it's easy to miss issues with details of a libdef that someone more familiar with the library might catch.

To solve this, we should build some notion of "ownership" for a libdef so that flow-typed can ping one or more of the owners for review. This should also help distribute the effort of review better if an "owner" of a libdef is also able to merge a given libdef (say, via a GitHub bot).

**Comment by GAntoine** [comment]
Closing as we support code owners via the CODEOWNERS file

**Comment by pascalduez** [comment]
@GAntoine CODEOWNERS file only works if the listed users are part of the GitHub org, if I'm not mistaken...

**Comment by GAntoine** [comment]
I don't think that's the case, I've seen it work with non-organization members. Let me try it in an upcoming PR with a random non-member.
