### ISSUE TITLE
How can I convert computed property name types from typescript to flow

### ISSUE THREAD

**Issue by aakashsardana** [flow-typed/flow-typed#4337]
### What do you want to know?

In @testing-library/user-event v14 there are types defined something like this

```
declare const UIValue: symbol;

declare global {
    interface Element {
        [UIValue]?: string;
    }
}
```
What can be the equivalent flow-types for this?

Especially for [UIValue]? : string

Thanks

**Comment by Brianzchen** [comment]
I assume you're referring that snippet from TS? If so could you post a link to that snippet just so I can get more context

**Comment by Brianzchen** [comment]
Closing, no reply
