### ISSUE TITLE
react-router-dom_v6 is mixing types from multiple packages

### ISSUE THREAD

**Issue by iamdey** [flow-typed/flow-typed#4421]
### Library definition file name

react-router-dom_v6

### Your dependent version

6.0.0

### Flow Version

0.104.x-

### Description

Hi,

Currently react-router-dom@6 types are mixing 3 packages from the same editor and use a kind of inheritance.

https://github.com/remix-run/react-router/tree/40d49e1/packages

> react-router-dom > react-router > @remix-run/router

_(Almost all typescript types and utilities are re-export on each package so it's not required add the whole chain as deps)_

In the current state typing from react-router cannot be reused in `react-router-native for example.

* flow-typed recommend not to follow Don't Repeat Yourself principle and [includes 3rd parties types into the definition](https://flow-typed.github.io/flow-typed/#/contributing?id=don39t-import-types-from-other-libdefs)
* But next version seems [to change this affirmation](https://github.com/flow-typed/flow-typed/blob/main/CONTRIBUTING.md#importing-types-from-other-libdefs)

**So,**
I have in mind to reorganize file to make visual separation between those packages in the definition file. Best effort, no breaking changes, no evolution, just reorganize.

For example:

```js
declare module "react-router-dom" {
  // ----------------------------------/
  // `@remix-run/router`         /
  // ----------------------------------/
  declare export type AgnosticIndexRouteObject = {|
    ...AgnosticBaseRouteObject,
    children?: void;
    index: true;
  |};
  …
  // ----------------------------------/
  // `react-router`                    /
  // ----------------------------------/
  declare export type RouteProps = PathRouteProps | LayoutRouteProps | IndexRouteProps;
  …

  // ----------------------------------/
  // `react-router-dom`            /
  // ----------------------------------/
  declare export var BrowserRouter: React$ComponentType<{|
    basename?: string,
    forceRefresh?: boolean,
    getUserConfirmation?: GetUserConfirmation,
    keyLength?: number,
    children?: React$Node
  |}>
  …

  // ----------------------------------/
  // WIP (or unofficial)            /
  // ----------------------------------/
  …
}
```

I don't have example right now for `WIP` section but I suppose I'll find intermediate types I don't know where to put.

What do you think?

### Do you want to submit a pull request to fix this issue?

Yes

**Comment by Brianzchen** [comment]
Hello there! Flow-typed maintainer and implementor of next version here. If you want to make these changes please feel free to do so targeting `main`, I'm always happy to see more contributors and people that want to show our repo some love.

I will help you to review and hopefully push it across the line.

On to note @GAntoine looks like more interested in shifting `main` to be the main target branch :)

**Comment by iamdey** [comment]
@Brianzchen I am grateful to you for taking part in the discussion.

Well first of all, do you have any procedure to backport definitions' changes to the `main` branch? 
It seems that if I target master, you usually merge master into main so it will benefits to both branches.

I still think I should begin with the simple «file reorganization» before any refactoring even if I target `main`. Are you OK with that?
