### ISSUE TITLE
[Question]: is jest libdef always installed by flow-typed by default?

### ISSUE THREAD

**Issue by SijanC147** [flow-typed/flow-typed#4426]
### What do you want to know?

I'm using mocha/chai for unit tests in my project, and whenever I run `flow-typed install` I always get `jest_v27.x.x.js` typedefs even though this library is not in my package.json, nor does it show up anywhere when I try to run `yarn why jest`. 

When installed, flow starts throwing all sorts of errors on all my unit tests, so i'm kind of confused as to why flow-typed would add this def, am i missing something? 

thanks in advance for any assistance 🙏

**Comment by Brianzchen** [comment]
May I ask what version of flow-typed you're on? You'll get the answer with `flow-typed --version`

**Comment by SijanC147** [comment]
Hey, thanks for getting back to me, it's `3.8.0`

**Comment by Brianzchen** [comment]
Thanks, I had assumed maybe it's to do with dependent definitions but that's in 4.x.x.

It could be to do with workspaces off the top of my head, we can try solving this anomaly which may highlight a bug which I'll need as much info about your repo as you can provide.

---

But for a quick fix you can leverage the `flow-typed.config.json` by adding the [ignore](https://flow-typed.github.io/flow-typed/#/flow-typed-config?id=ignore) property. Try this and let me know if it helps?

**Comment by SijanC147** [comment]
Hello, sorry for the delayed reply, but thank you so much for the suggestion, setting up a `flow-typed.config.json` file did the trick! 🙏
