### ISSUE TITLE
[Question]: Errors in flow-typed definitions

### ISSUE THREAD

**Issue by simkessy** [flow-typed/flow-typed#4471]
### What do you want to know?

I upgraded to flow 0.201 but now im getting errors in my flow definitions for @apollo and @lodash-es. I tried to set those two files under [untyped] but it's not getting ignored by the compiler

# Example of errors im seeing 
![image](https://github.com/flow-typed/flow-typed/assets/5871660/b1273990-e47f-44f5-8847-1b15fad34cf9)
![image](https://github.com/flow-typed/flow-typed/assets/5871660/f5919d57-bfbc-4ea2-a410-a1f93d718bdb)

FlowConfig.js

```
[version]
0.201.0

[ignore]
.*/**/malformed_package_json/package.json

[include]
../../../node_modules/

[libs]
<PROJECT_ROOT>/flow-typed/

[options]
sharedmemory.hash_table_pow=21
exact_by_default=true
autoimports=true
react.runtime=automatic
emoji=true
include_warnings=true

[declarations]
.*/node_modules/draft-js/*
.*/node_modules/fbjs/*

[untyped]
.*/flow-typed/npm/@apollo/client_v3.x.x.js
.*/flow-typed/npm/lodash-es_v4.x.x.js
<PROJECT_ROOT>/flow-typed/npm/lodash-es_v4.x.x.js
<PROJECT_ROOT>/flow-typed/npm/@apollo/client_v3.x.x.js
```

**Comment by pascalduez** [comment]
Those looks like severe issues in the Apollo lib definitions that were previously missed :\

They will need to be fixed for sure, open to PRs...

In the meantime did you try adding them under `[declarations]` instead?

**Comment by Brianzchen** [comment]
Made some fixes therefore closing, let me know issues persist
