### ISSUE TITLE
[Test CI] Automatically comment on PRs that add `any` types

### ISSUE THREAD

**Issue by jeffmo** [flow-typed/flow-typed#49]
We want the libdefs in this repository to remain high quality. As such, we want to minimize `any` types as much as is reasonably possible. In some cases an `any` type of some kind (including things like `Object`, `Function`, etc) is unavoidable -- so we can't simply ban them altogether.

To minimize the number of unnecessary `any` types, it would be good to have Travis check for these and comment on any pull requests that add them -- pointing out that they should be avoided if at all possible.

Perhaps something like a `--strict` flag could be added to the `validate-defs` command that emits warnings on these kinds of things?

**Comment by ryyppy** [comment]
@marudor did a great job adding some linting in here... are we done with this or is something still missing?

**Comment by marudor** [comment]
Still open.
We have // $ExpectError checks, but not any checks. I'm planning on doing them.

**Comment by relekang** [comment]
I created a lint rule for any, Function and Object for a private project. [I added it to a fork of eslint-plugin-flow-typed](https://github.com/jeffmo/eslint-plugin-flow-typed/compare/master...relekang:no-weak-types) yesterday when I saw this. I can send a PR if you want? Not sure about the name though.

**Comment by thejameskyle** [comment]
@relekang send a PR for sure

**Comment by relekang** [comment]
[I did](https://github.com/jeffmo/eslint-plugin-flow-typed/pulls), and now I realised nobody is watching the repo. So leaving a note here :)

Also, would it be interesting to add [fastlint][] or [lint-filter][] to the travis build to be able to indicate that new PR are breaking this?

[fastlint]: https://github.com/mixu/fastlint
[lint-filter]: https://github.com/relekang/lint-filter

**Comment by relekang** [comment]
I found [eslint-plugin-flowtype/no-weak-types]https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-no-weak-types and created a PR to this repo with config for that and will close my PR against eslint-plugin-flow-typed.

**Comment by jeffmo** [comment]
#335 doesn't quite solve this issue since the errors aren't surfaced in the PR in some way, but it's definitely a big step in the right direction!

**Comment by relekang** [comment]
@jeffmo Looks like [Hound CI has support for eslint](https://houndci.com/configuration#eslint) and does inline comments of lint warnings. Might be an option?
