### ISSUE TITLE
Support modular definitions

### ISSUE THREAD

**Issue by alexandradeas** [flow-typed/flow-typed#627]
I'm relatively new to `flow-typed` so I apologize if this functionality already exists and I just haven't been able to find it, although my initial playing around with it doesn't seem to indicate that it's currently possible.

It would be nice to support nested definitions of modules for repositories, I'm currently look at adding the libdefs for Ramda v0.23, the most recent version being v0.21. Obviously the changes between 2 minor versions aren't huge and a lot of stuff is reusable from v0.21. However, as it currently stands, it appears that I'd need to add a `definitions/npm/ramda_v0.23.0` directory to sit alongside the existing `definitons/npm/ramda_v0.21.x` libdef.

It'd be nice to define a structure such as
```
|-- definitions/
    |-- npm/
        |-- ramda_vx.x.x/
                |-- ramda_v0.x.x/
                    |-- generic.js
                    |-- ramda_v0.21.x/
                        |-- [v0.21 libdefs]
                        |-- ramda_v0.21.1/
                            |-- [v0.21.1 libdefs]
                    |-- ramda_v0.23.x/
                        |-- [v0.23 libdefs]
```

Through this, sharing definitions between versions is not only easier but is encourages by the structure of definitions.

**Comment by Brianzchen** [comment]
This is something we probably won't ever implement unfortunately. Reusable types per library could be supported with environment definitions.

Though there's currently no way for a libdef to use an envdef but that's at least on my radar
