### ISSUE TITLE
Question: How difficult is it to translate TypeScript definitions?

### ISSUE THREAD

**Issue by toddw** [flow-typed/flow-typed#660]
I am using sequelize in one of my projects and Flow. I noticed there is a TypeScript definition for the library but no one has converted it to Flow types yet. How much work is it to convert?

Would it be possible to automate this? It would be awesome if we could automatically import all of the typescript definitions.

https://github.com/types/npm-sequelize

**Comment by codemonkey800** [comment]
Similar issue here: #635 

You can try out [flowgen](https://github.com/joarwilk/flowgen). It's not perfect, but it does a pretty good job so far. I tried testing it out on some files in that repo, and I found that it'll require a lot of manual work, so good luck!

**Comment by jedwards1211** [comment]
@toddw Sequelize types can be pretty dynamic...for instance when you relate a `Posts` model with a `User` model, sequelize creates `getPosts` and `setPosts` methods.  I've been wondering if flow types, for sequelize models at least, wouldn't be better generated automatically...

**Comment by jedwards1211** [comment]
@toddw for instance, I was trying to get clever in defining the return type of `get(field)` but I don't think there's actually a way to make flow automatically deduce the return type for a given field name:
```js
interface ModelInstanceAPI<T: Object> {
  get<K: $Keys<T>>(field: K): $PropertyType<T, K>; // I wish this worked...
}
```

However, if generating type defs with a code generation tool, it would be possible to overload the `get` method to have the correct return type for each field:

```js
/* @flow */

declare class Model {
  get(field: 'foo'): number;
  get(field: 'bar'): string;
}

var m = new Model()

m.get('foo').indexOf('.') // error: property `indexOf` not found in Number
m.get('bar').toFixed(3) // error: property `toFixed` not found in String
```

**Comment by pascalduez** [comment]
See https://github.com/flow-typed/flow-typed/pull/3387
