### ISSUE TITLE
react-redux: connect(...) doesn't retain statics' types

### ISSUE THREAD

**Issue by fmoo** [flow-typed/flow-typed#830]
As of react-redux@3.1.0, redux hoists non-react statics to the wrapper class. 

Is there some way to maintain the API of the wrapped class through the connect() call in addition to exporting a React.Component with similar Props?

**Comment by sibelius** [comment]
is this a problem with flow-typed or with connect?

**Comment by EugeneZ** [comment]
@sibelius It's a problem with the flow-typed definitions. If a class has static methods, `connect` will hoist these static methods to the returned component wrapper. The definitions do not reflect these, so Flow thinks the returned component wrapper does not have these static methods when it in fact does.

**Comment by SBoudrias** [comment]
I'd like to help fix this issue, but I don't know how to define the statics of the input component as a value we can reuse later?

**Comment by sibelius** [comment]
maybe take a look here https://github.com/flowtype/flow-typed/blob/master/definitions/npm/hoist-non-react-statics_v2.x.x/flow_v0.54.1-/hoist-non-react-statics_v2.x.x.js
