### ISSUE TITLE
expressjs: switch `request.body` back to `mixed` from `any`

### ISSUE THREAD

**Issue by gabor** [flow-typed/flow-typed#871]
can we talk about #813 and possibly reverting it?

the argument for #813 was that it's inconvenient to handle a `mixed` definition for `request.body`, so let's go with `any`. i think that:
1. the flow-types should be as precise as possible about describing the data-structures. the whole reason for me using flow is that it enforces the structure of data.
2. if you want to write code that does not crash when invalid data is sent to it, you will have to do all those checks anyway.

please note, that this is a discussion about what is the better default (`any` or `mixed`). (one can always cast `any` into `mixed` or `mixed` into `any`)

i understand the inconvenince involved with using a `mixed` `request.body`. we flow-annotated our expressjs-using code when that type was still on `mixed`, and i admit it took a longer time to make flow happy. but, at the end, it made our code better. just pulling values out of `request.body` and hoping for the best will crash a nodejs application, if the request received is not of the correct form. with having it at `mixed`, flow basically forced us to handle things robustly, for example:

`any` way:
- take request.body.itemCount, and assume it's a number. this causes:
    - if `request.body` is not an object, nodejs will crash
    - if `request.body` does not have an `itemCount` attribute, nodejs will probably crash later when you try to use the `undefined` as a number
    - if `request.body.itemCount` is not a number, nodejs will probably crash later when you try to use the not-number as a number

`mixed` way:
- do a `typeof` check on `request.body` to make sure it's an `object`
- do a `typeof` check on `request.body.itemCount` to make sure it's a `number`
- with this approach you can be sure you get a number, and that you handled all the possible `bad request` cases

obviously, the situation is not black&white:
- maybe you are running a swagger-validator before your incoming request, so you are just sure that the data is in the correct format (my recommendation is that you simply cast it to `any` with a comment saying we are sure about the structure of the data because of swagger)
- maybe you have one function that extracts the data from `request.body` with `try...catch` so that the code does not crash if things go wrong. again, as before, you can just cast to `any` and go on.

**Comment by philikon** [comment]
I fully support going back to `mixed` for exactly the reasons you mention.

**Comment by pascalduez** [comment]
It's [currently using `mixed`](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.104.x-/express_v4.x.x.js#L17).
