### ISSUE TITLE
Enzyme: Wrapper#instance() returns React$Component instead of the original component class

### ISSUE THREAD

**Issue by Sparragus** [flow-typed/flow-typed#925]
[`Wrapper#instance()`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/enzyme_v2.3.x/flow_v0.28.x-/enzyme_v2.3.x.js#L50) has a return type of `React$Component<any, any, any>`. That is true, but not specific enough and if forcing me to add `$FlowFixMe` almost every time I use it.

Consider this class:

```js
class Map extend React.Component {
  zoom (zoomLevel: number): void {
    // ...
  }

  render () {
    //...
  }
}
```

And the test for `Map#zoom`:

```js
describe('#zoom', () => {
  it('zooms the map', () => {
    const tree = shallow(<Map />)
    tree.instance().zoom(16) // Flow error: property `zoom` Property not found in React$Component
  })
})
```

I think that error can be fixed using generics. If `Wrapper` knows that it is *wrapping* a type `T`, then it would be possible to do something like:

```js
declare class Wrapper<T> {
  instance(): T;
}
```

Furthermore, I think we can set a type of `React$Component<any, any, any>` to the generic `T` like so:

```js
declare class Wrapper<T: React$Component<any, any, any>> {
  instance(): T;
}
```

I would be very happy to send a PR to fix this, but I need guidance. Basically, I need to know if I'm on the right direction regarding this.

**Comment by Sparragus** [comment]
Fixed in https://github.com/flowtype/flow-typed/pull/950

**Comment by GAntoine** [comment]
@Sparragus Is this still an issue?

**Comment by Sparragus** [comment]
Not anymore, at least with `enzyme@3` and `flow-bin@0.53.0` :D

**Comment by alexgurr** [comment]
I'm having this issue:

enzyme@3.7.0
flow-bin@0.89.0

ideas?

**Comment by HsuTing** [comment]
enzyme@^3.8.0
flow-bin@^0.91.0

Have the same issue.
