### ISSUE TITLE
Add `// @flow` annotation to the flow-typed definitions

### ISSUE THREAD

**Issue by NameFILIP** [flow-typed/flow-typed#929]
Currently, `eslint-plugin-flowtype` linter fails for flow-typed definitions (See https://github.com/gajus/eslint-plugin-flowtype/issues/224). The reason is the way it decides if a file has flowtype definitions (See https://github.com/gajus/eslint-plugin-flowtype/blob/v2.32.1/src/utilities/isFlowFile.js#L17).

The question here is: 
Should flow-typed files have a `// @flow` on the first line of the file?
Alternatively, the plugin can be changed to check for something like `// flow-typed signature ...`

**Comment by Brianzchen** [comment]
Added docs for how to handle eslint errors from flow-typed
